### ISSUE TITLE
Outdated Google Cloud Platform logo

### ISSUE THREAD

**Issue by craigbox** [cncf/landscape#1]
Please update to the new version.

![logo_lockup_cloud_platform_icon_vertical](https://cloud.githubusercontent.com/assets/132510/20099933/dbfcd502-a5b2-11e6-990c-98f851af9868.png)

**Comment by craigbox** [comment]
(In case you also want to add the Google Cloud Storage logo to the "Cloud Native Storage" section, it can be found [here](https://upload.wikimedia.org/wikipedia/en/2/2e/Google_Cloud_Storage_logo.png)).

**Comment by dankohn** [comment]
Fixed, thanks.
