### ISSUE TITLE
Please add Kong to the Orchestration and Management, under Service Management 

### ISSUE THREAD

**Issue by daviesf1** [cncf/landscape#100]
Please add Kong to the Orchestration and Management, under Service Management

**Comment by shawnpreissner** [comment]
@daviesf1 thanks for the request, we'll include Kong in the upcoming release!

**Comment by shawnpreissner** [comment]
@daviesf1 just noticed Kong is already in API Management (within Application Definition & Development). Please let me know if we should leave it there, or you'd prefer it moved.

**Comment by dankohn** [comment]
Actually Service Management is the best fit here, thanks.

**Comment by shawnpreissner** [comment]
Thanks @daviesf1, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
