### ISSUE TITLE
Fetch Crunchbase delisted status

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#1001]
When a company has a stock ticker and IPO status is `delisted`, treat the stock ticker as null.

https://www.crunchbase.com/organization/octo-technology#section-overview
https://www.crunchbase.com/organization/rackspace#section-overview

Then, look at whether you can clear out the `stock_ticker: null` entries from landscape.yml/

**Comment by ZeusTheTrueGod** [comment]
I've asked a tech support about this field in the API, it is not inside the IPO and does not belong to the organization
