### ISSUE TITLE
Adding N|Solid to Languages & Frameworks section?

### ISSUE THREAD

**Issue by bnb** [cncf/landscape#101]
Hello! 👋

Just saw [this tweet](https://twitter.com/dankohn1/status/850306324676173826) and thought this was an *awesome* project. Looking at the chart, I realized that it's also applicable to my work and company. We offer [N|Solid](https://nodesource.com/products/nsolid), which is a Node.js runtime built with the Enterprise in mind. 

Similar to Node.js, it works in containerized and cloud environments by default. You can deploy N|Solid with Docker, Kubernetes, Cloud Foundry and others. You can also spin up N|Solid from the AWS, GCP, and Azure Marketplaces as you would with Node.js or any other application-level runtime 😊

**Comment by shawnpreissner** [comment]
Hi @bnb we appreciate your excitement about the Landscape! We already have Nodesource under Monitoring and Node.js under Languages & Frameworks and due to limited real estate, we'll have to leave Node.js in there instead. Thanks for reaching out and a very well composed request.
