### ISSUE TITLE
Tsuru to Platforms

### ISSUE THREAD

**Issue by guilhermebr** [cncf/landscape#102]
Tsuru is an extensible and open source Platform as a Service software.

https://tsuru.io/
https://github.com/tsuru/tsuru

Some media:
http://www.infoworld.com/article/3092824/paas/tsuru-open-source-paas-puts-developers-first.html

https://youtu.be/HkP_tI3D0lE?t=43m16s

http://medium.com/tsurupaas

**Comment by shawnpreissner** [comment]
Hi @guilhermebr thanks for the clearly popular request 🥇  We will include in the upcoming release, can you please provide a hi-res logo for Tsuru? Thanks

**Comment by guilhermebr** [comment]
Hi @shawnpreissner, glad to know!
 
The PNG logo: https://github.com/tsuru/tsuru.io/blob/master/resources/images/icons/tsuru-fb-icon.png

and SVG logo: https://github.com/tsuru/tsuru.io/blob/master/resources/images/brand.svg

Please let me know If these images work. Thanks

**Comment by shawnpreissner** [comment]
@guilhermebr SVG works, thanks

**Comment by shawnpreissner** [comment]
Thanks @guilhermebr, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
