### ISSUE TITLE
HPE Vertica in Data Warehouse?

### ISSUE THREAD

**Issue by dannyk81** [cncf/landscape#103]
https://www.vertica.com/overview/

Seems like it's missing in the list.

**Comment by shawnpreissner** [comment]
Hi @dannyk81 thanks for the request and we will add HPE Vertica to Data Warehouse in the upcoming release.

**Comment by shawnpreissner** [comment]
Thanks @dannyk81, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
