### ISSUE TITLE
Add JHipster to platforms

### ISSUE THREAD

**Issue by deepu105** [cncf/landscape#104]
Add Jhipster as an entry to the platform section
https://jhipster.github.io
We are an OSS framework/platform providing application development and deployment support with multiple cloud support
It also supports API management and creation, deployment and maintanance of cloud native microservices with docker, kubernetes and rancher support

**Comment by shawnpreissner** [comment]
Hi @deepu105 love the site and what you are up to w/JHipster! Will add to Platforms, can you provide a hi-res logo for us to use? Thanks

**Comment by deepu105** [comment]
Here it is https://jhipster.github.io/images/logo/logo-jhipster.svg

**Comment by deepu105** [comment]
other formats https://jhipster.github.io/artwork/

**Comment by shawnpreissner** [comment]
Thanks @deepu105, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version

**Comment by deepu105** [comment]
Thank you
