### ISSUE TITLE
Add Crunchy PostgeSQL to Database

### ISSUE THREAD

**Issue by prlaurence** [cncf/landscape#105]
Not 100% clear whether the landscape is intended to track companies, project or products, but in any event, I would propose the inclusion of Crunchy in the Database category. Admittedly I am biased in my assessment, but Crunchy  has developed a Cloud Native PostgreSQL solution (Crunchy PostgreSQL Container Suite (https://github.com/CrunchyData/crunchy-containers) as well as the first Kubernetes Operator for Postgres (https://github.com/CrunchyData/postgres-operator).  Beyond Kubernetes / Containers, Crunchy is bring Cloud Native PostgreSQL to Cloud Foundry, with Crunchy PostgreSQL for Pivotal Cloud Foundry (https://network.pivotal.io/products/crunchy-postgresql).

**Comment by shawnpreissner** [comment]
Hi @prlaurence the landscape is intended to highlight technologies that are doing really awesome things in making clound native computing ubiquitous! In other words having a focus on containers, microservices, and dynamic orchestration.

Thanks for the request, we'll include Crunchy in the Database category in the upcoming release!

**Comment by prlaurence** [comment]
Great. Thanks @shawnpreissner. I appreciate your including Crunchy. 

Logo attached (or available here: https://github.com/CrunchyData/crunchy-containers). 

![crunchy logo file enterprise postgresql](https://user-images.githubusercontent.com/5797273/28989873-5baf9eda-7946-11e7-9294-17e9786e6dc6.png)

**Comment by dankohn** [comment]
Hi, I'm big fan of Crunchy and the work you're doing to make Postgres easy to deploy. Unfortunately, we're not able to include you in the landscape because of our policy against including commercial versions of open source software (so that we don't have [66](https://docs.google.com/spreadsheets/d/1LxSqBzjOxfGx3cmtZ4EbB_BGCxT_wlxW_xgHVVa23es/edit#gid=0) versions of Kubernetes).

However, please keep up the great work.

**Comment by prlaurence** [comment]
Thanks @dankohn. Crunchy actually provides an open source advanced orchestration layer around PostgreSQL (based on Kubernetes Operator model) that I would suggest provides specific Cloud Native value add around PostgreSQL (https://github.com/CrunchyData/postgres-operator). I certainly understand the challenge, but would suggest Crunchy goes further with its Cloud Native support than simply a commercial version of PostgreSQL.

**Comment by dankohn** [comment]
@prlaurence I agree you're creating a ton of value over just using the Postgres Docker image. If you were interested, I would be open to creating a different diagram that would categorize some of the best and most important Operators and Helm Charts.
