### ISSUE TITLE
CNCF Project count in downloaded CSV vs. Interactive Landscape CNCF Project count

### ISSUE THREAD

**Issue by evectis** [cncf/landscape#1051]
This issues seems to be related to how the Interactive Landscape  is rendered.
CNCF Project count in downloaded CSV is 36.
Interactive Landscape CNCF Project count (when CNCF Relation is equal to CNCF Projects) is 32 (Graduated CNCF Projects = 3, Incubating CNCF Projects = 17 and Cloud Native Sandbox Projects = 12).
Interactive Landscape is missing the 4 following projects in its count:
1. Container Storage Interface (CSI)
2. CRI-O
3. kops
4. Minikube

**Comment by dankohn** [comment]
https://landscape.cncf.io/project=hosted,graduated,incubating,sandbox correctly shows 32 items both on the web and when downloaded as a CSV.

https://landscape.cncf.io/grouping=organization&organization=cloud-native-computing-foundation-cncf correctly shows 36 items, both on the web and as a CSV,

Those 4 projects are hosted by CNCF but not top-level projects.

I don't see a bug.

**Comment by evectis** [comment]
What level are these projects?

**Comment by dankohn** [comment]
CSI is a separate project controlled by Google, which I've now fixed: https://landscape.cncf.io/selected=container-storage-interface-csi

CRI-O, kops, and Minikube are all part of the Kubernetes project.

**Comment by evectis** [comment]
Does it make sense to add a 4th grouping of CNCF Projects that includes CRI-O, kops, and Minikube and is selectable along with graduated, incubating and sandbox in the "CNCF Relation" filter so that all 35 project cards are shown when CNCF Relation = CNCF Projects?

**Comment by dankohn** [comment]
Thanks, but I think those 3 subprojects are enough of a special case that
I'd rather not call them out explicitly.

Note that you can see all 4 categories of CNCF-hosted projects with this
view:
https://landscape.cncf.io/organization=cloud-native-computing-foundation-cncf&project=hosted,graduated,incubating,sandbox,member
--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by evectis** [comment]
That works for me......have a Happy New Year!
