### ISSUE TITLE
Add Scaleway to Public loud

### ISSUE THREAD

**Issue by edouardb** [cncf/landscape#106]
[Scaleway](https://scaleway.com) is a unique IaaS platform, offering on demand BareMetal and Virtual SSD cloud servers. It should be added to the public cloud section. 

The logo: ![here](http://i.imgur.com/LvywuI1.png)

**Comment by shawnpreissner** [comment]
Hi @edouardb thanks for the request. We are splitting Infrastructure into Public Cloud and Bare Metal, of which we'll be happy to add Scaleway to Bare Metal. Look out for in the upcoming release.

**Comment by edouardb** [comment]
Hi @shawnpreissner thanks for your reply, Scaleway should be added into Public Cloud. I've edited the issue title.

**Comment by shawnpreissner** [comment]
Good afternoon @edouardb, we've taken your request into consideration however after evaluation of offerings, we have decided to include Scaleway in Bare Metal. Please find in the most recent version here -> https://github.com/cncf/landscape#cloud-native-landscape-project

**Comment by edouardb** [comment]
Hi @shawnpreissner, Scaleway appears in the private cloud section. It should be listed in the public one. Can you change that?
