### ISSUE TITLE
License = "Other" for these Apache License 2.0 licensed CNCF Projects?

### ISSUE THREAD

**Issue by evectis** [cncf/landscape#1061]
These 3 CNCF Projects show a License = "Other"

1. Harbor
2. The Update Framework (TUF)
3. Cortex

They all seem to adhere to the Apache License 2.0 (although, as allowed by this license, one or more of them may have added a Copyright clause to their version of the Apache License 2.0 language)

**Comment by dankohn** [comment]
Sorry for the long delay in my response. Here are the current non-Apache licensed CNCF-hosted projects:

https://landscape.cncf.io/format=card-mode&grouping=no&license=bsd-2-clause-simplified-license,bsd-3-clause-new-or-revised-license,gnu-affero-general-public-license-v3-0,gnu-general-public-license-v2-0,gnu-general-public-license-v3-0,gnu-lesser-general-public-license-v2-1,gnu-lesser-general-public-license-v3-0,isc-license,mit-license,mozilla-public-license-2-0,other,unknown-license,zlib-license&project=hosted,graduated,incubating,sandbox

Harbor has relicensed. Cortex is Apache-licensed but needs to update their license text. https://github.com/cortexproject/cortex/pull/1531

Brigade re-licensing is underway. And TUF is intentionally licensed as both Apache and MIT.
