### ISSUE TITLE
Some updates -- not addressed yet

### ISSUE THREAD

**Issue by LawrenceHecht** [cncf/landscape#109]
Redspread has been inactive since August 2016.

**Comment by LawrenceHecht** [comment]
Several logos/companies are defunct or purchased. I would check to make sure the following are active: 

ContainerX -- not sure if this product is being kept by Cisco.
Dataloop is now called Outlyer.
Opsee went out of business.
StackEngine was not kept as a brand by Oracle.
Lever OS has been inactive for 10 months.
StackHut is now called NStack (http://nstack.com/).

**Comment by shawnpreissner** [comment]
Hi @LawrenceHecht thank you so much for this list. I looked into and confirm that we'll update Outlyer, NStack, and will be removing the rest. Stay tuned for the upcoming release!

**Comment by LawrenceHecht** [comment]
Shawn, thank you.
