### ISSUE TITLE
Criteria for adding companies

### ISSUE THREAD

**Issue by ad-m** [cncf/landscape#1095]
I carefully reviewed the sections of the Readme covering new entries, corrections, and logos. I see very clear criteria for add new products (300+ GitHub stars etc.). However, I do not see any objective criteria for companies. 

How are the companies qualified to be listed? What conditions must the company meet? I wonder if the companies operating in this area from Poland are suitable to be mentioned (no listed any from Poland), whether they still require development, and if so to what area.

**Comment by dankohn** [comment]
Please read the https://github.com/cncf/toc/blob/master/DEFINITION.md that we link to. We're happy to cover closed source cloud native offerings from Polish companies, though we'd want to have the offering page in English.

If you have a consulting company, we would encourage you to become a KCSP and then get listed: https://www.cncf.io/certification/kcsp/
