### ISSUE TITLE
Add Anchore to Secure Images

### ISSUE THREAD

**Issue by acathrow** [cncf/landscape#11]
The secure images section is missing Anchore which provide a policy based image governance solution. Anchore is available both as an open source project and commercial offering. 

www.anchore.com

![anchore-logo](https://cloud.githubusercontent.com/assets/12734354/20322355/b79fd012-ab46-11e6-9fb1-6c1565625541.png)

**Comment by shawnpreissner** [comment]
Anchore is now included under Secure Images in v0.9.3
