### ISSUE TITLE
Bugsnag should be added to Monitoring

### ISSUE THREAD

**Issue by ErikKriessmann** [cncf/landscape#110]
Also any reason why Pivotal and Turbonomic weren't included? 

Pivotal in particular seems like it should be on here, unless highlighting Cloud Foundry is enough? Seems like that was the thinking with Spark and Kafka as well since Databricks and Confluent aren't on here either.

Would be curious to hear thoughts on listing open source projects vs. companies commercializing them.

**Comment by dankohn** [comment]
Yes, when a company like Pivotal is best known for an open source project like Cloud Foundry, we're including the project/product, not the company. Otherwise, we would have to include dozens or more companies for each of many projects.
