### ISSUE TITLE
BrowserSync alternative for prod

### ISSUE THREAD

**Issue by addikt1** [cncf/landscape#1106]
Question: BrowserSync is included for testing the dist build locally, but I'm trying to run this in a containerized platform and don't want it synchronizing Browser behaviors. I swapped it out for Express, but copy/paste of URls with query params will never work (syncToUrl.js seems to not trigger). What are you guys running for a web server in your hosted environment, and is there some trick to get syncToUrl to work?

**Comment by dankohn** [comment]
We're happy to help but I don't understand the problem you're having.

NPM should install into your container all software necessary for the integration tests, including chromium via puppeteer. We're just using browser-sync to run a simple web server: https://github.com/cncf/landscapeapp/blob/master/tools/ciServer.js

The actual web server to run in production can be any server that serves out the static files in `/dist`. We're using Netlify to build and host the pages, but you could use Apache, NGINX, Caddy, Envoy, or anything else.

**Comment by addikt1** [comment]
Thanks, Dan. After taking a different tac on this, I was able to properly configure Express to work in this single-page-application paradigm.

As for Puppeteer ... thats a whole different challenge re: installing and running chromium in a containerized build environment (probably a different Issue), so any insights there are appreciated.
