### ISSUE TITLE
Add vagrant to Infrastructure Automation

### ISSUE THREAD

**Issue by unklhe** [cncf/landscape#111]
Vagrant is a tool for building and managing virtual machine environments in a single workflow.

Vagrant stands on the shoulders of giants. Machines are provisioned on top of VirtualBox, VMware, AWS, or any other provider. Then, industry-standard provisioning tools such as shell scripts, Chef, or Puppet, can automatically install and configure software on the virtual machine.

https://www.vagrantup.com/intro/index.html

**Comment by hubner** [comment]
I second that

**Comment by rothgar** [comment]
Vagrant doesn't deploy production infrastructure though (that is what terraform is for). Hashicorp tried to make a production deploy tool with otto but that was shut down. I'm not sure including vagrant with these other tools would make as much sense unless you also include things like virtualbox to infrastructure providers.

**Comment by sjeeva** [comment]
I agree with @rothgar, I see vagrant is more of an dev/test tool

**Comment by dankohn** [comment]
I used Vagrant for years and am a big fan of the software. However, I think its role in development is being largely replaced by Docker. If we had a box for dev tools, it would belong there, but I don't think there's a good spot in the current landscape since it is not being used in production.
