### ISSUE TITLE
Fugue should be added to infrastructure automation 

### ISSUE THREAD

**Issue by ErikKriessmann** [cncf/landscape#112]
https://fugue.co/

**Comment by shawnpreissner** [comment]
Hi @ErikKriessmann thanks for the request, without having more information, I'm not seeing enough activity to warrant an add at this moment. Will leave open awaiting your response, for future consideration. Thanks.

**Comment by shawnpreissner** [comment]
Closing in the meantime; feel free to re-issue a ticket using the new template (will prompt while creating a ticket) in order to provide more information.
