### ISSUE TITLE
Download as CSV does not download entire landcapse any longer

### ISSUE THREAD

**Issue by evectis** [cncf/landscape#1124]
Using the "Download as CSV" link used to download the entire landscape (i.e. 638 rows), now when clicking on the "Download as CSV" link the resulting .csv file is truncated on the 47th row for some reason.

**Comment by dankohn** [comment]
Thanks for the bug report! We'll work on this right away.

**Comment by dankohn** [comment]
Moved to other repo.

**Comment by dankohn** [comment]
This is now resolved. @evectis thanks very much for reporting. The bug was improper escaping of `#`.

**Comment by evectis** [comment]
@dankohn , hello again, just did a download of entire landscape, expected 644 rows and only got 586 rows.  Seems there is still some kind of a bug.

**Comment by dankohn** [comment]
Apologies, I confirm this still isn't working. I'll reopen https://github.com/cncf/landscapeapp/issues/179.

**Comment by evectis** [comment]
Working perfectly now...Thanks!

**Comment by dankohn** [comment]
Thank you for the report!
