### ISSUE TITLE
Add Centreon to Monitoring

### ISSUE THREAD

**Issue by julienmathis** [cncf/landscape#113]
Hello, 

I think Centreon can have his place in the monitoring tool list.

https://www.centreon.com

Logo is available here : https://static.centreon.com/wp-content/themes/centreon/assets/images/centreon-ces-title.svg

Thanks

**Comment by shawnpreissner** [comment]
Hi @julienmathis thanks for the request and we'd be happy to include Centreon in the upcoming release. Can you please provide a new logo path, that one isn't working for me?

**Comment by shawnpreissner** [comment]
Thanks @julienmathis, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
