### ISSUE TITLE
harbor is an enterprise-class container registry server based on Docker Distribution

### ISSUE THREAD

**Issue by pescerosso** [cncf/landscape#114]
Can you please add Harbor? Harbor is an enterprise-class container registry server based on Docker Distribution. Harbor extends the open source Docker Distribution by adding the functionalities usually required by an enterprise, such as security, identity and management.

https://github.com/vmware/harbor

**Comment by shawnpreissner** [comment]
Hi @pescerosso thanks for the request and we do like Harbor! Unfortunately, we have larger VMWare technologies already represented elsewheres and are facing limited real estate. Thanks again but closing for now.

**Comment by shawnpreissner** [comment]
I'm sorry @pescerosso after further review, Harbor is definitely unique and will be included in Registry Services in the upcoming release. Thanks.

**Comment by shawnpreissner** [comment]
Thanks @pescerosso, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
