### ISSUE TITLE
In addition to Application Definition could we include Apache Brooklyn in Service Management

### ISSUE THREAD

**Issue by duncanjw** [cncf/landscape#115]
This reflects Apache Brooklyn's duality -

Design time -> Modelling -> Application Definition
Runtime -> Deployment & Management -> Service Management

We trust this is not controversial

**Comment by shawnpreissner** [comment]
Hi @duncanjw, we're limited each technology to one category. Comparing real estate, between the two, I'll assume you'll want to stay in Application Definition...let me know if you feel better suited in Service Management though. Thanks.
