### ISSUE TITLE
Wrong logo for NetApp

### ISSUE THREAD

**Issue by bgwolfe78** [cncf/landscape#116]
I don't know why there is a SolidFire logo for NetApp, they are just one of our products.  Can we please replace it with the attached logo?

![na_logo_vrt_2c_rgb_lrg](https://cloud.githubusercontent.com/assets/20129778/25963728/5b4165e8-3650-11e7-9988-a34865b2a4f3.png)

**Comment by shawnpreissner** [comment]
Yes @bgwolfe78 , will gladly make the change. Please stay tuned for the updated release soon!

**Comment by shawnpreissner** [comment]
Thanks @bgwolfe78, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
