### ISSUE TITLE
Github Enterprise

### ISSUE THREAD

**Issue by addikt1** [cncf/landscape#1169]
Sorry for the trivial question, but I'm trying to reference internal GitHub Enterprise repos for some items and the build keeps returning 404 in getReleaseDates when I can successfully hit the URLs in a browser. If I need to be using some sort of GitHub auth token, where do I put/use/export this?

**Comment by dankohn** [comment]
`export GITHUB_KEY=your-key-here` in your `.bash_profile`. Please feel free to share details about your use case if you're able.

**Comment by addikt1** [comment]
hmm, i have done that, but I still get a 404 when running `yarn fetch` and attempting to access a URL like https://github.mydomain.com/myorg/myrepo/releases in getReleaseDates. I've modified the code to go against the internal URL vs github.com exclusively. The repo is public, too, which deepens my confusion.

**Comment by dankohn** [comment]
We only support GitHub URLs of the form github.com/org/repo. Adding in
/releases is confusing it.
--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by addikt1** [comment]
I was just referring to the URL created from the getReleaseDate function in https://github.com/cncf/landscapeapp/blob/master/tools/githubDates.js

**Comment by ZeusTheTrueGod** [comment]
Hi, @addikt1 , as an author of githubDates.js, I can explain how we got this to work.
We are relying on a scraping tool to find the latest page with commits, and on that latest page we look for the date of a first commit. To make it faster, I use a binary search with a maximum page number about 250000. It is absolutely possible that gitlab has a bit different user interface.
Regarding a release date, it is not that complex as getting the first commit date, but still relies on a the DOM implementation.

**Comment by addikt1** [comment]
I'll keep working on it
