### ISSUE TITLE
Dimension Data missing in Infrastructure section

### ISSUE THREAD

**Issue by cyberatz** [cncf/landscape#117]
Dimension Data is likely one of the largest players in the enterprise cloud market with significant geographic spread in the public cloud space. Their APIs are the same for both on premise cloud and public cloud infrastructure.

**Comment by hubner** [comment]
I don't believe Dimension Data, be it as a cloud provider, multicloud broker or integrator should be included in the Infra section. If so, then we must do the same for **all** companies _(providers, integrators or software builders, doesn't matter)_ that somehow are just like Dimension Data (and I can list at least a hundred of those).

**Comment by dankohn** [comment]
Hi, unfortunately, we don't have a box that is a good fit for Dimension Data at this time.
