### ISSUE TITLE
Make logos clickable

### ISSUE THREAD

**Issue by BarisEris** [cncf/landscape#119]
One of the key uses of this great one-pager would be to easily navigate to respective web sites. I think it'd be feasible to include hyperlinks to respective landing pages for the benefit of the community.

**Comment by shawnpreissner** [comment]
Hi @BarisEris stay tuned as we're working on producing an interactive (web app) version of the landscape with much more org detail, features, and of course links!

**Comment by evectis** [comment]
@shawnpreissner, Hello, any updates on that  interactive (web app) version of the landscape?

**Comment by dankohn** [comment]
We’re hoping to release it in the next month. 

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation  https://www.cncf.io
+1-415-233-1000  https://www.dankohn.com

**Comment by evectis** [comment]
Looking at V 1.0, is it now interactive?

**Comment by dankohn** [comment]
Nope, we're hoping to add the interactive version early next year. We'll announce it when we do.

**Comment by evectis** [comment]
Dan....hello again, is there anything I can do to assist in identifying options for making the Landscape interactive?

**Comment by dankohn** [comment]
Look for an announcement Wednesday March 7.

**Comment by dankohn** [comment]
Finally implemented: https://landscape.cncf.io/
