### ISSUE TITLE
Updating the Cloud Native Landscape

### ISSUE THREAD

**Issue by iguazioDani** [cncf/landscape#120]
Please add iguazio to the "database" and "streaming" sections under application definition and development. Thanks!

**Comment by shawnpreissner** [comment]
Hi @iguazioDani, which one of the two categories would you prefer iguazio residing in?

**Comment by iguazioDani** [comment]
@shawnpreissner Yes, thanks.

**Comment by shawnpreissner** [comment]
Great, @iguazioDani we'll be including in streaming in the new release, coming out shortly!

**Comment by iguazioDani** [comment]
Great, we look forward to seeing it.

**Comment by iguazioDani** [comment]
Hey Shawn, on second thought we prefer Database over Streaming - please move our logo for the next version. Thank you!

**Comment by shawnpreissner** [comment]
Hey @iguazioDani, you've got it. Stay tuned for 0.9.8...

**Comment by shawnpreissner** [comment]
@iguazioDani closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
