### ISSUE TITLE
Add OpenAPI Initiative in the API management section/area

### ISSUE THREAD

**Issue by hubner** [cncf/landscape#121]
OpenAPI, an open governance structure under the Linux Foundation, is an consortium/specification that is followed/endorsed by multiple tier1 software companies. I think it should be added under the API management section/area.

[https://www.openapis.org](https://www.openapis.org)

**Comment by shawnpreissner** [comment]
Thanks @hubner, closing as this update was included under the newly titled Application Definition category, in the most recent version https://github.com/cncf/landscape#current-version
