### ISSUE TITLE
Add Microsoft Operations Management Suite Container Monitoring Solution

### ISSUE THREAD

**Issue by keikhara** [cncf/landscape#123]
https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-containers 

Please add OMS Container Monitoring Solution to the Monitoring section. 

- https://github.com/Microsoft/OMS-Agent-for-Linux (github) 

- https://hub.docker.com/r/microsoft/oms/ (dockerhub)

OMS Container Monitoring Solution provides the following: 
- Centralize and correlate millions of logs from Docker containers at scale
- See real-time information about Container status, image, and affinity
- Quickly diagnose “noisy neighbor” containers that can cause problems on Container hosts
- Retrieve, visualize, and monitor CPU, memory, storage, and network usage with performance metrics
- View detailed and secure audit trail of all Docker actions on Container hosts

We support any OS ( linux or windows), multiple orchestrator (k8s, dc/os, docker swarm, redhat openshift), on any platform (Azure, onprem, other hosting)

If you have any question, please let me know. 

thank you,

Keiko

**Comment by caniszczyk** [comment]
cc: @shawnpreissner can you take a look at this

**Comment by shawnpreissner** [comment]
Hi @keikhara thanks for the request and we have included Microsoft OMS in our new version, releasing soon!
cc: @caniszczyk

**Comment by keikhara** [comment]
@shawnpreissner 

Can change the name quickly since we did a name change on the product. 
Instead of Microsoft Operating Management Suite. It will be "Azure Log Analytics". 
Sorry for the last minute change. 

thanks,

**Comment by keikhara** [comment]
![10090af5](https://user-images.githubusercontent.com/19479703/29379674-182fd310-8278-11e7-9111-3535a683fcfa.PNG)

Icon attached

**Comment by shawnpreissner** [comment]
@keikhara I wondered because while looking for the logo I was confused by seeing Azure Log Analytics everywhere! I found the same logo but white backdrop which is required for the landscape - will this work? https://azure.microsoft.com/svghandler/log-analytics/?width=600&height=315

**Comment by keikhara** [comment]
@shawnpreissner  white backdrop will works. thanks!

**Comment by shawnpreissner** [comment]
Thanks @keikhara, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
