### ISSUE TITLE
Add Istio in "Service Management"

### ISSUE THREAD

**Issue by zorel** [cncf/landscape#124]
https://github.com/istio/istio

"Istio is an open platform for providing a uniform way to integrate microservices, manage traffic flow across microservices, enforce policies and aggregate telemetry data. Istio's control plane provides an abstraction layer over the underlying cluster management platform, such as Kubernetes, Mesos, etc."

**Comment by shawnpreissner** [comment]
Hi @zorel we are including Istio in the upcoming version, releasing soon! Thanks

**Comment by dosire** [comment]
Istio was included, this issue can be closed.
