### ISSUE TITLE
Add Apache CarbonData in DataWarehouse section

### ISSUE THREAD

**Issue by chenliang613** [cncf/landscape#129]
Apache CarbonData is an indexed columnar data storage for fast analytics.
Please consider adding Apache CarbonData to data warehouse section. 

You can find the detail from Apache CarbonData website : carbondata.apache.org

Thanks
Liang

**Comment by shawnpreissner** [comment]
Hi @chenliang613 it was nice meeting you in Beijing. We'll add CarbonData to our next release, please stay tuned ~end of July.

**Comment by chenliang613** [comment]
@shawnpreissner  Thanks, very happy to meet you in beijing.

**Comment by shawnpreissner** [comment]
Thanks @chenliang613, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
