### ISSUE TITLE
Add Concourse to CI/CD

### ISSUE THREAD

**Issue by trosenkranz** [cncf/landscape#130]
I belive, that Concourse is missing.

https://concourse.ci/

greetings

**Comment by shawnpreissner** [comment]
Hi @trosenkranz thanks for the request and we'll be including Concourse in the new release, coming soon!

**Comment by trosenkranz** [comment]
Great. Thanks.

**Comment by shawnpreissner** [comment]
Thanks @trosenkranz, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
