### ISSUE TITLE
Rancher OS

### ISSUE THREAD

**Issue by m4b0** [cncf/landscape#133]
Hello,

Into the section "Runtime / OS", it appears "Rancher" logo. I think it will be better to show the "Rancher OS" logo because "Ranches OS" is the Operating System and not Rancher (which is a container management platform).

Racher OS image availabe at http://cdn.rancher.com/wp-content/uploads/2016/07/25205112/rancheros-logo-01.png

Regards,
Marco Bravo

**Comment by shawnpreissner** [comment]
Hi @m4b0 good observation and we do aim to present the specific projects, however for the new version (releasing soon) we are restructuring some categories. This impacted OS, and we're therefore keeping Rancher in PaaS. Thanks again for reporting this!
