### ISSUE TITLE
installer vs distribution

### ISSUE THREAD

**Issue by soheilade** [cncf/landscape#1369]
in the cncf landscape there are 2 sections for k8s **distributions** and k8s **installers**. Does an installer include a distribution as well? Can an installer have multiple distributions?

**Comment by dankohn** [comment]
Please see the definitions here: https://github.com/cncf/k8s-conformance/blob/master/faq.md#what-is-a-distribution-hosted-platform-and-an-installer

The vendor has some discretion is deciding whether to call their Certified Kubernetes implementation a distribution or an installer.
