### ISSUE TITLE
Add OpenFaaS to -> event-based compute

### ISSUE THREAD

**Issue by alexellis** [cncf/landscape#137]
I’d like to suggest OpenFaaS for the project landscape in the event-based compute section. https://github.com/openfaas

[OpenFaaS](https://github.com/alexellis/faas) is a framework for building Serverless functions for Docker and Kubernetes. It has over 3k GitHub stars and was the top trending Golang project for several days in August.

As the author I’m planning to give an overview to the Serverless WG at the next meeting - Aug 24th 2017.

> Update: [blog and recording here](https://blog.alexellis.io/openfaas-cncf-workgroup/)

Logo: Logos with side text or stacked is available in SVG/EPS format or other on request.

[logos.zip](https://github.com/cncf/landscape/files/1232103/logos.zip)

**Comment by alexellis** [comment]
URL updated to https://github.com/openfaas

**Comment by dankohn** [comment]
Thanks, Alex. It will be in the next version.

**Comment by alexellis** [comment]
Great. Do you have a timeline?

**Comment by dankohn** [comment]
Next couple weeks, hopefully.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by shawnpreissner** [comment]
Hi @alexellis, closing as this update was included in the most recent version. https://github.com/cncf/landscape#current-version

**Comment by alexellis** [comment]
Shawn thank you - looks great. 👍
