### ISSUE TITLE
Suggestion: npm

### ISSUE THREAD

**Issue by seldo** [cncf/landscape#138]
We are arguably present in a lot of these boxes but as the world's largest software registry we should certainly be at least in the "registry" section.

Our logos are available in this repo: https://github.com/npm/logos probably this is the best one to use: 

https://github.com/npm/logos/blob/master/%22npm%22%20lockup/npm.png

**Comment by dankohn** [comment]
npm is an amazing project, and it's used by tons of cloud native applications. However, we specifically cut out languages and frameworks from our last [version](https://raw.githubusercontent.com/cncf/landscape/master/landscape/CloudNativeLandscape_v0.9.5_cncf.jpg) to focus more on the infrastructure for deploying containers.

However, I agree that `Registry Services` is unclear what it covers, so we'll change it to `Container Registries` for the next version.

@shawnpreissner
