### ISSUE TITLE
Add ScyllaDB to the database bucket

### ISSUE THREAD

**Issue by dorlaor** [cncf/landscape#139]
Scylla is a Cassandra reimplementation in C++ at 10X the speed. We do have lots of github stars and good traction: https://github.com/scylladb/scylla 

Thanks, Dor

**Comment by shawnpreissner** [comment]
Hi @dorlaor, we are including Scylla in the upcoming version, releasing soon! Thanks
http://www.scylladb.com/wp-content/uploads/logo-scylla.svg

**Comment by dorlaor** [comment]
Super, thanks!

**Comment by shawnpreissner** [comment]
Thanks @dorlaor, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version

**Comment by dorlaor** [comment]
Awesome, just tweeted it around
