### ISSUE TITLE
Avi Networks not listed for service discovery and proxy functions

### ISSUE THREAD

**Issue by guruchahal** [cncf/landscape#14]
Avi Networks provides the following for Mesos, Kubernetes, Swarm and Rancher based environments:
- Service discovery
- Service proxy
- Service security (micro-segmentation, encryption etc, white/black lists)
- Service performance monitoring (and auto-discovery of application maps based on conversation). 

The software in in production with several customers today. Could you please include the Avi logo in the cloud native landscape under "Service Management", "Coordination and Service Discovery", and "Observability and Analysis"? 

Thanks!

**Comment by dankohn** [comment]
You need to pick the one place where you best fit. I appreciate that this
is challenging and arbitrary, but we've made that decision to avoid logo
overload.

**Comment by guruchahal** [comment]
Dan - A fair request, certainly as a start. Please list Avi under "Service Management". Thanks!

**Comment by shawnpreissner** [comment]
Avi Networks is now included under Service Management in v0.9.3
