### ISSUE TITLE
Azure Functions is open source

### ISSUE THREAD

**Issue by davidobrien1985** [cncf/landscape#140]
Hi,

great collection of tools!
However, Azure Functions in the "Serverless" space is indeed open source.

https://github.com/Azure/azure-webjobs-sdk-script

This should be fixed.

Cheers
David

**Comment by dankohn** [comment]
Thanks for the comment. The SDK is open source, but I don't think the underlying functions are. I can't take Azure Functions and create a serverless setup on my own bare metal, can I?

**Comment by davidobrien1985** [comment]
Yes, you can.
I think the repo just has a strange name.

Sent from my iPhone

On 18 Aug 2017, at 12:44 pm, Dan Kohn <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the comment. The SDK is open source, but I don't think the underlying functions are. I can't take Azure Functions and create a serverless setup on my own bare metal, can I?

**Comment by dankohn** [comment]
@gabrtv @michelleN Could I please get official confirmation?

**Comment by kris-nova** [comment]
@dankohn -

Yes @davidobrien1985 is correct, this is open source and can be ran on any environment (including baremetal)

**Comment by dankohn** [comment]
Cool, we'll fix it for the next version.

**Comment by shawnpreissner** [comment]
Thanks @davidobrien1985 @kris-nova, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
