### ISSUE TITLE
Please add OpenEBS to storage

### ISSUE THREAD

**Issue by kmova** [cncf/landscape#141]
https://github.com/openebs

**Comment by kmova** [comment]
Project or Product name: OpenEBS

Is it open source?: Yes

What are the best URL(s) for it?: 
https://github.com/openebs/openebs
www.openebs.io


What category does it belong in? Container Native Storage

What's the URL for the best logo (and it needs to include the name)? 
https://github.com/openebs/chitrakala/blob/master/logo/png/logo-01.png

Anything else we need to know?: Nope, thank you!

**Comment by shawnpreissner** [comment]
Hi @kmova thanks for the request, we'll be including OpenEBS in our upcoming version.

**Comment by kmova** [comment]
thank you @shawnpreissner

**Comment by shawnpreissner** [comment]
Thanks @kmova, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
