### ISSUE TITLE
Add CloudScreener to Analysis

### ISSUE THREAD

**Issue by MathieuMailhos** [cncf/landscape#142]
Hi, I would be great to add CloudScreener to Observability/Analysis.

[Cloud Decision Engine](https://search.cloudscreener.com) is a free tool that gives entire infrastructure comparison and recommendation based on criteria such as price, performance, location... between major IaaS providers.

The main purpose is to demystify the complexity of offers and help the user to find the right place to build his Cloud Native app based on his particular needs.

[logo attached](https://user-images.githubusercontent.com/5645869/29452001-0fc3ffa6-8405-11e7-8353-08307cc78a35.png)

**Comment by dankohn** [comment]
Thanks. Sounds like a cool product, but it's not a fit for the Service Management category, or unfortunately for the landscape at this time. We're referring to managing application services.

**Comment by MathieuMailhos** [comment]
Thanks for your answer. Looking forward for the next "Managing Application" category to open then!

**Comment by dankohn** [comment]
When we add it, you'll be there.
