### ISSUE TITLE
Add Scalingo to PaaS

### ISSUE THREAD

**Issue by yannski** [cncf/landscape#143]
[Scalingo](https://scalingo.com/) is a polyglot PaaS (and a DBaaS) located in France/Europe based on Docker and buildpacks. It should be added to the PaaS section.

The logo: 
![Scalingo Logo](https://scalingo.com/logo.svg)

**Comment by shawnpreissner** [comment]
Hi @yannski, we'll include Scalingo in the upcoming version, releasing soon.

**Comment by yannski** [comment]
Thanks a lot @shawnpreissner

**Comment by shawnpreissner** [comment]
Thanks @yannski, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version

**Comment by yannski** [comment]
:+1:
