### ISSUE TITLE
runV logo for runtime in landscape

### ISSUE THREAD

**Issue by resouer** [cncf/landscape#144]
cc @dankohn Seems we are late 😢 

Fixes: https://github.com/hyperhq/runv/issues/542

![image](https://user-images.githubusercontent.com/1701782/29455671-ab0078ca-8444-11e7-8a7c-f3b41fa1954d.png)

**Comment by resouer** [comment]
Also, hyper.sh need a new logo, I will attach it here soon!

**Comment by dankohn** [comment]
Looks great, we'll get you in the next version.

**Comment by resouer** [comment]
The latest hyper.sh logo: ![logo_dark](https://user-images.githubusercontent.com/1701782/29462984-a8451220-8463-11e7-84a0-739418f027f1.png)

**Comment by shawnpreissner** [comment]
Thanks @resouer, we're adding runV and updating the hyper.sh logo in our upcoming 0.9.8 release.

**Comment by shawnpreissner** [comment]
Thanks @resouer, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
