### ISSUE TITLE
Weave Net logo update

### ISSUE THREAD

**Issue by pidster** [cncf/landscape#145]
Please can the logo used for Weave Net be updated to this one?

[edited] See below for .ai in zip.

**Comment by pidster** [comment]
I can provide an Illustrator .ai file instead or as well, if that is preferable.

**Comment by dankohn** [comment]
Is it possible to get a Weavenet logo that is different from Weaveworks? That will be a showstopper if (as I hope) Weavenet becomes a CNCF project.

Cc @monadic

**Comment by pidster** [comment]
The logo that was used in the landscape is old & was only used for a short period, so we'd prefer it changed to the corporate one if that's the only Weaveworks thing in the landscape.

Completely understand (& agree) that the corporate one can't be used if it becomes a CNCF project - we'd be happy to contribute a neutral logo if/when that happens.

**Comment by dankohn** [comment]
OK.

--
Dan Kohn <mailto:dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation <https://cncf.io/>
tel:+1-415-233-1000

**Comment by shawnpreissner** [comment]
Hi @pidster, we currently have that corporate one used in the Monitoring (for Weave Scope). We also currently have Weave Flux in Service Management, and you found Weave Net. Please let me know your preference within the next two days and we can update for the upcoming version. 

We'd also be happy to contribute a possible logo (either through our LF designers or by kicking off a 99designs campaign) for the prospective project, working with your team and direction throughout the process. Let me know if you'd like to take us up on that offer.
cc: @monadic

**Comment by pidster** [comment]
Please update Net logo to this (for now, until the other submission happens).

[weave-sq-logos-net.ai.zip](https://github.com/cncf/landscape/files/1369329/weave-sq-logos-net.ai.zip)

**Comment by shawnpreissner** [comment]
@pidster we try to avoid having many products/projects from the same company to begin with, having the same logo only difference being "net" vs "cloud" (#146) underneath makes it very glaring.

**Comment by pidster** [comment]
@shawnpreissner I read the guidelines as meaning one-per-box was OK. (Net will change again soon, but we haven't been able to address that yet).

We thought, as Netflix also has multiple projects under one brand, we'd copy how their logos are presented.

Our normal logos place the product word to the right of the 'weave' prefix, but this makes it too small to read. Getting sign off for these square variants was quite a task, I don't know how else I can solve this & keep everyone happy.

**Comment by shawnpreissner** [comment]
Thanks @pidster, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
