### ISSUE TITLE
Weave Cloud logo update in "Observability & Analysis"

### ISSUE THREAD

**Issue by pidster** [cncf/landscape#146]
Please can Weave Cloud be added to the "Observability & Analysis" section, using the attached logo?

[edited] see last comment for file.

**Comment by pidster** [comment]
I can provide an Illustrator .ai file instead or as well, if that is preferable.

**Comment by dankohn** [comment]
We can replace the Weaveworks logo with the Weavecloud one above (no ai
necessary). Please confirm that's what you want.

--
Dan Kohn <mailto:dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation <https://cncf.io/>
tel:+1-415-233-1000

**Comment by shawnpreissner** [comment]
#145

**Comment by pidster** [comment]
OK... decisions made at our end. Please update to this:

[weave-sq-logos-cloud.ai.zip](https://github.com/cncf/landscape/files/1369327/weave-sq-logos-cloud.ai.zip)

**Comment by shawnpreissner** [comment]
Ok @pidster, no problem, updating Weaveworks logo to that most recent Weavecloud logo.

**Comment by shawnpreissner** [comment]
Closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
