### ISSUE TITLE
Add Portainer.io into Orchestration & Management

### ISSUE THREAD

**Issue by deviantony** [cncf/landscape#147]
https://github.com/portainer/portainer
https://portainer.io

"Portainer is a lightweight management UI which allows you to easily manage your different Docker environments (Docker hosts or Swarm clusters)."

Tho I'm not sure it would fit into the Service management section.

**Comment by shawnpreissner** [comment]
Hi @deviantony, we are including Portainer in Platforms in the upcoming version, releasing soon! Thanks

**Comment by shawnpreissner** [comment]
Thanks @deviantony, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
