### ISSUE TITLE
Add kubicorn to infra automation

### ISSUE THREAD

**Issue by kris-nova** [cncf/landscape#148]
Would the CNCF be interested in adding [kubicorn](https://github.com/kris-nova/kubicorn) to the landscape diagram as an infrastructure automation solution? We have a logo on our `README.md` but can provide something a little more subtle if needed.

Cheers

**Comment by shawnpreissner** [comment]
Thanks @kris-nova, love the logo, and this will be included in the upcoming 0.9.8 version!

**Comment by kris-nova** [comment]
Yay awesome thank you!

**Comment by shawnpreissner** [comment]
Hi @kris-nova, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
