### ISSUE TITLE
Dead link in INSTALL.md + missing script for local development

### ISSUE THREAD

**Issue by SS-TT** [cncf/landscape#1485]
Hi there.

`INSTALL.md` file has a link to [this script](https://github.com/cncf/landscapeapp/blob/master/update_server/setup.template), which gives 404 error.

Also, on local development instructions you have

* `npm run open:src` (starts a development server) or
* `npm run build`, then `npm run open:dist` (compiles and opens a production build)

but, besides `npm run build`, other commands are not working.

Here's an output example for `npm run open:src --verbose`:

> npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'open:src', '--verbose' ]
npm info using npm@6.7.0
npm info using node@v11.15.0
npm verb stack Error: missing script: open:src
npm verb stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:155:19)
npm verb stack     at /usr/lib/node_modules/npm/lib/run-script.js:63:5
npm verb stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
npm verb stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
npm verb stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45)
npm verb stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)
npm verb stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
npm verb stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:364:12
npm verb stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:90:16
npm verb stack     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
npm verb cwd /mnt/c/Users/myUser/Desktop/landscape/landscape
npm verb Linux 4.4.0-18362-Microsoft
npm verb argv "/usr/bin/node" "/usr/bin/npm" "run" "open:src" "--verbose"
npm verb node v11.15.0
npm verb npm  v6.7.0
**npm ERR! missing script: open:src**
npm verb exit [ 1, true ]
npm timing npm Completed in 460ms
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/myUser/.npm/_logs/2019-11-28T13_35_39_967Z-debug.log

As you can see on the bold line, seems like the scripts on INSTALL.md are missing.

**Comment by dankohn** [comment]
Thanks for the bug report. You found some out-of-date instructions. Could you please try the updated ones I link to with https://github.com/cncf/landscape/commit/3dc63bca7530023a5e9ff198f06cc1618914002e and open a new issue if you still have build errors.
