### ISSUE TITLE
Please Add Azure Service Fabric from Microsoft

### ISSUE THREAD

**Issue by masnider** [cncf/landscape#149]
Hello!

Wanted to see if we could add Service Fabric to the landscape. The clearest home would be Orchestration & Management / Scheduling and Orchestration. 

If it's possible to be included in other areas as well please let me know. Arguably Service Fabric participates in the following as well:

- Coordination and Service Discovery
- Service Management
- Platforms / PaaS Container Service
- App Definition & Development / Application Definition 
- Runtime / Cloud-Native Storage

Happy to have a longer conversation about any of these and provide evidence and any docs or other information required. 

Thanks
-Matt

@MikkelHegn fyi

**Comment by masnider** [comment]
I suppose pointing to the basic landing pages would also help kick things off :)

Basic marketing landing page --> https://azure.microsoft.com/en-us/services/service-fabric/
Docs home -> https://docs.microsoft.com/en-us/azure/service-fabric/

**Comment by dankohn** [comment]
@masnider Could you please answer these questions for us (we created the issue template after you opened the issue):

**Please only report on one project or product per issue**

Guidelines for getting added to the CNCF Cloud Native Landscape:

* We generally will only list a company in one box, to represent its major or best known offering. We occasionally make exceptions for large companies.
* Projects with at least 250 GitHub stars that clearly fit in an existing category are generally included.
* We are unlikely to create a new category for products/projects as we'd rather find the best home with the current options.
* We are generally not including commercial versions of open source software, when that version just includes minor tweaks.
* Closed source products need to link to a clear description of your product; no stealth mode companies.
* Your project or company needs a logo.

**Project or Product name**:

**Is it open source?**:

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source.**:

**What category does it belong in?**

**What's the URL for the best logo (and it needs to include the name)?**

**Anything else we need to know?**:

**Comment by masnider** [comment]
Hi @dankohn - thanks. Glad I didn't just skip the template originally. Answers below:

**Project or Product name:** Microsoft Azure Service Fabric

**Is it open source?:** Partially. The programming models and some tools are currently open source, and the plan is for more of the product to become open source, however we have not publicly disclosed a timeline for that at this time. 

**What are the best URL(s) for it?:** 
https://azure.microsoft.com/en-us/services/service-fabric/
https://github.com/Azure/service-fabric

**What category does it belong in?:** Orchestration & Management / Scheduling and Orchestration
Service Fabric also has capabilities that fall into the following categories:

- Coordination and Service Discovery
- Service Management
- Platforms / PaaS Container Service
- App Definition & Development / Application Definition
- Runtime / Cloud-Native Storage

I don't know if it's possible to be included in multiple categories. If that's the case can we have a quick discussion about how to represent that Service Fabric is a large platform?

**What's the URL for the best logo?:**
https://raw.githubusercontent.com/Azure/service-fabric/master/service-fabric.png 

**Anything else we need to know?:** Service Fabric is widely deployed inside of Microsoft, running directly on about (as of this writing) one-third of all Azure cores. Service Fabric is the platform behind many services from Microsoft, including SQL Azure, Cosmos DB, EventHubs, IotHubs, Cortana, Intune, PowerBI, Dynamics 365, the core Azure Resource Providers, and more. Service Fabric currently supports Windows and has a public preview for Linux. Service Fabric provides a development platform for writing services should developers wish, with capabilities for lifecycle management and stateful computation. Service Fabric orchestrates and manages bare processes, containers, and services written against Service Fabric's service APIs. 

Thanks and let us know if you need any more information. 
-Matt

**Comment by dankohn** [comment]
Great, thanks. We are very likely to put it in Service Management.

**Comment by dankohn** [comment]
@masnider Could you please email me: dan at linuxfoundation.org

**Comment by dankohn** [comment]
Confirming this will go as a closed source product in Orchestration. Thanks.

**Comment by shawnpreissner** [comment]
Thanks for all the detail @masnider and @dankohn ... this will be included in the upcoming 0.9.8 version!

**Comment by shawnpreissner** [comment]
Hi @masnider, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version

**Comment by masnider** [comment]
@dankohn @shawnpreissner Thanks! This is great.
