### ISSUE TITLE
add OpenStack Swift under cloud-native storage

### ISSUE THREAD

**Issue by notmyname** [cncf/landscape#150]
Despite OpenStack already being mentioned under "Bare Metal Provisioning", Swift should be added under "Cloud-Native Storage".

Swift does not provide bare metal provisioning, and it is closely associated with the other projects listed under cloud native storage. It is commonly deployed (and fully supported) independently of other OpenStack projects.

Swift's project logo is at https://www.openstack.org/themes/openstack/images/project-mascots/Swift/OpenStack_Project_Swift_vertical.png

Swift's GitHub mirror is at https://github.com/openstack/swift

**Comment by shawnpreissner** [comment]
Hi @notmyname, we will include OpenStack Swift in the upcoming version, releasing soon! If you can reply back today with an updated logo path (one provided is not working), we'll include that otherwise we'll place "Swift" text underneath the OpenStack logo. Thanks

**Comment by notmyname** [comment]
I'm happy to hear it, and I'm sorry the other link isn't working for you. I've re-uploaded it to http://d.not.mn/OpenStack_Project_Swift_vertical.png. Does that link work for you?

**Comment by shawnpreissner** [comment]
Thanks for the quick response @notmyname I've updated the logo per your link.

**Comment by shawnpreissner** [comment]
Hi @notmyname, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
