### ISSUE TITLE
Wrong logo for one of the Apex entries

### ISSUE THREAD

**Issue by LawrenceHecht** [cncf/landscape#151]
Under Serverless/Event-based, the Apex logo should come from http://apex.run. This is totally different than the Apex in the Streaming section

**Comment by dankohn** [comment]
Thanks for catching that.

**Comment by shawnpreissner** [comment]
This will be updated in our upcoming version, thanks again @LawrenceHecht!

**Comment by shawnpreissner** [comment]
Hi @LawrenceHecht, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
