### ISSUE TITLE
Include Platform.sh

### ISSUE THREAD

**Issue by Crell** [cncf/landscape#152]
https://platform.sh/ is a fully integrated Container-based 2nd Gen PaaS.  We have our own LXC-based orchestration software and container format, offering rapid cloning of environments including data (copy-on-write for speed), and repeatable build-from-git functionality for many languages and services.

Please add us!  I think we'd go in the Platforms / PaaS section.

Let me know if I can clarify anything about Platform.sh for you.

**Comment by shawnpreissner** [comment]
Hi @Crell, we'll Platform.sh in the upcoming version, releasing soon! Thanks

**Comment by shawnpreissner** [comment]
Thanks @Crell, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
