### ISSUE TITLE
Include Black Duck, StackRox, and OpenSCAP

### ISSUE THREAD

**Issue by charlesrichard** [cncf/landscape#153]
Include Black Duck, StackRox, and OpenSCAP under CI/CD Security.

**Comment by charlesrichard** [comment]
Information on Black Duck Software can be found here-> https://www.blackducksoftware.com/
StackRox here-> https://www.stackrox.com/
OpenSCAP here-> https://www.open-scap.org/

**Comment by shawnpreissner** [comment]
Hi @charlesrichard, Black Duck and OpenSCAP will be included under Secure Images (formerly named CI/CD Security), and we have another request from the StackRox team to include them under Monitoring - so please look for them there in the upcoming version. Thanks

**Comment by shawnpreissner** [comment]
Thanks @charlesrichard, closing as these updates were included in the most recent version https://github.com/cncf/landscape#current-version
