### ISSUE TITLE
Add chaosmesh to the Chaos Enginnering tools

### ISSUE THREAD

**Issue by MrBW** [cncf/landscape#1531]
Hi CNCF team,

congrats for your awesome landscape project. Well done!
We are a young start-up from Europe (Germany) and are founded in October 2019. We develop and operate a Chaos Engineering Platform, which we offer as SaaS or On-Prem solution.

We would be very happy if we can become part of your landscape.

Our website can be found at [chaosmesh.com](https://www.chaosmesh.com/) and our logo is attached to this issue.

Twitter: [@chaosmesh](https://twitter.com/chaosmesh)
GitHub: [chaosmesh GitHub](https://github.com/chaosmesh)
LinkedIn: [LinkedIn chaosmesh](https://www.linkedin.com/company/chaosmesh)
Headcount: 3
Founded: October, 2019 (Europe/Germany)

Many thanks,
Benjamin

![chaosmesh-logo](https://user-images.githubusercontent.com/6093565/73154833-f7a32800-40d8-11ea-9a45-57b8ee351479.png)

**Comment by dankohn** [comment]
Please follow the directions on https://github.com/cncf/landscape#new-entries to add yourself.

Note that PingCAP's open source project https://landscape.cncf.io/selected=chaos-mesh with 1300 stars has the same name, so you should consider whether you want to enter the market with an identical name.

For GitHub, you need a repo, not an org.

Feel free to ask if you have trouble setting up your entry.

**Comment by MrBW** [comment]
Thank you for the description and the hint.

We are in contact with PingCAP, because they decided to rename their project about 20 days ago and did not check if there was already a company with this name.
