### ISSUE TITLE
Include ManageIQ under Infrastructure Automation

### ISSUE THREAD

**Issue by charlesrichard** [cncf/landscape#154]
Include ManageIQ under Infrastructure Automation.

**Comment by charlesrichard** [comment]
Information on ManageIQ can be found here-> http://manageiq.org/

ManageIQ is 100% open source. It's core project can be found here-> https://github.com/ManageIQ/manageiq

"ManageIQ is an open-source Management Platform that delivers the insight, control, and automation that enterprises need to address the challenges of managing hybrid IT environments. It has the following feature sets:

Insight: Discovery, Monitoring, Utilization, Performance, Reporting, Analytics, Chargeback, and Trending.
Control: Security, Compliance, Alerting, Policy-Based Resource and Configuration Management.
Automate: IT Process, Task and Event, Provisioning, Workload Management and Orchestration.
Integrate: Systems Management, Tools and Processes, Event Consoles, CMDB, RBA, and Web Services."

**Comment by shawnpreissner** [comment]
Thanks for all the detail @charlesrichard, this will be included in the upcoming 0.9.8 version!

**Comment by shawnpreissner** [comment]
Closing @charlesrichard as this update was included in the most recent version https://github.com/cncf/landscape#current-version
