### ISSUE TITLE
Include 3Scale under Service Management

### ISSUE THREAD

**Issue by charlesrichard** [cncf/landscape#155]
Include 3Scale under Service Management

**Comment by charlesrichard** [comment]
Information on 3Scale API Management can be found here-> https://www.3scale.net/

It is not 100% open source yet, but Red Hat is making it so.

**Comment by shawnpreissner** [comment]
Hi @charlesrichard, we are including 3Scale in the upcoming version. Thanks

**Comment by shawnpreissner** [comment]
Hi @charlesrichard closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
