### ISSUE TITLE
Include documentation-related tools

### ISSUE THREAD

**Issue by mildis** [cncf/landscape#156]
Like

- [ReadTheDocs](http://www.readthedocs.io) for documentation hosting
- [EasyDocContents](http://www.easydoccontents.com) for documentation redaction and integration

**Comment by shawnpreissner** [comment]
Hi @mildis, leaving this open as we'll consider it for a future release. Thanks for the suggestion.

**Comment by shawnpreissner** [comment]
Hi @mildis, like the idea, however real estate is a current challenge with the Landscape and I'm not seeing enough players/momentum to warrant the new category, today. Closing for now, thanks.
