### ISSUE TITLE
Update Sonatype Nexus logo

### ISSUE THREAD

**Issue by derekeweeks** [cncf/landscape#157]
![sonatype nexus stack](https://user-images.githubusercontent.com/7955995/29498304-ee71d418-85c6-11e7-9f95-e87a4439ed3c.png)

**Comment by shawnpreissner** [comment]
Hi @derekeweeks, we are updating this logo in the upcoming version, releasing soon! Thanks

**Comment by shawnpreissner** [comment]
Thanks @derekeweeks, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
