### ISSUE TITLE
Update logo for Packet

### ISSUE THREAD

**Issue by jacobsmith928** [cncf/landscape#159]
This is not a rush, but Packet is starting to focus on a new version of its logo.   PNG and EPS attached (in zip due to github upload issue).

![packet_logo_color](https://user-images.githubusercontent.com/7989673/29498525-38a33f36-85cc-11e7-938d-ef6f10ba6fb3.png)

[Packet_logo_color.eps.zip](https://github.com/cncf/landscape/files/1237366/Packet_logo_color.eps.zip)

**Comment by shawnpreissner** [comment]
Hi @jacobsmith928, of course, we'll update for the new version that's releasing soon! Thanks

**Comment by shawnpreissner** [comment]
Thanks @jacobsmith928, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version

**Comment by jacobsmith928** [comment]
thanks so much @shawnpreissner !
