### ISSUE TITLE
Include Portus in the CNCF Cloud Native Landscape

### ISSUE THREAD

**Issue by aclark801** [cncf/landscape#160]
Please include Portus in the CNCF Cloud Native Landscape

**Project or Product name**:
Portus

**Is it open source?**:
Yes

**What's the best URL for it (repo for open source, product homepage for closed source)**:
http://port.us.org/

This links to the documentation and github repositories

**What category does it belong in?**
“Registry Services” in “App Definition & Development”

**What's the URL for the best logo (and it needs to include the name)?**
https://github.com/SUSE/Portus/blob/master/public/favicon/android-chrome-192x192.png

**Anything else we need to know?**:
Portus is a next open source authorization service and user interface for the next generation Registry.  It has completed several releases and is growing in features, contributors and momentum.

**Comment by raghu999** [comment]
+1

**Comment by shawnpreissner** [comment]
Hi @aclark801, looks great, we are including Portus in the upcoming version! Look for under Container Registries category (renamed from Registry Services). Thanks

**Comment by shawnpreissner** [comment]
Thanks @aclark801, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
