### ISSUE TITLE
Intel clear containers

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#161]
**Project or Product name**:

Intel Clear Containers

**Is it open source?**:

Yes

**What's the best URL for it (repo for open source, product homepage for closed source)**:

https://clearlinux.org/features/intel%C2%AE-clear-containers
https://github.com/01org/cc-oci-runtime

**What category does it belong in?**

Container runtime

**What's the URL for the best logo (and it needs to include the name)?**

Use https://clearlinux.org/file/65 with "Intel® Clear Containers" under it, in the font from https://clearlinux.org/features/intel%C2%AE-clear-containers

**Anything else we need to know?**:

Ask @dankohn with questions.

**Comment by shawnpreissner** [comment]
Thanks for the detail @dankohn, this will be included in the upcoming 0.9.8 version.

**Comment by shawnpreissner** [comment]
Hi @dankohn, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
