### ISSUE TITLE
Inclusion of MemSQL in cloud native landscape

### ISSUE THREAD

**Issue by boyarski** [cncf/landscape#162]
**Please only report on one project or product per issue**

Guidelines for getting added to the CNCF Cloud Native Landscape:

* We generally will only list a company in one box, to represent its major or best known offering. We occasionally make exceptions for large companies.
* Projects with at least 250 GitHub stars that clearly fit in an existing category are generally included.
* We are unlikely to create a new category for products/projects as we'd rather find the best home with the current options.
* We are generally not including commercial versions of open source software, when that version just includes minor tweaks.
* Your project or company needs a logo.

**Project or Product name**:
MemSQL

**Is it open source?**:
No

**What's the best URL for it (repo for open source, product homepage for closed source)**:
www.memsql.com
https://github.com/memsql

**What category does it belong in?**
Database and Data Warehouse

**What's the URL for the best logo (and it needs to include the name)?**
https://brandfolder.com/memsql

**Anything else we need to know?**:

**Comment by shawnpreissner** [comment]
Hi @boyarski, like the persistent offering of MemSQL, we'll include in the upcoming version! Thanks

**Comment by shawnpreissner** [comment]
Thanks @boyarski, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
