### ISSUE TITLE
please add DriveScale

### ISSUE THREAD

**Issue by marimaya** [cncf/landscape#163]
**Project or Product name**: DriveScale

**Is it open source?**: no

**What's the best URL for it (repo for open source, product homepage for closed source)**:  https://www.drivescale.com

**What category does it belong in?**. metal prov

**What's the URL for the best logo (and it needs to include the name)?** https://www.drivescale.com
![ds_horiz_sig_rgb_for_web](https://user-images.githubusercontent.com/29932195/29692163-85533b32-88e3-11e7-9aa2-64c802430b10.jpeg)
![ds_vert_sig_rgb_for_web](https://user-images.githubusercontent.com/29932195/29692164-8560a40c-88e3-11e7-8035-c65f9c668eb2.jpeg)

**Anything else we need to know?**:

**Comment by shawnpreissner** [comment]
Hi @marimaya, like the work, however real estate is a current challenge with the Landscape and I'm not seeing the type of requested momentum, today. Keep it up and I'll close for now. Thanks
