### ISSUE TITLE
Provide categorisation of projects per SIG group.

### ISSUE THREAD

**Issue by bwplotka** [cncf/landscape#1632]
I might be wrong, but I think this is not possible at the moment, right?

The rationales are that with the recent creation of SIG Observability I feel like slowly each project within CNCF can be easily assigned to each SIG. It would be awesome for the landscape to quickly give that information and become source of truth. What do you think? (: 

CC @idvoretskyi @caniszczyk 

## Acceptance Criteria:

* Allow filtering projects assigned only to SIG X (e.g SIG Observability).

Related to: https://github.com/cncf/sig-observability/issues/10

----
PS:
> ### Don't create an issue

Sorry ):

**Comment by dankohn** [comment]
I believe each subcategory can easily be assigned to a SIG, so there's no need for extra landscape functionality. Specifically, everything under Observability & Analysis belongs to SIG Observability. https://landscape.cncf.io/category=observability-and-analysis&format=card-mode&grouping=category

**Comment by bwplotka** [comment]
I think that can work, for now, thank you!

**Comment by dankohn** [comment]
Great, thanks for engaging on this.
