### ISSUE TITLE
Include Kasten in the Cloud Native Landscape

### ISSUE THREAD

**Issue by ntolia** [cncf/landscape#164]
**Project or Product name**:

Kasten

**Is it open source?**:

No, commercial.

**What's the best URL for it (repo for open source, product homepage for closed source)**:

http://kasten.io

**What category does it belong in?**

Storage

**What's the URL for the best logo (and it needs to include the name)?**

https://drive.google.com/file/d/0B9QNFSAKWcMIcktlVHZ6WDBYdjA/view?usp=sharing is a PNG but please let me know if you prefer SVG or any other format/resolution.

**Anything else we need to know?**:

No but please ping me for any questions.

**Comment by dankohn** [comment]
Hi, I just updated the guidelines to make clear that we're not including stealth mode products. However, we're hoping to learn about Kasten at [KubeCon + CloudNativeCon](http://events.linuxfoundation.org/events/kubecon-and-cloudnativecon-north-america) in Austin and will then happily include you. Thanks.
