### ISSUE TITLE
Please add Cilium

### ISSUE THREAD

**Issue by mskarbek** [cncf/landscape#165]
**Project or Product name**:
Cilium

**Is it open source?**:
Yes

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source.**:
https://github.com/cilium/cilium
https://www.cilium.io/

**What category does it belong in?**
Cloud-Native Network

**What's the URL for the best logo (and it needs to include the name)?**
https://github.com/cilium/cilium/blob/master/Documentation/images/logo.svg
Yes

**Anything else we need to know?**:
No

**Comment by shawnpreissner** [comment]
Hi @mskarbek, yes happy to include Cilium in the upcoming version, releasing soon! Thanks

**Comment by shawnpreissner** [comment]
Thanks @mskarbek, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
