### ISSUE TITLE
Please add NetFoundry logo to Cloud native Networking landscape

### ISSUE THREAD

**Issue by sreesarva** [cncf/landscape#1658]
Creating an issues per email from Chris to add the logo:

On Wed, Apr 29, 2020 at 10:08 AM Chris Aniszczyk <caniszczyk@linuxfoundation.org> wrote:
Yes, just please send a PR :)
On Wed, Apr 29, 2020 at 12:05 PM Sreelakshmi Sarva <sree.sarva@netfoundry.io> wrote:
Hello Taylor  NetFoundry has been a silver member of CNCF with our opensource project for cloud native networking https://ziti.devCan you please let us know whats the procedure to add ourselves to the CNCF landscape page? I know we provided a high resolution logo when we were onboarded, I assumed that logo would reflect on landscape page automatically but that doesn't seem to be the case.

### Don't create an issue

If you see an error in the cards or missing ones, please don't create an issue here. Instead, edit landscape.yml (you can even do it via the GitHub web interface) and open a pull request. Then, review the preview staging server that's posted to your pull request and add a comment if your new or updated card looks correct and is ready to merge. Before going forward, please carefully review the sections of the Readme covering new entries, corrections, and logos: https://github.com/cncf/landscape/blob/master/README.md.

**Comment by caniszczyk** [comment]
please create a PR
