### ISSUE TITLE
triton also under Bare Metal

### ISSUE THREAD

**Issue by fayazg** [cncf/landscape#166]
**Project or Product name**: Triton

**Is it open source?**: Yes

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source.**:  
*   [Product home page](https://www.joyent.com/triton)  
*   [Repo](https://github.com/joyent/triton)  

**What category does it belong in?**: Bare Metal

**What's the URL for the best logo (and it needs to include the name)?**
[Triton Logo](https://drive.google.com/file/d/0BzH1899GrQqfRkxQa05yc3dBb2M/view?usp=sharing)

**Anything else we need to know?**: Triton is an opensource **platform**, which runs **baremetal** on-prem and also available as a public cloud container service.

**Comment by dankohn** [comment]
Thanks. We can only include you once, so please choose between Platform and Bare Metal. I would recommend staying in Platform.

**Comment by shawnpreissner** [comment]
Hi @fayazg, haven't heard back so assuming you also prefer staying in Platform. Closing for now but please create a new issue if you decide you'd like to move. Thanks
