### ISSUE TITLE
Chart needs some kind of title

### ISSUE THREAD

**Issue by cjyabraham** [cncf/landscape#1668]
I think this chart here needs some kind of title or y-axis label so it's clear what it represents.  I wasn't sure if it was a count of the number of tweets, commits or what:
<img width="1109" alt="Screen Shot 2020-05-06 at 9 24 49 AM" src="https://user-images.githubusercontent.com/463160/81131343-6d8f1900-8f7d-11ea-9ac8-9d2111cddbe6.png">

**Comment by dankohn** [comment]
Closed for https://github.com/cncf/landscapeapp/issues/552
