### ISSUE TITLE
Triton Object Storage under Cloud-Native Storage

### ISSUE THREAD

**Issue by fayazg** [cncf/landscape#167]
**Project or Product name**: Triton Object Storage (manta)

**Is it open source?**: Yes

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source.**:  
*   [Product home page](https://www.joyent.com/triton/object-storage)  
*   [Repo](https://github.com/joyent/manta/)  

**What category does it belong in?**: Cloud-Native Storage

**What's the URL for the best logo (and it needs to include the name)?**: [Triton Object Storage Logo](https://drive.google.com/file/d/0BzH1899GrQqfb2tHSGRuR21fVkU/view?usp=sharing)

**Comment by dankohn** [comment]
We could include Manta if it had its own logo, but I suggest leaving Triton
in platform.

https://github.com/joyent/manta

--
Dan Kohn <mailto:dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation <https://cncf.io/>
tel:+1-415-233-1000

**Comment by fayazg** [comment]
They both have the word Triton in them but [Triton **Compute**](https://drive.google.com/file/d/0BzH1899GrQqfRkxQa05yc3dBb2M/view?usp=sharing) and [Triton **Object Storage**](https://drive.google.com/file/d/0BzH1899GrQqfb2tHSGRuR21fVkU/view?usp=sharing) are two different products with their own logos.

**Comment by dankohn** [comment]
We are artificially limiting the number of products that we show for the public clouds, or else you, AWS and GCP would have a product entry in every box (e.g., note that we don't include EBS or RDS). Instead, we're limiting it to Joyent in public cloud and Triton in platform. However, we would be happy to include Manta as an open source project if it had a logo.

**Comment by fayazg** [comment]
I understand. [Here](https://drive.google.com/file/d/0BzH1899GrQqfbGpqUXJ0ZDkwRU0/view?usp=sharing) is the [manta](https://github.com/joyent/manta/) logo.

**Comment by dankohn** [comment]
Great, thank you.

**Comment by shawnpreissner** [comment]
Hi @fayazg, thanks for providing, we are including in the upcoming version.

**Comment by shawnpreissner** [comment]
Thanks @fayazg, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
