### ISSUE TITLE
Better categorization of service proxy / ingress

### ISSUE THREAD

**Issue by richarddli** [cncf/landscape#1678]
In the current landscape, the service proxy & API Gateway categories overlap and are confusing. In general, a service proxy is a client-side proxy that enables applications to send and receive traffic. Examples of service proxies include HAProxy, Envoy Proxy, Traefik, and NGINX.

Service Proxies are usually managed with "control planes". In Kubernetes, these control planes are ingress controllers. These ingress controllers are built on top of service proxies. Examples of this are:

- Ambassador, Contour (built on Envoy Proxy)
- Traefik Ingress Controller (built on Traefik)
- Voyager, HAProxy ingress controller (built on HAProxy)

etc.

Finally, there are API Gateways that have integrated ingress controllers. This includes Ambassador  API Gateway and Kong API Gateway.

My suggestion would be:

1. Create a more strict definition of service proxy, with Envoy Proxy, NGINX, etc in it
2. Create a more broad category of "API Gateway / ingress controller" and put everything else in it

Alternatively, we could create:

1. Service Proxy
2. Ingress Controller
3. API Gateway

and allow projects to be in more than one category.

**Comment by dankohn** [comment]
We're open to making this change. Could you please fully flesh out the proposal (i.e., what goes where). Note that the complexity of Service Proxy, API Gateway, Service Mesh was designed to be increasing from left to right.

**Comment by dankohn** [comment]
Please reopen with a concrete suggestion of exactlt what goes where.
