### ISSUE TITLE
ContainerPilot under Scheduling & Orchestration

### ISSUE THREAD

**Issue by fayazg** [cncf/landscape#168]
**Project or Product name**: [ContainerPilot](https://www.joyent.com/containerpilot)

**Is it open source?**: Yes

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source.**:  
*   [Product home page](https://www.joyent.com/containerpilot)  
*   [Repo](https://github.com/joyent/containerpilot)  

**What category does it belong in?**: Scheduling & Orchestration

**What's the URL for the best logo (and it needs to include the name)?**: [ContainerPilot Logo](https://drive.google.com/file/d/0BzH1899GrQqfdGk5eUI5M0QyUXc/view?usp=sharing)

**Comment by dankohn** [comment]
We're happy to add to Service Discovery.

--
Dan Kohn <mailto:dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation <https://cncf.io/>
tel:+1-415-233-1000

**Comment by shawnpreissner** [comment]
Thanks for all the detail @fayazg, this will be included in the upcoming 0.9.8 version!

**Comment by shawnpreissner** [comment]
@fayazg closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
