### ISSUE TITLE
SmartOS under Container Runtime

### ISSUE THREAD

**Issue by fayazg** [cncf/landscape#169]
**Project or Product name**: SmartOS

**Is it open source?**: Yes

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source.**:  
*   [Product home page](https://www.joyent.com/smartos)  
*   [Repo](https://github.com/joyent/smartos-live)  

**What category does it belong in?**: Container Runtime

**What's the URL for the best logo (and it needs to include the name)?**: [SmartOS Logo](https://drive.google.com/file/d/0BzH1899GrQqfRmotYk1qMlhITWs/view?usp=sharing)

**Comment by shawnpreissner** [comment]
@fayazg will add to upcoming version

**Comment by shawnpreissner** [comment]
@fayazg closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
