### ISSUE TITLE
Add Oracle Cloud to Infrastructure

### ISSUE THREAD

**Issue by brunoborges** [cncf/landscape#17]
cloud.oracle.com provides [Elastic Compute](http://cloud.oracle.com/compute), [Bare Metal Compute ](https://cloud.oracle.com/bare-metal)for Cloud infrastructure provisioning, as well [Container](http://cloud.oracle.com/container) orchestration.

**Comment by shawnpreissner** [comment]
Oracle is now included under Infrastructure in v0.9.3
