### ISSUE TITLE
Add Sensu to the Landscape 👌

### ISSUE THREAD

**Issue by mbbroberg** [cncf/landscape#170]
**Project or Product name**: Sensu

**Is it open source?**: Yes

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source.**: [Repo](https://github.com/sensu/sensu) | [Homepage](https://sensuapp.org)

**What category does it belong in?** Observability & Analysis

**What's the URL for the best logo (and it needs to include the name)?** https://raw.githubusercontent.com/sensu/sensu-logo/master/sensu1_flat%20white%20bg_png.png

**Anything else we need to know?**: Nope, thank you for curating this incredible list!

**Comment by mbbroberg** [comment]
👋 @dankohn. Would it be helpful if I opened a PR with edits to the .ai file? Glad to help where I can!

**Comment by dankohn** [comment]
No thanks, you've submitted everything we need and we'll include it in the
next version.

--
Dan Kohn <mailto:dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation <https://cncf.io/>
tel:+1-415-233-1000

**Comment by shawnpreissner** [comment]
Thanks for all the detail @mbbroberg, Sensu will be included in the upcoming 0.9.8 version!

**Comment by mbbroberg** [comment]
Thanks so much @shawnpreissner 🙌

**Comment by shawnpreissner** [comment]
Hi @mbbroberg, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version

**Comment by mbbroberg** [comment]
🙌  Thanks @shawnpreissner 🙌
