### ISSUE TITLE
sloppy.io under Container Service

### ISSUE THREAD

**Issue by MikeMichel** [cncf/landscape#171]
Project or Product name: sloppy.io

Is it open source?: No

Product home page:  https://sloppy.io
Repo: https://github.com/sloppyio
What category does it belong in?: PaaS/Container Service

What's the URL for the best logo (and it needs to include the name)?: sloppy.io
![sloppy-logo-typo-high](https://user-images.githubusercontent.com/8025931/29916470-2e047524-8e3f-11e7-91c4-69dff2ca6567.png)
 Logo

**Comment by shawnpreissner** [comment]
Hi @MikeMichel, like the work, however real estate is a current challenge with the Landscape and I'm not seeing the type of requested momentum, today. Keep it up and I'll close for now. Thanks
