### ISSUE TITLE
Apache NiFi

### ISSUE THREAD

**Issue by rahst12** [cncf/landscape#172]
Apache NiFi should be included as a streaming technology.

**Project or Product name**: Apache NiFi

**Is it open source?**: Yes

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source.**: 
https://nifi.apache.org/index.html
https://github.com/apache/nifi - 640 GitHub stars

**What category does it belong in?**
Streaming data

**What's the URL for the best logo (and it needs to include the name)?**
https://nifi.apache.org/assets/images/apache-nifi-logo.svg

**Anything else we need to know?**:
Apache NiFi supports powerful and scalable directed graphs of data routing, transformation, and system mediation logic. Some of the high-level capabilities and objectives of Apache NiFi include:

Web-based user interface
Seamless experience between design, control, feedback, and monitoring
Highly configurable
Loss tolerant vs guaranteed delivery
Low latency vs high throughput
Dynamic prioritization
Flow can be modified at runtime
Back pressure
Data Provenance
Track dataflow from beginning to end
Designed for extension
Build your own processors and more
Enables rapid development and effective testing
Secure
SSL, SSH, HTTPS, encrypted content, etc...
Multi-tenant authorization and internal authorization/policy management

**Comment by shawnpreissner** [comment]
Thanks for all the detail @rahst12, this will be included in the upcoming 0.9.8 version!

**Comment by shawnpreissner** [comment]
Hi @rahst12, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version

**Comment by rahst12** [comment]
That's amazing, thanks!
