### ISSUE TITLE
Add Nuage Networks in the Cloud-Native Network category

### ISSUE THREAD

**Issue by rvichery** [cncf/landscape#173]
Could you please add Nuage Networks in the Cloud-Native Network category ?

**Product name**: Nuage Networks VSP

**Is it open source?**: Partially. Our core product is not open source but some of our network plugins are.

**What are the best URL(s) for it?**
[Github repositories](https://github.com/nuagenetworks)
[CNI github repository](https://github.com/nuagenetworks/nuage-cni)
[Company website](http://www.nuagenetworks.net/)
[Product page](http://www.nuagenetworks.net/products/virtualized-cloud-services/)

**What category does it belong in?** Cloud-Native Network

**What's the URL for the best logo ?** 

![nuage_v_colour_cmyk_large](https://user-images.githubusercontent.com/6019102/29992977-e6e92a02-8f5d-11e7-855b-0bf748f13dd9.png)

[nuage_v_colour_CMYK_large.ai.zip](https://github.com/cncf/landscape/files/1271899/nuage_v_colour_CMYK_large.ai.zip)

**Comment by shawnpreissner** [comment]
Thanks for all the detail @rvichery, this will be included in the upcoming 0.9.8 version!

**Comment by shawnpreissner** [comment]
Hi @rvichery, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
