### ISSUE TITLE
Update AWS logo

### ISSUE THREAD

**Issue by aaronkao** [cncf/landscape#174]
**Project or Product name**:
Amazon Web Services

**Is it open source? (if you are tempted to say partially, please answer no)**:
No

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source.**:
aws.amazon.com

**What category does it belong in?**
Public Cloud

**What's the URL for the best logo (and it needs to include the name)?**
https://upload.wikimedia.org/wikipedia/commons/1/1d/AmazonWebservices_Logo.svg

**Anything else we need to know?**:
Current logo on the landscape has a TM symbol which is not the correct logo. Please update. Thank you

**Comment by dankohn** [comment]
Thanks, we'll fix in the next version.

**Comment by shawnpreissner** [comment]
Thanks @aaronkao, stay tuned as this is updated in the new version, releasing soon!

**Comment by tnir** [comment]
@aaronkao @shawnpreissner Is that logo old? New logo is th following:

https://a0.awsstatic.com/main/images/logos/aws_logo_smile_1200x630.png

**Comment by shawnpreissner** [comment]
Hi @aaronkao @tnir, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
