### ISSUE TITLE
Update the Serverless Framework logo

### ISSUE THREAD

**Issue by krook** [cncf/landscape#175]

**Comment by dankohn** [comment]
Url for the correct logo, please?

**Comment by krook** [comment]
What logo should be used @ac360 @davidwells ?

**Comment by ac360** [comment]
@krook @dankohn Here are our updated logos.  I've also included some square versions which better fit the format of your graphic.  Thank you for doing this!

![serverless-logo-square-rounded](https://user-images.githubusercontent.com/2752551/30405068-a7733b34-989e-11e7-8f66-7badaf1373ed.png)
![serverless-logo-square](https://user-images.githubusercontent.com/2752551/30405069-a7751fee-989e-11e7-9a58-f93f8e820bd1.png)
![serverless-logo-dark](https://user-images.githubusercontent.com/2752551/30404910-d56d9b66-989d-11e7-9208-b720eb28b4f2.png)
![serverless-logo-light](https://user-images.githubusercontent.com/2752551/30404912-d5781a00-989d-11e7-8d25-5ebca177326a.png)
![serverless-logo-transparent](https://user-images.githubusercontent.com/2752551/30404911-d575539c-989d-11e7-9a74-df8533b95c6d.png)

**Comment by dankohn** [comment]
Thanks for the square-oriented logos. We'll definitely get in the next version.

**Comment by shawnpreissner** [comment]
Hi @krook @ac360, please see previous request. I temporarily updated to the horizontal white background version in the latest release https://github.com/cncf/landscape#current-version

Please provide today and I'll get this changed and closed. Thanks

**Comment by shawnpreissner** [comment]
@krook @ac360 can you please respond to let us know how to proceed?

**Comment by shawnpreissner** [comment]
Closing since the stacked, updated version used our latest release -> https://github.com/cncf/landscape#current-version
