### ISSUE TITLE
CloudHealth Technologies

### ISSUE THREAD

**Issue by aschepis** [cncf/landscape#176]
**Project or Product name**: CloudHealth Technologies

**Is it open source? (if you are tempted to say partially, please answer no)**: No

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source.**: https://www.cloudhealthtech.com/

**What category does it belong in?** Observability and Analysis

**What's the URL for the best logo (and it needs to include the name)?** https://www.cloudhealthtech.com/sites/all/themes/cloud_health/img/cloudhealth-tech.svg

**Anything else we need to know?**:

- Support for top 3 major public cloud vendors (AWS, Azure, GCP)
- Analysis of Cost, Usage, Performance, Governance, and Security
- Policy driven automation

**Comment by shawnpreissner** [comment]
Hi @aschepis, like the work, however real estate is a current challenge with the Landscape and I'm not seeing the type of requested momentum, today. Keep it up and I'll close for now. Thanks
