### ISSUE TITLE
Update Twistlock Logo

### ISSUE THREAD

**Issue by joshuathorngren** [cncf/landscape#178]
![twistlock_logo-lockup_rgb](https://user-images.githubusercontent.com/390943/30335459-4b05be7e-9797-11e7-9a26-4554b1e9ddc4.png)

Thank you!

**Comment by shawnpreissner** [comment]
Hi @joshuathorngren, we are updating this for the upcoming version, releasing soon! Thanks

**Comment by shawnpreissner** [comment]
Thanks, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
