### ISSUE TITLE
Add sentry to the landscape

### ISSUE THREAD

**Issue by pieterlange** [cncf/landscape#179]
**Project or Product name**: Sentry

**Is it open source? (if you are tempted to say partially, please answer no)**: yes

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source.**: https://sentry.io - https://github.com/getsentry/sentry

**What category does it belong in?** Observability & Analysis - Monitoring
(Hard to classify - there's a little bit of "tracing" here as well)

**What's the URL for the best logo (and it needs to include the name)?** https://sentry.io/branding/

**Anything else we need to know?**:

**Comment by stympy** [comment]
Perhaps it's time for a new category, since there are multiple providers in this space who are focused on exception monitoring:

- [Honeybadger](https://www.honeybadger.io) - also does uptime monitoring
- [AppSignal](https://appsignal.com) - also does performance monitoring
- [Airbrake](https://airbrake.io)
- [Rollbar](https://rollbar.com/)
- [Raygun](https://raygun.com)
- [Bugsnag](https://www.bugsnag.com)

**Comment by shawnpreissner** [comment]
Hi @pieterlange, thanks for the message, we are including Sentry in the upcoming version, releasing soon!

@stympy, we're happy to consider for a future version, what name(s) are you proposing for this potential new category and what criteria would be used to ensure this category is apart?

**Comment by stympy** [comment]
@shawnpreissner I'm not sure... those providers are indeed monitoring products, but (for the most part) the don't do APM.  So maybe the new category is really just a subset of monitoring, and so doesn't need to be a separate category.  

In the mean time, I've opened https://github.com/cncf/landscape/issues/193 for Honeybadger to be added to monitoring while you ponder the question. :)

**Comment by pieterlange** [comment]
I concur that "exception monitoring" is really its own class/category. It's highly specialized form of monitoring intended to make regular stack traces more consumable through visualization and event rollup/tallying. 

But of course there is a lot of overlap with conventional forms of logging (which extract stacktraces from logs) and apps that span multiple categories (newrelic, honeycomb)

**Comment by shawnpreissner** [comment]
Appreciate the discussion @stympy and @pieterlange. At this time, we don't see firm enough criteria for another partition. Thanks and closing for now...
