### ISSUE TITLE
Add Codeship to CI/CD Tools

### ISSUE THREAD

**Issue by moritzplassnig** [cncf/landscape#18]
Disclaimer: I'm one of the founders of Codeship

[Codeship](https://www.codeship.com) is a Docker-native CI/CD system (CircleCI/TravisCI aren't): https://blog.docker.com/2016/11/new-dockercast-episode-interview-docker-captain-laura-frank/
http://www.slideshare.net/Docker/efficient-parallel-testing-with-docker-by-laura-frank
http://events.linuxfoundation.org/sites/events/files/slides/DC16%20Efficient%20Parallel%20Testing%20with%20Docker.pdf

Works well with Kubernetes: https://resources.codeship.com/ebooks/deploy-docker-kubernetes-codeship

**Comment by dankohn** [comment]
Thanks, we'll be adding.

**Comment by moritzplassnig** [comment]
@dankohn Awesome - thanks :) If you need our logo, you can find it [here](https://www.dropbox.com/s/kfjvkk9aig73wi3/Codeship-Logopack.zip?dl=0).

**Comment by moritzplassnig** [comment]
@dankohn Since we want to get added, we thought that we should do the work and adjust the illustrator file (attached a version including the Codeship logo). Here's a preview:
![upload_12_2_2016_at_5_43_37_pm](https://cloud.githubusercontent.com/assets/516961/20853075/f77b6850-b8bf-11e6-81ba-242764c55f62.png)

And here's the AI file: 
[CloudNativeLandscape_v0.9.2.ai.zip](https://github.com/cncf/landscape/files/628466/CloudNativeLandscape_v0.9.2.ai.zip)

**Comment by shawnpreissner** [comment]
Codeship is now included under CI/CD in v0.9.3
