### ISSUE TITLE
Add "Sematext Cloud" to Observability & Analysis

### ISSUE THREAD

**Issue by megastef** [cncf/landscape#180]
**Project or Product name**:  [Sematext Cloud](http://sematext.com/cloud/)

**Is it open source? (if you are tempted to say partially, please answer no)**: No 

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source.**:  Homepage: http://sematext.com/kubernetes/  GitHub: https://github.com/sematext/sematext-agent-docker

**What category does it belong in?** Observability & Analysis  
Sematext Docker Agent collects metrics, logs, and events. The product would fit in Logging, Monitoring, and Tracing. Is there a "general" section for an all-in-one solution? 

**What's the URL for the best logo (and it needs to include the name)?** https://sematext.com/wp-content/uploads/2017/09/octi-square-logo-200x200-2.png

**Anything else we need to know?**:
Sematext Docker Agent is Docker Certified and Red Hat Certified. Sematext is Red Hat and Kubernetes partner. 
- https://kubernetes.io/partners/
- http://blog.kubernetes.io/2016/11/kubernetes-containers-logging-monitoring-with-sematext.html
- https://access.redhat.com/containers/?tab=overview#/registry.connect.redhat.com/sematext/sematext-agent-docker
- https://store.docker.com/images/sematext-agent-monitoring-and-logging

**Comment by shawnpreissner** [comment]
Hi @megastef, we are including Sematext in the Logging section for the upcoming version, releasing soon! Thanks

**Comment by otisg** [comment]
That's great.  Note that Sematext provides Infrastructure Monitoring (including containers) and APM, too.

**Comment by shawnpreissner** [comment]
Understood @otisg, however we generally limit to 1 category. Closing as we placed in best fit - Logging, please reopen if you'd prefer a different location. Thanks
