### ISSUE TITLE
A suggestion on the website regarding transparent SVGs and/or PNG

### ISSUE THREAD

**Issue by TommyUnger** [cncf/landscape#1804]
I noticed that a lot of the landscape website is filled with SVGs and/or transparent PNGs. I was wondering if you could adopt an approach that puts white backgrounds on all logos. Because the way it works now is that there are grey backgrounds and white backgrounds. It might help the experience to keep all logos on a white background.

Maybe just something like this?
```
.nonoss img {
    background: #ffffff;
}
```

Otherwise I wanted to say this is a great website and a cool deployment workflow!

**Comment by TommyUnger** [comment]
Oh. I figured out there's logic here. Non-OSS vs OSS. Sorry for the trouble.

**Comment by dankohn** [comment]
No worries. We're always glad when people are looking closely enough to have suggestions.
