### ISSUE TITLE
Joyent (under public cloud) is open source

### ISSUE THREAD

**Issue by fayazg** [cncf/landscape#181]
Joyent under Public Cloud section should be marked as open source.

### github repos:
* [adminui](https://github.com/joyent/sdc-adminui)
* [triton](https://github.com/joyent/triton)
* [manta](https://github.com/joyent/manta)

#### Networking API
* [sdc-napi](https://github.com/joyent/sdc-napi)

#### Compute API
* [sdc-docker](https://github.com/joyent/sdc-docker)
* [sdc-cloudapi](https://github.com/joyent/sdc-cloudapi)

#### Storage API
* [sdc-manta](https://github.com/joyent/sdc-manta)

Above are some of the key repos, for anything else, look under [https://github.com/joyent/](https://github.com/joyent/).

Thanks

**Comment by dankohn** [comment]
@fayazg I know that much of Joyent's software stack is open source. But is 100% of it? Even the billing software?

**Comment by fayazg** [comment]
The only component that isn't open source was our UI/billing.
Our new UI can be found [here](https://github.com/yldio/copilot). For billing, we will be using third party tool Zuora. [node_zuora repo](https://github.com/joyent/node_zuora)

**Comment by dankohn** [comment]
That's fascinating. Have you done a blog post about this? There are some providers that are running OpenStack, but even there they tend not to open source every aspect of their offering.

Are you saying that (modulo finding competent people to run and maintain it), I can exactly recreate Joyent's services using your open source offerings (and the same third-party billing tools)? If so, I would agree that Joyent should be shown as open source not proprietary.

Cc @bcantrill

**Comment by bcantrill** [comment]
Yes, we blogged about [open sourcing SmartDataCenter (Triton) and Manta](https://www.joyent.com/blog/sdc-and-manta-are-now-open-source), and we've been 100% open ever since -- and that has remained true post Samsung acquisition.

**Comment by dankohn** [comment]
Great, thanks. We'll mark Joyent as an open source public cloud in our next version, hopefully in just a couple weeks.

**Comment by shawnpreissner** [comment]
Thanks @bcantrill @fayazg, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
