### ISSUE TITLE
Add leofs as Distributed storage/Data Lake

### ISSUE THREAD

**Issue by raghu999** [cncf/landscape#182]
**Project or Product name**: **## LEOFS**

**Is it open source? (if you are tempted to say partially, please answer no)**: Yes

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source.**: 
https://leo-project.net/leofs/
https://github.com/leo-project/leofs/
**What category does it belong in?**
Cloud Native Storage
**What's the URL for the best logo (and it needs to include the name)?**
https://leo-project.net/leofs/
**Anything else we need to know?**:
Multi protocol Support S3,NFS and Embedded

**Comment by shawnpreissner** [comment]
Hi @raghu999, we are including LeoFS in the Cloud Native Storage section of the upcoming version, releasing soon! Thanks

**Comment by shawnpreissner** [comment]
Thanks @raghu999, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
