### ISSUE TITLE
Jenkins is open and commercial, many enterprises use the commercial, half/half colored tile would be fair.

### ISSUE THREAD

**Issue by NaranKPatel** [cncf/landscape#183]
Jenkins is open source but the best features and support is commercial only, I think it would be fair to tilt in the favor of being commercial product, as the founder and main contributor has joined CloudBees, or at the very least half tile grey and full color graphic.

**Comment by shawnpreissner** [comment]
Jenkins appears to be open source to me https://github.com/jenkinsci/jenkins and selling support is another thing. Opening it up for discussion though... @dankohn your thoughts please? Also, the comment on half grey tile is interesting, however IMO it would lead to visual confusion and then 75/25, etc.

**Comment by NaranKPatel** [comment]
I think CloudBees (grey) and Jenkins (white) just about covers it, thanks.

Having the highlighted Blue as CNCF aligned "Projects", White as Open-source and Grey as Commercial makes it clear and readable at first glance.

I'm also pretty glad that there are very few or none Grey/Commercial "Projects" that pose as Blue ;-)

**Comment by shawnpreissner** [comment]
Yes, gotcha. Thanks @NaranKPatel
