### ISSUE TITLE
Axibase Time Series Database

### ISSUE THREAD

**Issue by rodionos** [cncf/landscape#184]
**Please only report on one project or product per issue**

Guidelines for getting added to the CNCF Cloud Native Landscape:

* We generally will only list a company in one box, to represent its major or best known offering. We occasionally make exceptions for large companies.
* Projects with at least 250 GitHub stars that clearly fit in an existing category are generally included.
* We are unlikely to create a new category for products/projects as we'd rather find the best home with the current options.
* We are generally not including commercial versions of open source software, when that version just includes minor tweaks.
* Closed source products need to link to a clear description of your product; no stealth mode companies.
* Your project or company needs a logo.

**Project or Product name**:

Axibase Time Series Database

**Is it open source? (if you are tempted to say partially, please answer no)**:

No

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source.**:

https://axibase.com/products/axibase-time-series-database/

**What category does it belong in?**

Observability and Analysis

> The category is based on the Docker monitoring use case: https://github.com/axibase/atsd-use-cases/tree/master/Solutions/docker

**What's the URL for the best logo (and it needs to include the name)?**

http://axibase.com/wp-content/uploads/2014/12/axibase_logo_orange-2.png

**Anything else we need to know?**:

Github Stars: 

* https://github.com/axibase/atsd - 31 
* https://github.com/axibase/atsd-use-cases - 304
* Other repos with clients etc.

**Comment by shawnpreissner** [comment]
Hi @rodionos, we are including Axibase under Monitoring in the upcoming version, releasing soon! Thanks

**Comment by rodionos** [comment]
@shawnpreissner Great, thank you.
