### ISSUE TITLE
Adding nuclio to "serverless/event-based" under Platform

### ISSUE THREAD

**Issue by iguazioDani** [cncf/landscape#185]
**Project or Product name:** nuclio

**Is it open source? (if you are tempted to say partially, please answer no)**: Yes

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source.**: https://github.com/nuclio/nuclio

**What category does it belong in?** "serverless/event-based" under Platform

**What's the URL for the best logo (and it needs to include the name)?** https://github.com/nuclio/nuclio/blob/master/docs/images/logo.png

**Anything else we need to know?**: Thank you!

**Comment by shawnpreissner** [comment]
Hi @iguazioDani, very cool project, we are including nuclio in the upcoming version. Thanks

**Comment by shawnpreissner** [comment]
Thanks @iguazioDani, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
