### ISSUE TITLE
Add Visual Studio Team Services to App Definition and Development

### ISSUE THREAD

**Issue by ethomson** [cncf/landscape#186]
**Project or Product name**:
Microsoft Visual Studio Team Services

**Is it open source? (if you are tempted to say partially, please answer no)**:
No

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source.**:
https://visualstudio.com/team-services

**What category does it belong in?**
App Definition and Development : SCM and
App Definition and Development : CI/CD

**What's the URL for the best logo (and it needs to include the name)?**
[vsts-with-text-stacked.pdf](https://github.com/cncf/landscape/files/1351947/vsts-with-text-stacked.pdf)

**Anything else we need to know?**:
Microsoft Visual Studio Team Services is a hosted application platform providing agile project management, version control hosting (Git repositories and centralized), continuous integration including Azure-hosted build agents and continuous delivery.

**Comment by dankohn** [comment]
It needs to be one category, sorry. Which do you prefer?

**Comment by ethomson** [comment]
If we can be in only one, then I suppose SCM.

However, you have another integrated solution in both categories (GitLab).  Are you going to keep them from both?

**Comment by dankohn** [comment]
GitLab Runner is a separate open source project with more than 250 stars.
https://gitlab.com/gitlab-org/gitlab-runner. Although it's mostly used with
GitLab it can be run independently.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by ethomson** [comment]
I see.  Thanks for the clarification.

**Comment by shawnpreissner** [comment]
Hi @ethomson, we are including VSTS in the upcoming version, releasing soon! Thanks

**Comment by shawnpreissner** [comment]
Thanks @ethomson, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
