### ISSUE TITLE
Please add Kublr to CNCF Landscape

### ISSUE THREAD

**Issue by CatPaga** [cncf/landscape#188]
**Please only report on one project or product per issue**

Guidelines for getting added to the CNCF Cloud Native Landscape:

* We generally will only list a company in one box, to represent its major or best known offering. We occasionally make exceptions for large companies.
* Projects with at least 250 GitHub stars that clearly fit in an existing category are generally included.
* We are unlikely to create a new category for products/projects as we'd rather find the best home with the current options.
* We are generally not including commercial versions of open source software, when that version just includes minor tweaks.
* Closed source products need to link to a clear description of your product; no stealth mode companies.
* Your project or company needs a logo.

**Project or Product name**: Kublr

**Is it open source? (if you are tempted to say partially, please answer no)**: No

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**: kublr.com

**What one category does it best belong in?** Platform 

**What's the URL for the best logo (and it needs to include the name)?** kublr.com/logo

**Anything else we need to know?**:

Thank you!

**Comment by shawnpreissner** [comment]
Hi @CatPaga, we are including Kublr in the upcoming version, releasing soon! Thanks

**Comment by shawnpreissner** [comment]
Thanks @CatPaga, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version

**Comment by CatPaga** [comment]
Thank you!
