### ISSUE TITLE
Update Red Hat logos

### ISSUE THREAD

**Issue by chuckdubuqueRH** [cncf/landscape#1896]
Red Hat logos need to be updated for Red Hat OpenShift, and Red Hat OpenShift Dedicated
[Archive.zip](https://github.com/cncf/landscape/files/5519915/Archive.zip)

**Comment by goat023** [comment]
I'm would like to contribute to this issue, but I'm new here. can someone guide me?

**Comment by adithyaakrishna** [comment]
Is this issue still open? or does it need any updating? 👀

**Comment by xmulligan** [comment]
this was closed with #1973
