### ISSUE TITLE
Add Contiv to Cloud Native Network

### ISSUE THREAD

**Issue by rohitagarwalla** [cncf/landscape#19]
https://github.com/contiv/netplugin
http://contiv.github.io/documents/networking/

Thanks ! 
Rohit

**Comment by dankohn** [comment]
Thanks. Could you please also fill in this spreadsheet comparing networking options. https://docs.google.com/spreadsheets/d/1polIS2pvjOxCZ7hpXbra68CluwOZybsP1IYfr-HrAXc/edit#gid=0

Cc @monadic

**Comment by rohitagarwalla** [comment]
thanks @dankohn for sharing doc pointer. We have updated the sheet though need some additional clarification on one of the rows (posted comment in the spreadsheet). 

cc @jojimt

**Comment by jojimt** [comment]
Yes, would be nice to have clarity on what is meant by "partially connected host network"

**Comment by shawnpreissner** [comment]
Contiv is now included under Cloud Native Network in v0.9.3

**Comment by rohitagarwalla** [comment]
Great. Thanks !
