### ISSUE TITLE
Please add StackRox to the Cloud Native Landscape

### ISSUE THREAD

**Issue by roxeng** [cncf/landscape#190]
**Please only report on one project or product per issue**

Guidelines for getting added to the CNCF Cloud Native Landscape:

* We generally will only list a company in one box, to represent its major or best known offering. We occasionally make exceptions for large companies.
* Projects with at least 250 GitHub stars that clearly fit in an existing category are generally included.
* We are unlikely to create a new category for products/projects as we'd rather find the best home with the current options.
* We are generally not including commercial versions of open source software, when that version just includes minor tweaks.
* Closed source products need to link to a clear description of your product; no stealth mode companies.
* Your project or company needs a logo.

**Project or Product name**: StackRox

**Is it open source? (if you are tempted to say partially, please answer no)**: No

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**: stackrox.com

**What one category does it best belong in?** "Observability & Analysis" -> "Monitoring" 

**What's the URL for the best logo (and it needs to include the name)?** https://www.stackrox.com/img/logo-300.jpg

**Anything else we need to know?**:

**Comment by shawnpreissner** [comment]
Hi @roxeng, we are including StackRox in the upcoming version, releasing soon! Thanks

**Comment by roxeng** [comment]
Thank you for including us in the latest version of the cloud native landscape. We found an issue with our logo. We had provided https://www.stackrox.com/img/logo-300.jpg as the link to the logo but somehow we see a different one in the cloud native landscape. Would you please correct it. Thank you for all your help.

**Comment by shawnpreissner** [comment]
@roxeng thanks for raising, we'll make the change

**Comment by shawnpreissner** [comment]
Hi, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
