### ISSUE TITLE
Update kubeless logo

### ISSUE THREAD

**Issue by sebgoa** [cncf/landscape#191]
Hi, can the kubeless logo be updated ?
Here is a version with the tag name below the logo which I think will render better:

https://www.dropbox.com/s/ffi624yjjz9b5jt/kubeless.png?dl=0

thanks

**Comment by shawnpreissner** [comment]
Hi @sebgoa, yes we can update this for the upcoming version. Thanks

**Comment by shawnpreissner** [comment]
Thanks @sebgoa , closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version

**Comment by sebgoa** [comment]
thanks a bunch
