### ISSUE TITLE
Update Kubermatic Company Logo 

### ISSUE THREAD

**Issue by KrissiWi** [cncf/landscape#1912]
Hello,

we do have a new logo so our svg requires updating.

https://drive.google.com/file/d/1zMB_SDQ_Z5drgQVuFpt1aYfjqCyifuSy/view?usp=sharing

Thanks,

Kristin

**Comment by KrissiWi** [comment]
@taylorwaggoner : I tried once again to upload the svg but where not able to. If the problem is on my side, thanks for advising. 

Best,

Kristin

**Comment by taylorwaggoner** [comment]
Opened a PR in #1913, thanks!
