### ISSUE TITLE
Update Weave Flux logo

### ISSUE THREAD

**Issue by pidster** [cncf/landscape#192]
Weave Flux .ai in zip attached.

Please include Flux in the CICD category, instead of the Service Management category.

[weave-sq-logos-flux.ai.zip](https://github.com/cncf/landscape/files/1371170/weave-sq-logos-flux.ai.zip)

**Comment by shawnpreissner** [comment]
Thanks @pidster , closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
