### ISSUE TITLE
Add Honeybadger to the landscape

### ISSUE THREAD

**Issue by stympy** [cncf/landscape#193]
**Project or Product name**: Honeybadger

**Is it open source? (if you are tempted to say partially, please answer no)**: No

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**: https://www.honeybadger.io

**What one category does it best belong in?**: Observability & Analysis - Monitoring

**What's the URL for the best logo (and it needs to include the name)?**: https://www.honeybadger.io/assets/

**Anything else we need to know?**:

**Comment by shawnpreissner** [comment]
Hi @stympy, we are including Honeybadger in the upcoming version, releasing soon! Thanks

**Comment by stympy** [comment]
Thanks!

**Comment by shawnpreissner** [comment]
Closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
