### ISSUE TITLE
Streaming: Apache Pulsar (incubating) by Yahoo/Oath, stars = 1,314

### ISSUE THREAD

**Issue by lewiskan** [cncf/landscape#194]
Apache Pulsar is an open-source distributed pub-sub messaging system originally
created at Yahoo and now part of the Apache Software Foundation.
**Project or Product name**:
Apache Pulsar (1,314 GitHub stars)

**Is it open source? (if you are tempted to say partially, please answer no)**:
Yes, Open Source, Apache 2.0, Apache Incubating
2017-06 http://incubator.apache.org/projects/pulsar.html
open sourced in 2016: https://yahooeng.tumblr.com/post/150078336821/open-sourcing-pulsar-pub-sub-messaging-at-scale

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**:
https://github.com/apache/incubator-pulsar
https://pulsar.incubator.apache.org/

**What one category does it best belong in?**
Streaming

**What's the URL for the best logo (and it needs to include the name)?**
Logo: https://pulsar.incubator.apache.org/img/pulsar.png

**Anything else we need to know?**:
Apache Pulsar is supported by Streamlio as part of a unified, real-time solution. Founded by ex-Twitter/Yahoo co-creators of Apache Pulsar (durable messaging, Matteo Merli), Heron (compute, Karthik Ramasamy, Sanjeev Kulkarni), and Apache BookKeeper (stream storage, Sijie Guo), with Lightspeed Series A, announced in August 2017.
https://streaml.io/blog/announcing-streamlio/
https://streaml.io/blog/intro-to-pulsar/
Apache Pulsar also part of Linux Foundation OpenMessaging standard with founding supporters Alibaba Cloud, Di Di, Oath (Yahoo), and Streamlio
https://www.linuxfoundation.org/blog/building-open-standard-distributed-messaging-introducing-openmessaging/

------------------------
Guidelines for getting added to the CNCF Cloud Native Landscape:
* We generally will only list a company in one box, to represent its major or best known offering. We occasionally make exceptions for large companies.
* Projects with at least 250 GitHub stars that clearly fit in an existing category are generally included.
* We are unlikely to create a new category for products/projects as we'd rather find the best home with the current options.
* We are generally not including commercial versions of open source software, when that version just includes minor tweaks.
* Closed source products need to link to a clear description of your product; no stealth mode companies.
* Your project or company needs a logo.

**Comment by shawnpreissner** [comment]
Thanks for all the detail @lewiskan , this will be included in the upcoming 0.9.9 version!

**Comment by lewiskan** [comment]
Thanks, @shawnpreissner , excited to get Apache Pulsar in the upcoming 0.9.9 release!

**Comment by shawnpreissner** [comment]
Hi, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
