### ISSUE TITLE
Add a note at the top of the landscape regarding CNCF projects

### ISSUE THREAD

**Issue by caniszczyk** [cncf/landscape#1949]
We should add a little yellow caution note near the top

"Note: Not all projects listed on the landscape are formally part of the CNCF. The Cloud Native Landscape is meant to be an exhaustive list of technology across the cloud native ecosystem. To get the full list of CNCF projects, you can visit this part of the landscape: https://landscape.cncf.io/format=card-mode&project=hosted"

**Comment by caniszczyk** [comment]
@AndreyKozlov1984 can you PR a change with this note?

**Comment by tegioz** [comment]
Is this still relevant to landscape2 @caniszczyk?

**Comment by tegioz** [comment]
Will close this one for now, please feel free to reopen if needed 🙂
