### ISSUE TITLE
Portus under Container Registry section should be marked as open source.

### ISSUE THREAD

**Issue by Evalle** [cncf/landscape#197]
Portus should be marked as Open Source

**links:**
Repo: https://github.com/SUSE/Portus
Licence: https://github.com/SUSE/Portus/blob/master/LICENSE

**Comment by shawnpreissner** [comment]
You are right, @Evalle we will make the correction in the upcoming version. Thanks

**Comment by shawnpreissner** [comment]
Closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
