### ISSUE TITLE
Referenced data.json file on https://github.com/cncf/landscape is not returning valid json.

### ISSUE THREAD

**Issue by jselleck** [cncf/landscape#2006]
We rely on the data.json to feed an internal Software Governance tool.   This file seems to be missing.

Reference in docs: https://github.com/cncf/landscape

**Comment by caniszczyk** [comment]
@jordinl83 @AndreyKozlov1984 any thoughts here on this file?

**Comment by jordinl83** [comment]
The file was moved as part of the next.js refactor. The new location is: https://landscape.cncf.io/data/items.json

**Comment by jselleck** [comment]
Got it.  Thanks!  The docs that reference the file need to be updated.  I really appreciate you guys!

**Comment by jordinl83** [comment]
@jselleck Updated readme. Thanks
