### ISSUE TITLE
A new subcategory under Observability and Analysis

### ISSUE THREAD

**Issue by qedrakmar** [cncf/landscape#2009]
We want to discuss a potential new category under Observability and Analysis.  We (StormForge) are currently listed under the Monitoring section, for lack of a better place to go.  The functionality of the platform, though, is much more accurately described as "Performance Testing and Application Optimization", and there is not really an appropriate subcategory under any category for experimenting on your apps and reacting to the results.  

The O&A category feels closest aligned, because this is working on running apps, not working at the build or provision level.  So, I'd like to propose a subcategory named "Performance, Testing, & Optimization", under the Observability and Analysis category, and I believe there are others under the Monitoring umbrella that would also fit better under that heading.

**Comment by caniszczyk** [comment]
I'm open to it, can you outline the new category and who would be there?

**Comment by qedrakmar** [comment]
Okay, it's been a while, but we're getting back to this now.

The biggest defining characteristic of this category would be: products and projects that are focused on analyzing application or infrastructure behavior, then taking an **active** role in tuning various resources for desired outcomes, whether that's availability, performance, infra resilience, cost, or whatever other characteristics are desired.  It's really focused on the reactions being made from the observations being performed.

To that end, I think the originally proposed name is actually a bit misleading (for example, calling out "Testing" originally could easily include test suites, but that doesn't really fit the reactive nature that I think defines this).  So, we'd like to propose simply "Resource Optimization" as the title, with the idea that the resources may not be related to performance/applications/etc, and may be of a scope that we haven't considered yet.

As for who could be in this category, we don't necessarily want to speak for others, but Turbonomic, Replex, and AppNeta are easy fits.  Depending on how they feel about the scale of monitoring vs reactions from that monitoring, CloudHealth could be a good fit as well, and maaaaybe even Cloudwatch, though they seem more focused on the monitoring side.  There's also others who are not on this landscape yet, such as Cast.ai, who would now have a better place to land.

What are your thoughts?

**Comment by caniszczyk** [comment]
see https://github.com/cncf/landscape/pull/3789
