### ISSUE TITLE
Add Icinga to the landscape

### ISSUE THREAD

**Issue by bobapple** [cncf/landscape#201]
**Project or Product name**: Icinga

**Is it open source? (if you are tempted to say partially, please answer no)**: Yes

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**: 
https://www.icinga.com/

**What one category does it best belong in?** 
Observability & Analysis / Monitoring

**What's the URL for the best logo (and it needs to include the name)?**
https://www.icinga.com/wp-content/uploads/2009/05/icinga_logo4.png

**Anything else we need to know?**:

**Comment by shawnpreissner** [comment]
Thanks for following the template, @bobapple , icinga will be included in the upcoming 1.0 version!

**Comment by shawnpreissner** [comment]
Closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
