### ISSUE TITLE
Elastic & Graylog under Logging section should be marked as open source.

### ISSUE THREAD

**Issue by raghu999** [cncf/landscape#202]
Elasticsearch and  graylog under logging should be marked as an opensource logging tools.

Project: https://github.com/elastic/elasticsearch
Licence: https://github.com/elastic/elasticsearch/blob/master/LICENSE.txt

Project: https://github.com/Graylog2/graylog2-server
License: https://github.com/Graylog2/graylog2-server/blob/master/COPYING

**Comment by dankohn** [comment]
We introduced the error in 0.9.8 and will fix shortly. Thanks for bringing it to our attention.

**Comment by SaaldjorMike** [comment]
Since 0.9.9 has been released, I guess this can be closed.

**Comment by dankohn** [comment]
Fixed, closing.
