### ISSUE TITLE
Serverless service for Oracle Cloud Platform

### ISSUE THREAD

**Issue by gfsantamarina** [cncf/landscape#206]
**Project or Product name**:
Oracle Application Container Cloud - Replace the currently shown Oracle Application Express

**Is it open source? (if you are tempted to say partially, please answer no)**:
No

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**:
https://cloud.oracle.com/en_US/application-container-cloud

**What one category does it best belong in?**
Serverless

**What's the URL for the best logo (and it needs to include the name)?**
Includes a name - https://abhirockzz.files.wordpress.com/2016/11/blog-logo.jpg
Original from Oracle - https://docs.oracle.com/en/cloud/paas/app-container-cloud/sp_common/shared-images/cloudgs_appcontainer.png

**Anything else we need to know?**:
I used to work at Oracle selling the Oracle Cloud Platform

**Comment by shawnpreissner** [comment]
Thanks for the heads up @gfsantamarina , this change will be included in the upcoming 1.0 version.

**Comment by shawnpreissner** [comment]
Closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
