### ISSUE TITLE
Request to include LinuxKit

### ISSUE THREAD

**Issue by justincormack** [cncf/landscape#207]
**Project or Product name**:

LinuxKit

**Is it open source? (if you are tempted to say partially, please answer no)**:

Yes.

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**:

https://github.com/linuxkit/linuxkit

**What one category does it best belong in?**

Host Management/Tooling

**What's the URL for the best logo (and it needs to include the name)?**

https://github.com/linuxkit/linuxkit/tree/master/logo
usually use https://github.com/linuxkit/linuxkit/blob/master/logo/linuxkit-blk%403x.svg

**Anything else we need to know?**:

Project has 3400 stars on Github and uses existing CNCF projects eg containerd, notary, and is being used to build Kubernetes distros. It is a much newer more cloud native design than other options in the category. I am planning to do an informational presentation to the toc at some point fairly soon.

**Comment by shawnpreissner** [comment]
Thanks for all the detail @justincormack , love LinuxKit and the community behind it. We will definitely include it in the upcoming 1.0 version!

**Comment by shawnpreissner** [comment]
Closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
