### ISSUE TITLE
Some missing entries

### ISSUE THREAD

**Issue by matt-shaw** [cncf/landscape#208]
Could you add Microsoft Azure Stack in private cloud.
Why is Docker not under container runtime.
Why is Nexus not under container registry.

**Comment by Steiniche** [comment]
Hi matt,

Microsoft Azure  Stack is already listed under cloud and there is only allowed one entry per product.
Containerd is docker which is listed in container runtime, see more here: https://www.cncf.io/announcement/2017/03/29/containerd-joins-cloud-native-computing-foundation/

**Comment by shawnpreissner** [comment]
Thanks for the discussion @matt-shaw and @Steiniche. As mentioned we do have Azure placed in the Cloud category, more widely consumed in a Public Cloud model. Docker is represented by containerd in Runtime, and Sonatype Nexus can be found under Secure Images.
