### ISSUE TITLE
Develop a CNCF landscape guide

### ISSUE THREAD

**Issue by CathPag** [cncf/landscape#2088]
As part of the CNCF Business Value Subcommittee, we'd like to create a CNCF landscape guide that may overlap with some of the goals of the Cartografos group Cheryl Hung is putting together. To ensure we are all in synch, we reached out to Cheryl who suggested raising an issue here.

**Context**: Jason Morgan and I have written a series on the CNCF landscape for The New Stack which we'd like to adapt for the CNCF. Feedback has shown there is a need for it and we believe this type of content should be owned by the CNCF. 

**What we'd like to do:**

- Website (and eBook) with table of content broken down by layer and category so people can easily jump between sections (website is key if the content should be discoverable on Google)

- Repurpose the same content or, more likely, a shorter version of it for interactive elements in the landscape: each layer and category has a clickable element that will open a popup with an explanation of what it is.

We are ready to start putting this together as early as next week. Please advise.

**Comment by oicheryl** [comment]
@CathPag this looks very feasible, but I do recommend you have a chat with Simon and the Cartografos group before starting. Does the meeting tomorrow work for you?

**Comment by CathPag** [comment]
Thanks, @saforster and @oicheryl! Hadn't had a chance to reply yet, but yes, we'll absolutely be there and are looking forward to it. Talk to you tomorrow!

**Comment by caniszczyk** [comment]
https://landscape.cncf.io/guide
