### ISSUE TITLE
Include Project Hatchway by VMware under Cloud Native Storage category.

### ISSUE THREAD

**Issue by tusharnt** [cncf/landscape#209]
**Project or Product name**:
Project Hatchway by VMware

**Is it open source? (if you are tempted to say partially, please answer no)**:
Yes

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**:
Project Hatchway is VMware's open source, enterprise grade, persistent storage & availability platform for cloud native applications.
Project URL -  https://vmware.github.io/hatchway/
Repo for underlying projects 
- vSphere storage for Docker - https://github.com/vmware/docker-volume-vsphere
- vSphere storage for Kubernetes (documentation) - https://github.com/vmware/vsphere-storage-for-kubernetes. Code lives in the official kubernetes repo.

**What one category does it best belong in?**
Cloud native storage

**What's the URL for the best logo (and it needs to include the name)?**
Please use the official vmware logo.

**Comment by shawnpreissner** [comment]
Hi @tusharnt , we are including Project Hatchway in the upcoming version, releasing soon. You probably noticed in the requirements that we request a project logo, especially for companies that are present in many places on the landscape. Please do provide that as soon as possible. Thanks!

**Comment by tusharnt** [comment]
Hi @shawnpreissner, currently we do not have a logo for Project Hatchway. That's why I initially suggested to use official vmware logo. Would that work?

**Comment by shawnpreissner** [comment]
@tusharnt are there plans to create a logo for the project? Please provide once created. Also if considering contributing the project to the CNCF, we do offer such creative services and would love to help. Happy to schedule a call to discuss further, otherwise closing for now as this update was included in the most recent version https://github.com/cncf/landscape#current-version

**Comment by tusharnt** [comment]
Thanks @shawnpreissner for all the help!
We're actively working on getting a logo for the project. I will file a new ticket to update the landscape once our logo is available.
