### ISSUE TITLE
add Diamanti to "Platform" box

### ISSUE THREAD

**Issue by katiecrimi** [cncf/landscape#211]
Diamanti is currently categorized as "Runtime - Cloud-Native Storage"....please update to "Platform - PaaS/Container Service"

**Project or Product name**: Diamanti

**Is it open source? (if you are tempted to say partially, please answer no)**: No

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**: https://diamanti.com/products/

**What one category does it best belong in?** PLATFORM

**What's the URL for the best logo (and it needs to include the name)?** See attached (one currently used is fine however, but incase you need again...)

**Anything else we need to know?**: Please move us from "Runtime/Cloud-Native Storage" to "Platform- PaaS/Container Service" box. 

![web_diamanti_logo](https://user-images.githubusercontent.com/33495412/32567603-9851a3d6-c470-11e7-886f-ee49902d1e18.png)

**Comment by shawnpreissner** [comment]
Hi @katiecrimi , sure thing, we will make the change to Platforms in the upcoming version.

**Comment by shawnpreissner** [comment]
Closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
