### ISSUE TITLE
Add "SUSE CaaS Platform" to "Platforms" box

### ISSUE THREAD

**Issue by cduch** [cncf/landscape#212]
**Project or Product name**:
SUSE CaaS Platform

**Is it open source? (if you are tempted to say partially, please answer no)**:
Yes

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**:
SUSE CaaS Platform for Enterprises is based on the "kubic" project: https://github.com/kubic-project
General product website: https://www.suse.com/products/caas-platform/

**What one category does it best belong in?**
Platforms

**What's the URL for the best logo (and it needs to include the name)?**
![suse_caas_platform](https://user-images.githubusercontent.com/5948137/32596616-37fe60b8-c534-11e7-8682-bd9200a6c4d1.png)
or: https://drive.google.com/open?id=162F3WwNfdclPkli39E0SwSkxpG5nnOYy

**Anything else we need to know?**:
SUSE CaaS Platform is an enterprise class container management solution.
It includes:
- Kubernetes container orchestration technology
- Container engine and image registry
- SUSE MicroOS, a purpose built OS to run containers

**Comment by shawnpreissner** [comment]
Hi @cduch we are including SUSE CaaS Platform in the upcoming version, releasing soon! Thanks

**Comment by shawnpreissner** [comment]
Closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
