### ISSUE TITLE
Request to include Kasten in the CNCF Landscape

### ISSUE THREAD

**Issue by ntolia** [cncf/landscape#214]
**Project or Product name**:

Kasten

**Is it open source? (if you are tempted to say partially, please answer no)**:

No

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**:

https://kasten.io

**What one category does it best belong in?**

Storage

**What's the URL for the best logo (and it needs to include the name)?**

https://drive.google.com/file/d/0B9QNFSAKWcMIcktlVHZ6WDBYdjA/view?usp=sharing is a PNG but please let me know if you prefer SVG or any other format/resolution.

**Anything else we need to know?**:

No, but please ping me for any questions.

**Comment by shawnpreissner** [comment]
Hi @ntolia thanks for creating this ticket, please look for Kasten in the upcoming version! Thanks

**Comment by shawnpreissner** [comment]
Closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
