### ISSUE TITLE
Please add IRONdb to the CCNF landscape

### ISSUE THREAD

**Issue by redhotpenguin** [cncf/landscape#215]
**Please only report on one project or product per issue**

Guidelines for getting added to the CNCF Cloud Native Landscape:

* We generally will only list a company in one box, to represent its major or best known offering. We occasionally make exceptions for large companies.
* Projects with at least 250 GitHub stars that clearly fit in an existing category are generally included.
* We are unlikely to create a new category for products/projects as we'd rather find the best home with the current options.
* We are generally not including commercial versions of open source software, when that version just includes minor tweaks.
* Closed source products need to link to a clear description of your product; no stealth mode companies.
* Your project or company needs a logo.

**Project or Product name**:
IRONdb

**Is it open source? (if you are tempted to say partially, please answer no)**:
No

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**:
[http://irondb.io](http://irondb.io)

**What one category does it best belong in?**
Observability & Analysis : Monitoring

**What's the URL for the best logo (and it needs to include the name)?**
[https://login.circonus.com/resources/docs/irondb/assets/irondb-logo-1777x761.png](https://login.circonus.com/resources/docs/irondb/assets/irondb-logo-1777x761.png)

**Anything else we need to know?**:
I'm the world's biggest IRONdb fan - let me know if there are any questions!

**Comment by shawnpreissner** [comment]
Love the allegiance @redhotpenguin :) IRONdb will be included in the upcoming 1.0 version!

**Comment by shawnpreissner** [comment]
Closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version

**Comment by dankohn** [comment]
IronDB is not open source.

**Comment by dankohn** [comment]
Re-closing.
