### ISSUE TITLE
Update logo/product name: IBM Bluemix is now IBM Cloud

### ISSUE THREAD

**Issue by estesp** [cncf/landscape#216]
IBM Bluemix logo should be replaced per the new IBM Cloud branding announced in the [IBM Cloud blog](https://www.ibm.com/blogs/bluemix/2017/10/bluemix-is-now-ibm-cloud/)

**Official SVG of logo**
[retrievable via this URL](https://login.ng.bluemix.net/UAALoginServerWAR/logo_bluemix_light.svg) *the irony of the URL's hostname is not lost on me* 😄 

If you need a different format let me know.

**Comment by dankohn** [comment]
Will do, thanks. 

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation  https://www.cncf.io
+1-415-233-1000  https://www.dankohn.com

**Comment by shawnpreissner** [comment]
Closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
