### ISSUE TITLE
Update Skywalking APM logo 

### ISSUE THREAD

**Issue by wu-sheng** [cncf/landscape#217]
Skywalking is already in the CNCF landscape 0.9.9 . And we require to update the logo.

Here is the logo:
![68747470733a2f2f736b7977616c6b696e67746573742e6769746875622e696f2f706167652d7265736f75726365732f332e302f736b7977616c6b696e672e706e67](https://user-images.githubusercontent.com/5441976/32988183-39616ee0-ccc4-11e7-9542-7426eaf1685a.png)

And you can find it in here: https://camo.githubusercontent.com/4ac940361b7345156ff71aa21efdb42a449e67d7/68747470733a2f2f736b7977616c6b696e67746573742e6769746875622e696f2f706167652d7265736f75726365732f332e302f736b7977616c6b696e672e706e67

**Comment by shawnpreissner** [comment]
Hi @wu-sheng thanks for the heads up, we will make the change for the upcoming version.

**Comment by shawnpreissner** [comment]
Closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
