### ISSUE TITLE
Add CoScale to Observability & Analysis / Monitoring

### ISSUE THREAD

**Issue by parijs** [cncf/landscape#22]
CoScale provides performance monitoring for container and microservices environments.

See also:
http://www.coscale.com
http://www.coscale.com/docker-monitoring

Logo:
![coscale_logo](https://cloud.githubusercontent.com/assets/17178774/20599703/dcf9efd6-b24f-11e6-8c0f-dad133f62663.png)

**Comment by dankohn** [comment]
+1

**Comment by shawnpreissner** [comment]
Hi @parijs please find in 0.9.4 https://github.com/cncf/landscape/tree/master/landscape
