### ISSUE TITLE
Please add Software AG

### ISSUE THREAD

**Issue by jonathanheywood** [cncf/landscape#221]
**Project or Product name**: 
Software AG Digital Business Platform

**Is it open source? (if you are tempted to say partially, please answer no)**:
 No

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**: 
http://www2.softwareag.com/corporate/products/bis/default.aspx - Products available for cloud deployment as Docker images: https://store.docker.com/publishers/softwareag

**What one category does it best belong in?**
Database & Data Analytics

**What's the URL for the best logo (and it needs to include the name)?**
http://www.softwareag.com/corporate/images/SAG_Logo_RGB_tcm16-134070.jpg

**Anything else we need to know?**:

**Comment by shawnpreissner** [comment]
Hi @jonathanheywood we are including Software AG in the upcoming version, releasing soon! Thanks

**Comment by shawnpreissner** [comment]
Closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
