### ISSUE TITLE
Updated IBM Logos/Placement in CNCF Landscape

### ISSUE THREAD

**Issue by jtborek** [cncf/landscape#222]
Greetings,
Here is the updated IBM logo for placement in the public cloud and platform portion of the CNCF landscape:
![ibmcloud2018](https://user-images.githubusercontent.com/10730496/33621697-4a30e35a-d9b1-11e7-8b7e-ee1732492cb1.png)

**Please only report on one project or product per issue**

Guidelines for getting added to the CNCF Cloud Native Landscape:

* We generally will only list a company in one box, to represent its major or best known offering. We occasionally make exceptions for large companies.
* Projects with at least 250 GitHub stars that clearly fit in an existing category are generally included.
* We are unlikely to create a new category for products/projects as we'd rather find the best home with the current options.
* We are generally not including commercial versions of open source software, when that version just includes minor tweaks.
* Closed source products need to link to a clear description of your product; no stealth mode companies.
* Your project or company needs a logo.

**Project or Product name**:

**Is it open source? (if you are tempted to say partially, please answer no)**:

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**:

**What one category does it best belong in?**

**What's the URL for the best logo (and it needs to include the name)?**

**Anything else we need to know?**:

**Comment by shawnpreissner** [comment]
Thanks @jtborek . Closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
