### ISSUE TITLE
Please add Argo open source project to CNCF Landscape

### ISSUE THREAD

**Issue by mukulikak** [cncf/landscape#223]
**Please only report on one project or product per issue**

Guidelines for getting added to the CNCF Cloud Native Landscape:

* We generally will only list a company in one box, to represent its major or best known offering. We occasionally make exceptions for large companies.
* Projects with at least 250 GitHub stars that clearly fit in an existing category are generally included.
* We are unlikely to create a new category for products/projects as we'd rather find the best home with the current options.
* We are generally not including commercial versions of open source software, when that version just includes minor tweaks.
* Closed source products need to link to a clear description of your product; no stealth mode companies.
* Your project or company needs a logo.

**Project or Product name**: Argo

**Is it open source? (if you are tempted to say partially, please answer no)**:
Yes

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**:

https://github.com/argoproj/argo
https://applatix.com/open-source/argo/

**What one category does it best belong in?**
CI/CD

**What's the URL for the best logo (and it needs to include the name)?**
https://github.com/argoproj/argo/blob/master/Branding%20Assets.md

**Anything else we need to know?**:
Argo is a generic workflow engine which can run any pipeline like CI/CD, image processing workflows, data processing workflows. Since there is no workflow category, closest category we found is CI/CD.

**Comment by ntolia** [comment]
I understand that the README says that "We are unlikely to create a new category for products/projects..." but I would support the creation of a Workflow category as Kasten would be a better fit there too.

**Comment by mukulikak** [comment]
I agree we need a better category like Workflow to list generic workflow engines.

**Comment by dankohn** [comment]
We’ll probably keep you in ci/cd for now though I understand it has other use cases. 

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation  https://www.cncf.io
+1-415-233-1000  https://www.dankohn.com

**Comment by shawnpreissner** [comment]
Hi @mukulikak, love the logo, and we are including Argo in the upcoming version, releasing soon! Thanks

**Comment by shawnpreissner** [comment]
Closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
