### ISSUE TITLE
Please add the logo of ZTE TECS OpenPalette container cloud platform to CNCF Landscape 

### ISSUE THREAD

**Issue by chenxiaofeng2017** [cncf/landscape#224]
**Project or Product name**:
ZTE TECS OpenPalette container cloud platform 

**Is it open source? (if you are tempted to say partially, please answer no)**:
No

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**:
http://sdnfv.zte.com.cn/en/products/126

**What one category does it best belong in?**
Platform

**What's the URL for the best logo (and it needs to include the name)?**
https://github.com/guangxuli/OpenPalette/tree/master/images/logo_tecs_white.jpg

**Anything else we need to know?**:

**Comment by guangxuli** [comment]
hi @shawnpreissner  @dankohn how to proceed this? Feel free to contact @chenxiaofeng2017  thanks. :)

**Comment by chenxiaofeng2017** [comment]
Hello, @@shawnpreissner @dankohn , you can contact us with  @chenxiaofeng2017 @guangxuli  if there are some problems in the this submittion? And how to proceed this?

**Comment by shawnpreissner** [comment]
Hi @chenxiaofeng2017 @guangxuli we had our last release the week of KubeCon + CloudNativeCon and will be reviewing submissions and releasing our January update towards the end of the month. Will reach out if any questions, thanks.

**Comment by guangxuli** [comment]
@shawnpreissner okay, got it, thanks so much.

**Comment by shawnpreissner** [comment]
Hi @chenxiaofeng2017 @guangxuli we are including ZTE TECS OpenPalette in the upcoming version, releasing soon! Thanks

**Comment by shawnpreissner** [comment]
Closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
