### ISSUE TITLE
Consider adding Snap telemetry framework

### ISSUE THREAD

**Issue by andrzej-k** [cncf/landscape#225]
**Project or Product name**: 
Snap

**Is it open source? (if you are tempted to say partially, please answer no)**:
Yes

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**:
https://github.com/intelsdi-x/snap
http://snap-telemetry.io/

**What one category does it best belong in?**
Observability & Analysis - Monitoring 

**What's the URL for the best logo (and it needs to include the name)?**
https://cloud.githubusercontent.com/assets/1744971/20331694/e07e9148-ab5b-11e6-856a-e4e956540077.png

**Anything else we need to know?**:
We have a lots of plugins for data collection, processing and publishing: https://github.com/intelsdi-x/snap/blob/master/docs/PLUGIN_CATALOG.md :)

**Comment by shawnpreissner** [comment]
Hi, we are including Snap in the upcoming version, releasing soon! Thanks

**Comment by shawnpreissner** [comment]
Closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
