### ISSUE TITLE
Adding Cloud 66 project and products to the landscape

### ISSUE THREAD

**Issue by udinachmany** [cncf/landscape#226]
1. We would like to add our open source project Habitus in the CI/CD box
Project name: Habitus
Category: CI/CD
Git: https://github.com/cloud66/habitus
Web: http://www.habitus.io/
Logo: https://cloud66.com/images/habitus-by-cloud66-logo.png
(Habitus is the open core of Skycap, below)

2. We would like to add our commercial product Cloud 66 Skycap, a Continuous Delivery Pipeline built for containers, in CI/CD
Product name: Cloud 66 Skycap
Category: CI/CD
Web: https://cloud66.com/containers/skycap
Logo: https://cloud66.com/images/cloud66-skycap-logo-c.png

3. We would like to replace the generic Cloud 66 logo in Platforms, with our commercial product Cloud 66 Maestro, an application lifecycle management tool built for containers
Product name: Cloud 66 Maestro
Category: Platforms
Web: https://cloud66.com/containers/maestro
Logo: https://cloud66.com/images/cloud66-maestro-logo-c.png

**Comment by shawnpreissner** [comment]
Hi, we are including Habitus, Skycap, and Maestro in the upcoming version, releasing soon! Thanks

**Comment by shawnpreissner** [comment]
Closing as these updates were included in the most recent version https://github.com/cncf/landscape#current-version

**Comment by khash** [comment]
Thank you!
