### ISSUE TITLE
GuardiCore Centra

### ISSUE THREAD

**Issue by IgLiv** [cncf/landscape#227]
GuardiCore Centra:

**Is it open source? (if you are tempted to say partially, please answer no)**: No

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**: https://www.guardicore.com/

**What one category does it best belong in?**
Cloud-Native Network

**What's the URL for the best logo (and it needs to include the name)?**
https://www.guardicore.com/ , we can also provide additional sizes.

**Comment by shawnpreissner** [comment]
Hi, we are including GuardiCore Centra in the upcoming version, releasing soon! Thanks

**Comment by IgLiv** [comment]
Is there anything additional that you need from us?
logos? anything else?

**Comment by IgLiv** [comment]
Also when should we expect the upcoming version to be released?

**Comment by shawnpreissner** [comment]
Nothing further needed, thanks. Closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
