### ISSUE TITLE
Cards do not load correctly 

### ISSUE THREAD

**Issue by phumberdroz** [cncf/landscape#2271]
I am not sure what is causing this: 
<img width="1308" alt="Screenshot 2021-09-07 at 21 58 32" src="https://user-images.githubusercontent.com/3389721/132403514-419b6e99-58b1-4d0c-ab9e-7be0a1e5eab2.png">
I checked the past couple of PR previews they all seemed to be fine. Maybe a redeploy could fix it?

**Comment by caniszczyk** [comment]
cc: @jordinl83 to investigate

**Comment by jordinl83** [comment]
Seems like it was caused by https://github.com/cncf/landscapeapp/pull/770, which has been reverted.
