### ISSUE TITLE
Add "Apache RocketMQ" to "Streaming" box

### ISSUE THREAD

**Issue by zhouxinyu** [cncf/landscape#228]
**Please only report on one project or product per issue**

Guidelines for getting added to the CNCF Cloud Native Landscape:

* We generally will only list a company in one box, to represent its major or best known offering. We occasionally make exceptions for large companies.
* Projects with at least 250 GitHub stars that clearly fit in an existing category are generally included.
* We are unlikely to create a new category for products/projects as we'd rather find the best home with the current options.
* We are generally not including commercial versions of open source software, when that version just includes minor tweaks.
* Closed source products need to link to a clear description of your product; no stealth mode companies.
* Your project or company needs a logo.

**Project or Product name**:
Apache RocketMQ

**Is it open source? (if you are tempted to say partially, please answer no)**:
Yes

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**:
HomePage: https://rocketmq.apache.org/
Repo: https://github.com/apache/rocketmq

**What one category does it best belong in?**
Streaming

**What's the URL for the best logo (and it needs to include the name)?**

![rocketmq](https://user-images.githubusercontent.com/3961183/34104948-7b66350c-e42d-11e7-9424-a23d567cde8c.png)

**Anything else we need to know?**:

Apache RocketMQ is a distributed messaging and streaming platform with low latency, high performance and reliability, trillion-level capacity and flexible scalability.

**Comment by vongosling** [comment]
It has been widely use in asia, especially in China :-) Some users are listed in here, https://rocketmq.apache.org/users/

**Comment by shawnpreissner** [comment]
Hi @zhouxinyu @vongosling thanks for the detail, we are including RocketMQ in the upcoming version, releasing soon! Thanks

**Comment by vongosling** [comment]
@shawnpreissner Thanks :-)
