### ISSUE TITLE
Please include The Fn Project under Serverless/Event-based Category

### ISSUE THREAD

**Issue by carimura** [cncf/landscape#231]
**Please only report on one project or product per issue**

Guidelines for getting added to the CNCF Cloud Native Landscape:

* We generally will only list a company in one box, to represent its major or best known offering. We occasionally make exceptions for large companies.
* Projects with at least 250 GitHub stars that clearly fit in an existing category are generally included.
* We are unlikely to create a new category for products/projects as we'd rather find the best home with the current options.
* We are generally not including commercial versions of open source software, when that version just includes minor tweaks.
* Closed source products need to link to a clear description of your product; no stealth mode companies.
* Your project or company needs a logo.

**Project or Product name**: The Fn Project

**Is it open source? (if you are tempted to say partially, please answer no)**: YES

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**: [https://github.com/fnproject/](https://github.com/fnproject/)

**What one category does it best belong in?**: Serverless/Event-based Category

**What's the URL for the best logo (and it needs to include the name)?**: [https://github.com/fnproject/fnproject.github.io/blob/master/images/logos/fn.png](https://github.com/fnproject/fnproject.github.io/blob/master/images/logos/fn.png)

**Anything else we need to know?**: For more information about the project:
 [https://medium.com/fnproject/8-reasons-why-we-built-the-fn-project-bcfe45c5ae63](https://medium.com/fnproject/8-reasons-why-we-built-the-fn-project-bcfe45c5ae63)

Thank you!
Chad

**Comment by shawnpreissner** [comment]
Hi, we are including fn in the upcoming version, releasing soon! Thanks

**Comment by shawnpreissner** [comment]
Closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
