### ISSUE TITLE
Blue boxes have a bulge

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#233]
The CNCF Project bar slightly goes outside of the blue box everywhere it's used, creating a bulge. Please fix to make proper rectangles.

Also, please don't miss the 5 MB max size on PNGs and use of PNG Compressor: https://github.com/cncf/landscape/issues/230#issuecomment-354158803

**Comment by alexcontini** [comment]
@dankohn I have updated all v1.0 files to remove the bulges on the boxes. I also updated all the CloudNativeLandscape_latest files. 

When I saved as a png from photoshop, it saved as 2.09 MB, so I left the pngs at that size, but let me know if you would like me to make any smaller.

**Comment by dankohn** [comment]
Thanks. My directions should have mentioned this, but next time, I would have preferred to revise it to v1.01.

Also, your PNG is significantly lower res. It is 4800 × 2700 while mine was 7200 x 4050. You can see the difference here: https://github.com/cncf/landscape/commit/2549fce49b4253ee42b7f660306a7f9172dea176#diff-2e2ffbf1422c2dee9aeaa3f4d7cc16e0

Could you please try saving a new PNG at 450 px/in and email it to me before making another commit here. If Photoshop is not giving you control over the resolution, try opening the AI in OS X Preview and exporting it as PNG from there, and then adding PNG Compressor.

**Comment by alexcontini** [comment]
Sounds good! I re-exported and changed the settings from 300dpi to 450dpi
and now the file is 7200 x 4050, and it's now 3.5 MB so that makes sense. I
have attached that new file to this email, let me know if there are any
problems.

Sounds good about making every update as a new file (v1.01), I will do that
next time for sure.

Alex

**Comment by shawnpreissner** [comment]
Closing as this has been resolved in the latest version, and 450 dpi will be the standard moving forward -> https://github.com/cncf/landscape#current-version
