### ISSUE TITLE
Please add Tingyun to Monitoring category. Thanks.

### ISSUE THREAD

**Issue by woodchen** [cncf/landscape#234]
**Please only report on one project or product per issue**

Guidelines for getting added to the CNCF Cloud Native Landscape:

* We generally will only list a company in one box, to represent its major or best known offering. We occasionally make exceptions for large companies.
* Projects with at least 250 GitHub stars that clearly fit in an existing category are generally included.
* We are unlikely to create a new category for products/projects as we'd rather find the best home with the current options.
* We are generally not including commercial versions of open source software, when that version just includes minor tweaks.
* Closed source products need to link to a clear description of your product; no stealth mode companies.
* Your project or company needs a logo.

**Project or Product name**: Tingyun

**Is it open source? (if you are tempted to say partially, please answer no)**: no

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**: http://www.tingyun.com/

**What one category does it best belong in?** Monitoring

**What's the URL for the best logo (and it needs to include the name)?** 
![tingyun-logo-en](https://user-images.githubusercontent.com/2368412/34508718-690675b4-f07d-11e7-83ec-bf1e5290e9ef.png)
PNG Version: http://www.tingyun.com/wp-content/themes/tingyun/images_en/tingyun-logo-en.png
AI Version: http://www.tingyun.com/wp-content/themes/tingyun/images_en/tingyun-logo-en.ai

**Anything else we need to know?**:  

https://www.gartner.com/document/3179418

With a strong emphasis on mobile applications and a hybrid SaaS/on-premises delivery model, Tingyun is a significant indigenous competitor in the Chinese APM market. Tingyun's offering also supports a rich analytics capability, which modifies many online analytical processing (OLAP)-style operations and reporting motifs for the purposes of application performance analytics, particularly with regard to the end-user experience of applications accessed from smartphones and tablets. Given the importance of mobile applications for the Chinese market, Tingyun's current emphasis on the front end rather than the back end makes sense, but the technology will need to become better balanced in its data capture and analysis across the application stack if the offering is to appeal to global markets.

**Comment by shawnpreissner** [comment]
Hi, we are including Tingyun in the upcoming version, releasing soon! Thanks

**Comment by woodchen** [comment]
Thanks.

 

 

---------------------------------------------------------------------------------------------

Wood Chen

TEL: +86-10-84720868-833 | Mobile: +8618611920479 | www.networkbench.com

**Comment by shawnpreissner** [comment]
Closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
