### ISSUE TITLE
Please add Accordion web container platform to CNCF Landscape

### ISSUE THREAD

**Issue by airhigh** [cncf/landscape#235]
Guidelines for getting added to the CNCF Cloud Native Landscape:

* We generally will only list a company in one box, to represent its major or best known offering. We occasionally make exceptions for large companies.
* Projects with at least 250 GitHub stars that clearly fit in an existing category are generally included.
* We are unlikely to create a new category for products/projects as we'd rather find the best home with the current options.
* We are generally not including commercial versions of open source software, when that version just includes minor tweaks.
* Closed source products need to link to a clear description of your product; no stealth mode companies.
* Your project or company needs a logo.

**Project or Product name**:
Accordion web container platform

**Is it open source? (if you are tempted to say partially, please answer no)**:
No

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**:
http://www.mantech.co.kr/product/accordion/?lang=en

**What one category does it best belong in?**
Platforms

**What's the URL for the best logo (and it needs to include the name)?**
http://www.accordions.co.kr/accordion.png

**Anything else we need to know?**:

**Comment by shawnpreissner** [comment]
Hi @airhigh , like the work, however real estate is a current challenge with the Landscape and I'm not seeing the type of requested momentum, today. Keep it up and I'll close for now. Thanks
