### ISSUE TITLE
Add OpenIO to Storage

### ISSUE THREAD

**Issue by GuillaumeDelaporte** [cncf/landscape#237]
**Please only report on one project or product per issue**

Guidelines for getting added to the CNCF Cloud Native Landscape:

* We generally will only list a company in one box, to represent its major or best known offering. We occasionally make exceptions for large companies.
* Projects with at least 250 GitHub stars that clearly fit in an existing category are generally included.
* We are unlikely to create a new category for products/projects as we'd rather find the best home with the current options.
* We are generally not including commercial versions of open source software, when that version just includes minor tweaks.
* Closed source products need to link to a clear description of your product; no stealth mode companies.
* Your project or company needs a logo.

**Project or Product name**:
OpenIO

**Is it open source? (if you are tempted to say partially, please answer no)**:
Yes

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**:
www.openio.io
https://github.com/open-io/oio-sds

**What one category does it best belong in?**
Cloud-Native Storage

**What's the URL for the best logo (and it needs to include the name)?**
http://www.openio.io/wp-content/uploads/2017/02/OIO_LOGO_rgb_red.png

![oio_logo_rgb_red](https://user-images.githubusercontent.com/9073622/34883228-4dccbc16-f7b9-11e7-9a9b-43674ec7bbc5.png)

**Anything else we need to know?**:
OpenIO is an open source object storage and serverless computing software.

**Comment by shawnpreissner** [comment]
Hi, thanks for the detail, we are including OpenIO in the upcoming version, releasing soon! Thanks

**Comment by GuillaumeDelaporte** [comment]
Hey @shawnpreissner, thanks a lot!

**Comment by shawnpreissner** [comment]
Closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
