### ISSUE TITLE
Deadline cutoff for 1.1

### ISSUE THREAD

**Issue by shawnpreissner** [cncf/landscape#239]
Will support all requests prior to this in the upcoming release. The subsequent issues filed will be processed for the next version. Thanks for all of the engagement and stay tuned for 1.1!

**Comment by shawnpreissner** [comment]
1.1 is out -> https://github.com/cncf/landscape#current-version

**Comment by tnir** [comment]
@shawnpreissner Why don't we tag 1.1 against 8d12e84?

**Comment by dankohn** [comment]
Fixed, thanks. And I updated directions: https://github.com/cncf/landscape/blob/master/UPDATE.md
