### ISSUE TITLE
Add Hasura to Platforms - PaaS

### ISSUE THREAD

**Issue by shahidhk** [cncf/landscape#240]
**Project or Product name**:
Hasura

**Is it open source? (if you are tempted to say partially, please answer no)**:
No

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**:
https://hasura.io

**What one category does it best belong in?**:
Platform - PaaS

**What's the URL for the best logo (and it needs to include the name)?**:
https://hasura.io/logo.svg

**Anything else we need to know?**:
Hasura is a CNCF Member

**Comment by dankohn** [comment]
Added: https://landscape.cncf.io/selected=hasura
