### ISSUE TITLE
Questions about the usage of subdomain of OpenYurt Project

### ISSUE THREAD

**Issue by luc99hen** [cncf/landscape#2402]
Hi, guys. I am from [OpenYurt community](https://github.com/openyurtio). 

Recently, we are preparing for a new project **OpenYurt Experience Center** for OpenYurt users.  And we consider that it would be great if the *experience center* could share the same domain name (something like `lab.openyurt.io`) with OpenYurt's current home page site(`openyurt.io`). 

Since the home page domain is managed by CNCF currently, we are wondering if there is a way to allow us to use the subdomain. Thank you in advance!

> I am sorry if this issue is off the topic, but I don't know anywhere else to make this application. Please let me know if there is an official process for this.

**Comment by caniszczyk** [comment]
@luc99hen yes you can use the sub domain, just open a servicedesk ticket if you need help

https://github.com/cncf/servicedesk
