### ISSUE TITLE
Presto

### ISSUE THREAD

**Issue by tomnats** [cncf/landscape#241]
**Please only report on one project or product per issue**

Guidelines for getting added to the CNCF Cloud Native Landscape:

* We generally will only list a company in one box, to represent its major or best known offering. We occasionally make exceptions for large companies.
* Projects with at least 250 GitHub stars that clearly fit in an existing category are generally included.
* We are unlikely to create a new category for products/projects as we'd rather find the best home with the current options.
* We are generally not including commercial versions of open source software, when that version just includes minor tweaks.
* Closed source products need to link to a clear description of your product; no stealth mode companies.
* Your project or company needs a logo.

**Project or Product name**: Presto

**Is it open source? (if you are tempted to say partially, please answer no)**: yes

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**: https://www.starburstdata.com/download/

**What one category does it best belong in?** Database & Data Analytics

**What's the URL for the best logo (and it needs to include the name)?** https://prestodb.io/static/presto-og.png

**Anything else we need to know?**:

**Comment by dankohn** [comment]
Repo is at https://github.com/prestodb/presto

Please provide a high-res version of your logo. We would strongly prefer an SVG, AI, EPS or PSD of an image that is not reversed. See guidelines: https://github.com/cncf/landscape#logos

**Comment by mattsfuller** [comment]
Hello -- You can find the logo here:
https://static1.squarespace.com/static/59e9ddc88a02c760fe0494a1/5a8b1a7bf9619a075299ed19/5a9d7e1808522930f23bc003/1520270875322/Stacked_BW.png

I have the AI format as well, but GitHub will not let me upload it. If AI preferred, let me know your preferred way to get it.

**Comment by dankohn** [comment]
Please zip your AI file and then you can attach it here. Or email me dan at linuxfoundation.org

**Comment by dankohn** [comment]
Reminder that we're waiting for the AI version of the Presto logo.

**Comment by dankohn** [comment]
@alexcontini Please see your email.

**Comment by dankohn** [comment]
Closed with 116b6b4db1aca34850a81429ce64b26174950811
