### ISSUE TITLE
Include OrientDB Database

### ISSUE THREAD

**Issue by dellagustin** [cncf/landscape#242]
**Please only report on one project or product per issue**

Guidelines for getting added to the CNCF Cloud Native Landscape:

* We generally will only list a company in one box, to represent its major or best known offering. We occasionally make exceptions for large companies.
* Projects with at least 250 GitHub stars that clearly fit in an existing category are generally included.
* We are unlikely to create a new category for products/projects as we'd rather find the best home with the current options.
* We are generally not including commercial versions of open source software, when that version just includes minor tweaks.
* Closed source products need to link to a clear description of your product; no stealth mode companies.
* Your project or company needs a logo.

**Project or Product name**: OrientDB

**Is it open source? (if you are tempted to say partially, please answer no)**: Yes (Apache License, Version 2.0)

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**:
Repo: https://github.com/orientechnologies/orientdb
Homepage: http://orientdb.com/orientdb/

**What one category does it best belong in?** - App Definition & Development - Database & Data Analytics

**What's the URL for the best logo (and it needs to include the name)?**:  http://orientdb.com/wp-content/uploads/2017/10/OrientDB_by_CallidusCloud4.png

**Anything else we need to know?**:

**Comment by dankohn** [comment]
Please provide a high res version of your logo. We would strongly prefer an SVG, AI, EPS or PSD of the image from http://orientdb.com/wp-content/uploads/2017/10/OrientDB_by_CallidusCloud4.png

**Comment by lvca** [comment]
Attached. Thanks.

[OrientDB Logo.zip](https://github.com/cncf/landscape/files/1781912/OrientDB.Logo.zip)

**Comment by dankohn** [comment]
@alexcontini Please convert the ai in the zip file.
