### ISSUE TITLE
JPG changed to PNG - consider adding a link

### ISSUE THREAD

**Issue by EQXTFL** [cncf/landscape#243]
https://raw.githubusercontent.com/cncf/landscape/master/landscape/CloudNativeLandscape_latest.jpg
is now
https://raw.githubusercontent.com/cncf/landscape/master/landscape/CloudNativeLandscape_latest.png

Consider adding a link from the jpg version to the new png format, to ensure links will not break.

**Comment by dankohn** [comment]
git doesn't support symbolic links, and I'd rather not serve out a PNG when someone asks for a JPG.

This is the last change in filetypes we plan to make for the foreseeable future, so I'd prefer people just manually adjust.
