### ISSUE TITLE
Create "End User" filter for CNCF members

### ISSUE THREAD

**Issue by taylorwaggoner** [cncf/landscape#2436]
@AndreyKozlov1984 - is it possible to create a filter or landscape view for CNCF end users? My goal is to update [this slide](https://docs.google.com/presentation/d/1UGewu4MMYZobunfKr5sOGXsspcLOH_5XeCLyOHKh9LU/edit#slide=id.gc98d72cd14_1_1409) to have a more landscape-type view of the logos rather than the individual logos pasted in.  I'd like to have all end users sorted alphabetically, not by membership tier.

Thanks!

**Comment by AndreyKozlov1984** [comment]
The filter is not in the user interface, but we support it in an url it is `enduser=yes`


https://landscape.cncf.io/card-mode?enduser=yes&grouping=no

Let me show you what could help you for your slide!

https://landscape.cncf.io/card-mode?enduser=yes&grouping=no&style=borderless&embed=true

https://landscape.cncf.io/card-mode?enduser=yes&grouping=no&style=flat&embed=true

**Comment by taylorwaggoner** [comment]
Thanks, I think I can make this work!
