### ISSUE TITLE
Azure logo update

### ISSUE THREAD

**Issue by karenhchu** [cncf/landscape#244]
Can you please update Azure logo to the new one? Thank you. 
![azure_logolockup_blue](https://user-images.githubusercontent.com/15990693/36123814-be1884ee-1002-11e8-9690-072cf9ab23c6.jpg)

**Comment by dankohn** [comment]
Will do!

**Comment by dankohn** [comment]
Finally updated. Thanks for your patience.

https://github.com/cncf/landscape#current-version and https://landscape.cncf.io/organization=microsoft
