### ISSUE TITLE
Introduce a cloud-native infrastructure category

### ISSUE THREAD

**Issue by fabiand** [cncf/landscape#245]
Certain projects (KubeVirt, gluster-kubernetes, rook (?)) are projects which are cloud native applications which provide additional infrastructure to the cluster. gluster and rook for example provide storage solutions for the cluster.

Thus I wondered if it would make sense to have an _infrastructure_ category where these projects can live.

Now, I think that KubeVirt might not really be adding infrastructure.

**Comment by dankohn** [comment]
Thanks for the suggestion. We take direction on the categories from the TOC, which is planning to spin up a review of the architecture diagram. I'd encourage you to look for an announcement this month on the TOC list and engage there.

**Comment by fabiand** [comment]
Thanks - do you have a list to the right list to watch?

**Comment by dankohn** [comment]
https://github.com/cncf/toc#mailing-list

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com
