### ISSUE TITLE
Consider adding a "Continuous Optimization" section (under Obs)

### ISSUE THREAD

**Issue by caniszczyk** [cncf/landscape#2454]
Here are some companies/projects in the space:

<s>Spot by NetApp</s>
<s>Densify</s>
<s>Turbonomics</s> Moved!!!
<s>Opsani</s>
CloudZero
Granulate
StormForge
BMC Helix
CircleCI (via Vamp)
Zesty
Cast.ai

**Comment by caniszczyk** [comment]
@AndreyKozlov1984 if you have bandwidth can you work on this?

**Comment by AndreyKozlov1984** [comment]
Yes

**Comment by AndreyKozlov1984** [comment]
I'll make it in a separate branch, let me check if these companies are already in the list or I need to add them to the landscape.yml first!

**Comment by AndreyKozlov1984** [comment]
No ideas about subsections, I'll call it "Continious Optimization" too, and I'll readjust other sections a bit

**Comment by caniszczyk** [comment]
SGTM

Let's keep it simple first for review. We may have to move things around as the parent section is getting large

**Comment by AndreyKozlov1984** [comment]
Ok, will update you later today!

**Comment by AndreyKozlov1984** [comment]
https://deploy-preview-2495--landscape.netlify.app/ - a first preview, is this ok? I just added one item (spot.io) for now

![image](https://user-images.githubusercontent.com/230982/155816014-ef726a73-05d2-4a43-b13a-7d8e6d1c9aa3.png)

**Comment by AndreyKozlov1984** [comment]
Added Densify

**Comment by AndreyKozlov1984** [comment]
@caniszczyk Turbonomic is already in observability and analyzes, we can not make duplicates!

**Comment by AndreyKozlov1984** [comment]
Ok, I'll move it to a new place!

**Comment by caniszczyk** [comment]
This exists now!

<img width="239" alt="Screenshot 2024-01-22 at 2 43 35 PM" src="https://github.com/cncf/landscape/assets/63777/104600a9-a9cd-4146-9ff3-45d55214f8d0">
