### ISSUE TITLE
Add AppScale to Serverless Platforms

### ISSUE THREAD

**Issue by NicolasDenutte** [cncf/landscape#246]
**Please only report on one project or product per issue**

Guidelines for getting added to the CNCF Cloud Native Landscape:

* We generally will only list a company in one box, to represent its major or best known offering. We occasionally make exceptions for large companies.
* Projects with at least 250 GitHub stars that clearly fit in an existing category are generally included.
* We are unlikely to create a new category for products/projects as we'd rather find the best home with the current options.
* We are generally not including commercial versions of open source software, when that version just includes minor tweaks.
* Closed source products need to link to a clear description of your product; no stealth mode companies.
* Your project or company needs a logo.

**Project or Product name**:
AppScale
**Is it open source? (if you are tempted to say partially, please answer no)**:
Yes
**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**: [https://github.com/AppScale/appscale](url) & [https://www.appscale.com/](url)

**What one category does it best belong in?**
Platforms > Serverless
**What's the URL for the best logo (and it needs to include the name)?**
[https://www.appscale.com/wp-content/uploads/2018/02/AppScale-Logo1.png](url)
**Anything else we need to know?**:
AppScale is an easy-to-manage serverless platform for building and running scalable web and mobile applications on any infrastructure.

**Comment by dankohn** [comment]
That logo is too small and reversed. Could you please reopen as a pull request and include an SVG, non-reversed version of your logo.
