### ISSUE TITLE
UX / UI Initiative 

### ISSUE THREAD

**Issue by andreuxxxx** [cncf/landscape#2467]
Hello, my name is Andrea Velázquez, UX/UI expert and instructor at George Washington University UX/UI Bootcamps
We are bringing the initiative to optimize the current User Experience and User Interface of the CNCF Landscape. We are aware this is a valuable resource for the community and your collaboration is very important for us.

The scope of this project consists in:

1. UX Research - With your collaboration, we aim to gather findings and meaningful information that we can translate into quantitative and qualitative data. We will create user personas, empathy maps, and other UX deliverables that will be the foundation to lay out a set of solutions to improve the current way to search, navigate and find relevant information on the Landscape.

2. UX Design: With these findings, we will be able to ideate different UI patterns, components, and interactions that aim to improve the current way in which users search, filter, share and understand information on the current CNCF Landscape Website.

3. UX Prototyping and testing: We wish to take our ideation and observations to the next level with the creation of wireframes, user flows, and prototypes that will be tested before they are considered for implementation.

4. UI Design: As a final step, the solutions that prove to be feasible, efficient, and effective will be prototyped in hi-fi and will be presented to the community.

We are looking forward to creating interest in this project and working with the community.

Thank you for your attention

GW Bootcamp UX/UI Team

**Comment by Ciggzy1312** [comment]
Hey @andreuxxxx saw this issue being applied to LFX Mentorship for the upcoming batch
Would love to work on this as a mentee during the mentorship period and the link is not working (if that is supposed to work)
Do point me to some more resources to get started
Thank you :)

**Comment by andreuxxxx** [comment]
Hello! Please disregard the link to the survey, I updated the issue.
Thank you for the interest! I'll post back with more accurate info for potential mentees as soon as possible.

**Comment by octonawish-akcodes** [comment]
Hi, I would like to work on this issue under the LFX mentorship program. @andreuxxxx can you guide me a bit more on the issue and references regarding this issue.

**Comment by Asmit2952** [comment]
Hey, I am interested in working on this issue for LFX Mentorship 2023!

**Comment by nate-double-u** [comment]
Hello everyone, thanks for your interest in this project and the LFX Mentorship program!

You can find information about how to apply to the LFX Mentorship Program in the [cncf/mentoring 01-Mar-May projects](https://github.com/cncf/mentoring/tree/main/lfx-mentorship/2023/01-Mar-May) page and the [CNCF - CNCF Landscape: UX UI improvement](https://mentorship.lfx.linuxfoundation.org/project/df011bb8-8ce1-4092-bfc6-1e92ce40a17d) project page.

This issue is for discussion about what needs to be done and how to do it. Questions about the LFX Mentorship program and how to apply should be directed to the [cncf/mentoring discussion boards](https://github.com/cncf/mentoring/discussions).

**Comment by Rishikavishnoi** [comment]
Hello, I'm interested in working on this issue for the LFX Mentorship 2023 term

**Comment by maheshkasabe** [comment]
Hello @andreuxxxx & @nate-double-u I am really interested in this one, Would love to work on this in the upcoming LFX Term , Kindly tell where can I join the slack channel of this particular issue (project)!

**Comment by akshatvirmani** [comment]
Hi! I am interested in working on this issue under LFX Mentorship!

**Comment by YashKamboj** [comment]
Hey, I am interested in working and contribute to this issue for LFX Mentorship 2023!

**Comment by andreuxxxx** [comment]
Hello everyone, thank you for your interest!

In this stage of the project, we are seeking candidates with a background and/or training in user research. Supporting materials, such as the following recommended deliverables, that demonstrate your understanding and experience in this area are a plus:

1. Proto-Personas
2. Validated Personas with Supporting Findings
3. Brief Explanation of the Difference between Proto-Personas and Validated Personas
4. List of UX Research Techniques for Kickstarting the Discovery of Landscape Users

Thank you!

**Comment by ConnectBhawna** [comment]
Hi @andreuxxxx , I am interested in learning about this project and want to work on this project under LFX Mentorship.
Please let me know about any materials or resources that I should learn to get a better understanding of the project and its requirements.

Additionally, I was wondering if there is anything else I can do to get started, such as research and learn about the project from the existing documentation.

**Comment by andreuxxxx** [comment]
> Hi @andreuxxxx , I am interested in learning about this project and want to work on this project under LFX Mentorship. Please let me know about any materials or resources that I should learn to get a better understanding of the project and its requirements.
> 
> Additionally, I was wondering if there is anything else I can do to get started, such as research and learn about the project from the existing documentation.

You can find information about how to apply to the LFX Mentorship Program in the [cncf/mentoring 01-Mar-May projects](https://github.com/cncf/mentoring/tree/main/lfx-mentorship/2023/01-Mar-May) page and the [CNCF - CNCF Landscape: UX UI improvement](https://mentorship.lfx.linuxfoundation.org/project/df011bb8-8ce1-4092-bfc6-1e92ce40a17d) project page.

**Comment by YashPimple** [comment]
Hello, @andreuxxxx upon observing the application of this issue within LFX Mentorship for the upcoming batch, I am highly interested in acquiring knowledge about this project and I am eager to work with LFX Mentorship. 

I would greatly appreciate your professional guidance in identifying any relevant resources or materials that can enhance my understanding of the project.

**Comment by nate-double-u** [comment]
Project management board:
https://github.com/orgs/cncf/projects/23/views/1

**Comment by maityamit** [comment]
Hey, I am interested in working on this issue for LFX Mentorship 2023!

**Comment by mastersans** [comment]
Hey there!

I am Sanskar Sharma, a front-end developer who is passionate about contributing to open source projects. Although I am new to this field, I am eager to learn and improve. I am particularly interested in contributing to the landscape and working on UI/UX improvements as part of the LFX mentorship program term 2.

**Comment by Neilblaze** [comment]
Hello @andreuxxxx 👋🏼 , I am interested in working on this issue for LFX Mentorship 2023! I'd like to know more about the specifications & deliverables in sharp.

**Comment by sanya031** [comment]
Hello @andreuxxxx @Hilzygift I am interested in this project and have submitted my application for the upcoming term of lfx (june-august 2023) and I wanted to know if I can start helping on the project issues. Is there a discord or slack channel I should be joining ? 

Thanks 
Sanya

**Comment by tegioz** [comment]
Thanks @andreuxxxx!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io), so I'll close this one for now.

Please feel free to reopen if needed 🙂
