### ISSUE TITLE
Hide the headcount, funding and HQ for CNCF projects

### ISSUE THREAD

**Issue by lizrice** [cncf/landscape#2477]
The CNCF-owned projects all show that they are HQ'd in San Francisco, have $3M of funding and a headcount of 11-50. Maybe it makes some sense to show this kind of information when it's a vendor project, but it doesn't make sense for the ones the CNCF owns! Could we hide those fields in that case? 
<img width="1671" alt="Screenshot 2022-02-16 at 18 32 34" src="https://user-images.githubusercontent.com/458616/154333736-43f26e2c-eca8-4a22-a668-2a97f67f8f1c.png">

<img width="1669" alt="Screenshot 2022-02-16 at 18 32 51" src="https://user-images.githubusercontent.com/458616/154333716-b23b8770-3acc-453e-89b3-510972fe1ca2.png">

**Comment by tegioz** [comment]
Hi @lizrice 👋

Landscape v2 shows this information a bit differently, making it a bit clearer that it corresponds to the CNCF organization and not to the project. Do you think this is still a problem?

<img width="1682" alt="etcd" src="https://github.com/cncf/landscape/assets/1213902/b5838a90-2c6a-4467-bfcf-5d5f28d9d4b1">

**Comment by lizrice** [comment]
That makes more sense now, thanks @tegioz!
