### ISSUE TITLE
License detection broken for KICS

### ISSUE THREAD

**Issue by caniszczyk** [cncf/landscape#2487]
For some reason https://github.com/cncf/landscape/pull/2486 the license appears to not be detected properly.

Is this some type of caching issue?

@AndreyKozlov1984

**Comment by rafaela-soares** [comment]
Hello again, @caniszczyk 🙂 

For some reason, it did not work in the preview. However, it is working https://landscape.cncf.io/?grouping=category&selected=kics.

**Comment by AndreyKozlov1984** [comment]
I'll check what is wrong, I've noticed some flashing when a certain card is open.

**Comment by Arijit1000** [comment]
Yes, I also noticed the flashing issue while opening the card. Any idea how to solve this?

**Comment by AndreyKozlov1984** [comment]
I am pretty sure that had been fixed, please check again.
Or attach a video / steps how to reproduce the issue.

**Comment by Arijit1000** [comment]
@AndreyKozlov1984 Yes, it is fixed now. The flashing issue doesn't pop up now.
