### ISSUE TITLE
Fn Project is open source -- needs white box

### ISSUE THREAD

**Issue by carimura** [cncf/landscape#249]
Per issue #231, Fn is 100% open source and should be white. Can this be fixed in the next version of the landscape?

Also it should be "Hybrid" in the Platforms section of the Serverless Landscape. 

Thank you.

**Please only report on one project or product per issue**

Guidelines for getting added to the CNCF Cloud Native Landscape:

* We generally will only list a company in one box, to represent its major or best known offering. We occasionally make exceptions for large companies.
* Projects with at least 250 GitHub stars that clearly fit in an existing category are generally included.
* We are unlikely to create a new category for products/projects as we'd rather find the best home with the current options.
* We are generally not including commercial versions of open source software, when that version just includes minor tweaks.
* Closed source products need to link to a clear description of your product; no stealth mode companies.
* Your project or company needs a logo.

**Project or Product name**:

**Is it open source? (if you are tempted to say partially, please answer no)**:

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**:

**What one category does it best belong in?**

**What's the URL for the best logo (and it needs to include the name)?**

**Anything else we need to know?**:

**Comment by dankohn** [comment]
Yes, we'll fix both for next version. Sorry about the error.

**Comment by dankohn** [comment]
This has been fixed, thanks: https://landscape.cncf.io/selected=fn
https://github.com/cncf/landscape#serverless
