### ISSUE TITLE
Include PCF CredHub in Key Management Section

### ISSUE THREAD

**Issue by joshpadilla** [cncf/landscape#251]
**Please only report on one project or product per issue**

Guidelines for getting added to the CNCF Cloud Native Landscape:

* We generally will only list a company in one box, to represent its major or best known offering. We occasionally make exceptions for large companies.
* Projects with at least 250 GitHub stars that clearly fit in an existing category are generally included.
* We are unlikely to create a new category for products/projects as we'd rather find the best home with the current options.
* We are generally not including commercial versions of open source software, when that version just includes minor tweaks.
* Closed source products need to link to a clear description of your product; no stealth mode companies.
* Your project or company needs a logo.

**Project or Product name**:

**Is it open source? (if you are tempted to say partially, please answer no)**:

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**:

**What one category does it best belong in?**

**What's the URL for the best logo (and it needs to include the name)?**

**Anything else we need to know?**:

PCF CredHub
1) https://docs.cloudfoundry.org/credhub/
2) http://docs.pivotal.io/tiledev/2-0/credhub.html
3) https://github.com/cloudfoundry-incubator/credhub

PCF CredHub has Apache 2.0 License
1) https://github.com/cloudfoundry-incubator/credhub/blob/master/LICENSE

**Comment by dankohn** [comment]
This looks like a promising project but we'd like to see it get a little more traction first. Please reopen when it exceeds 250 stars and graduates from the incubator.

**Comment by joshpadilla** [comment]
I'm surprised, as I've seen quite a few other examples such as Apache Brooklyn that have well under 250 stars but have been included. Couple that with the fact that key management does not have a lot of choices currently, I would think the category would be ripe for expansion.

Let's compare a few other factors:
CredHub:
 1,728 commits
 10 branches
 31 contributors

Apache Brooklyn:
 138 commits
 11 branches
 21 contributors

Stars can be a pretty hit or miss category for a gauge of popularity or importance. Mostly b/c for every 100 people interested in a GitHub project, very few of them will take the effort to hit the star button. It's not a very optimal system.

**Comment by dankohn** [comment]
I totally agree that stars are a problematic indicator. However, note that that isn't actually the main Brooklyn repo. Apache projects are hosted on Apache and this is just a mirror, so we give them a little more slack. In addition, the tiny number of commits is because all the work has occurred in the subtrees.
