### ISSUE TITLE
Landscape oversimplifies Serverless..

### ISSUE THREAD

**Issue by antstanley** [cncf/landscape#252]
RE: Serverless Landscape Diagram.

The landscape diagram equates Serverless to FaaS. The reality is that there is that serverless encompasses a far broader landscape than just FaaS platforms.

The platforms sections is dominated by FaaS implementations, but then includes PubNub, and no other pubsub platforms or services (ie Google PubSub, Azure Event Grid, or AWS SNS). This diagram is misleading.

Would recommend removing the platform section and replacing by services categories, ie FaaS, DBaaS, Pubsub, Object storage, Authentication, GraphQL, Search etc...

**Comment by dankohn** [comment]
I would encourage you to read the CNCF Serverless WG white paper and then engage with that group. We're taking feedback from them on how best to structure the serverless category.

https://github.com/cncf/wg-serverless
https://github.com/cncf/wg-serverless#whitepaper
