### ISSUE TITLE
Suggestion to add Databend logo

### ISSUE THREAD

**Issue by wubx** [cncf/landscape#2520]
Databend is a Cloud-native Warehouse, which is inspired by the design of Clickhouse & Snowflake.
Github Repo: https://github.com/datafuselabs/databend
Logo: https://raw.githubusercontent.com/datafuselabs/databend/main/website/static/img/logo/databend-logo-vertical.svg
For more details, please check https://databend.rs/  and https://weekly.databend.rs

**Comment by donaldliu** [comment]
(Databend) can refer to https://github.com/cncf/landscape#new-entries.

**Comment by wubx** [comment]
https://github.com/cncf/landscape/pull/2721
