### ISSUE TITLE
Include StdLib in Serverless Platforms

### ISSUE THREAD

**Issue by keithwhor** [cncf/landscape#253]
**Project or Product name**: StdLib

**Is it open source? (if you are tempted to say partially, please answer no)**: No (Partially)

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**:
https://github.com/stdlib/lib/
https://stdlib.com/

**What one category does it best belong in?**
Serverless Platforms

**What's the URL for the best logo (and it needs to include the name)?**
https://stdlib.com/static/images/stdlib-logo-wordmark-128.png

**Anything else we need to know?**:
Nope. :)

**Comment by keithwhor** [comment]
Oops! I see it there. It's small. It wasn't listed in the whitepaper, which is why Chris recommended me in this direction.

Suggestion for inclusion of FaaSlang as a FaaS toolset, though it's more tightly coupled to FaaS API design:
https://github.com/faaslang/faaslang

**Comment by dankohn** [comment]
Closing as complete: https://landscape.cncf.io/selected=std-lib
