### ISSUE TITLE
Add YugaByte DB to the Database and Data Analytics section

### ISSUE THREAD

**Issue by schoudhury** [cncf/landscape#254]
**Please only report on one project or product per issue**

Guidelines for getting added to the CNCF Cloud Native Landscape:

* We generally will only list a company in one box, to represent its major or best known offering. We occasionally make exceptions for large companies.
* Projects with at least 250 GitHub stars that clearly fit in an existing category are generally included.
* We are unlikely to create a new category for products/projects as we'd rather find the best home with the current options.
* We are generally not including commercial versions of open source software, when that version just includes minor tweaks.
* Closed source products need to link to a clear description of your product; no stealth mode companies.
* Your project or company needs a logo.

**Project or Product name**:

YugaByte DB

**Is it open source? (if you are tempted to say partially, please answer no)**:

Yes, distributed under Apache 2.0

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**:

https://github.com/YugaByte/yugabyte-db
https://www.yugabyte.com/product/

**What one category does it best belong in?**

 Database and Data Analytics

**What's the URL for the best logo (and it needs to include the name)?**

https://s3-us-west-2.amazonaws.com/assets.yugabyte.com/yugabyte_logo_for_cncf_landscape.ai
https://s3-us-west-2.amazonaws.com/assets.yugabyte.com/yugabyte_logo_for_cncf_landscape.png

**Anything else we need to know?**:
See YugaByte DB in action on Kubernetes: https://docs.yugabyte.com/quick-start/install/#kubernetes

**Comment by dankohn** [comment]
@alexcontini Please convert page 2 of https://s3-us-west-2.amazonaws.com/assets.yugabyte.com/yugabyte_logo_for_cncf_landscape.ai into an SVG.

**Comment by alexcontini** [comment]
@dankohn the zipped svg is attached

[yugabyte.svg.zip](https://github.com/cncf/landscape/files/1803206/yugabyte.svg.zip)

**Comment by dankohn** [comment]
Closed with https://github.com/cncf/landscape/commit/86b7ebcc39c149561581fe91db091fffb3e4ee0a
