### ISSUE TITLE
add project riff to landscape

### ISSUE THREAD

**Issue by jldec** [cncf/landscape#255]
**Please only report on one project or product per issue**

Guidelines for getting added to the CNCF Cloud Native Landscape:

* We generally will only list a company in one box, to represent its major or best known offering. We occasionally make exceptions for large companies.
* Projects with at least 250 GitHub stars that clearly fit in an existing category are generally included.
* We are unlikely to create a new category for products/projects as we'd rather find the best home with the current options.
* We are generally not including commercial versions of open source software, when that version just includes minor tweaks.
* Closed source products need to link to a clear description of your product; no stealth mode companies.
* Your project or company needs a logo.

**Project or Product name**:
riff

**Is it open source? (if you are tempted to say partially, please answer no)**:
yes

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**:
https://github.com/projectriff/riff
https://projectriff.io/
https://twitter.com/projectriff

**What one category does it best belong in?**
Serverless/Event-based Platforms

**What's the URL for the best logo (and it needs to include the name)?**
https://projectriff.io/images/pvlg-riff-fullcolor.eps
https://projectriff.io/images/riff.png

**Anything else we need to know?**:
I recommend https://projectriff.io/video/mark-fisher-at-springone-platform-2017/ for a quick intro.
The riff project originated out of the OSS Spring team but is not Java-specific.

**Comment by dankohn** [comment]
I added you as a Pivotal project but please feel free to create a new Project Riff org on Crunchbase and open a PR to change to that, if you want.

https://landscape.cncf.io/selected=riff
05ff4c57cad2f856fae47f695237899384780730
