### ISSUE TITLE
New QR codes

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#256]
Please create new QR codes that include the Readme in the url, as it’s necessary to display the image in Github’s mobile version:

https://github.com/cncf/landscape/blob/master/README.md#current-version

https://github.com/cncf/landscape/blob/master/README.md#serverless

And one for:
https://landscape.cncf.io

**Comment by tnir** [comment]
@dankohn Interactive Landscape 🎉 

Didn't the filterable edition go public yet? I can't have access to https://github.com/cncf/filterable-landscape to file an issue about it.

**Comment by dankohn** [comment]
It will be public soon.
