### ISSUE TITLE
Viewing and analysing historical data

### ISSUE THREAD

**Issue by xmulligan** [cncf/landscape#2570]
I would like to trace the growth of the cloud native landscape. Is it possible to get snapshots of the landscape at various points to pull the data over time?

**Comment by Arijit1000** [comment]
We can make a separate section for tracing the growth of the cloud-native landscape.

**Comment by AndreyKozlov1984** [comment]
Hi, absolutely all data is stored in this repository, and it is updated daily by a CNCF-Bot !

**Comment by Arijit1000** [comment]
Great!

**Comment by xmulligan** [comment]
Thanks!
