### ISSUE TITLE
Tighten spacing around summary

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#258]
From filterable-landscape created by [dankohn](https://github.com/dankohn) : cncf/filterable-landscape#281  

Please make the summary text a grey color (so it's less emphatic than the title but more than the text below the title). Make it just a little larger than the headers. Remove the extra space below it.

<img width="1063" alt="screen shot 2018-02-19 at 5 20 02 pm" src="https://user-images.githubusercontent.com/3083270/36399335-6abfa9f2-1599-11e8-8f0f-f881cf17bf0f.png">

**Comment by alexkontsevoy** [comment]
@dankohn 

It looks like this now

![image](https://user-images.githubusercontent.com/4476098/36900293-ea23938c-1e4c-11e8-809b-dc7f0c39ac45.png)

The changes are merged, so I guess we can close this issue?

**Comment by dankohn** [comment]
You're right, it's fixed.
