### ISSUE TITLE
More dramatic logging

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#263]
From filterable-landscape created by [dankohn](https://github.com/dankohn) : cncf/filterable-landscape#306  

Please add ‘FATAL ERROR:’ in front of fatal errors to make them easier to find in the logs. In this case, the issue is missing image data for Harbor:  https://app.netlify.com/sites/interactive-landscape/deploys/5a91cfcda6188f5d187824d0

**Comment by ZeusTheTrueGod** [comment]
Ok, I tried to add colors, but this helps only locally, when deployed to netlify, colors are ignored
