### ISSUE TITLE
Powershell Desired State Configuration

### ISSUE THREAD

**Issue by Outek** [cncf/landscape#264]
Is DSC worth an entry?

**Project or Product name**:
Desired State Configuration

**Is it open source? (if you are tempted to say partially, please answer no)**:
Partially, so no. But there is a announcement, the future release will be.

**What are the best URL(s) for it? Repo and homepage (if different) for open source, product homepage for closed source?**:
https://github.com/PowerShell/DscResources

**What one category does it best belong in?**
Tooling

**What's the URL for the best logo (and it needs to include the name)?**
https://upload.wikimedia.org/wikipedia/commons/2/2f/PowerShell_5.0_icon.png

**Anything else we need to know?**:

**Comment by dankohn** [comment]
Please reopen as a pull request and include an SVG that says `PowerShell DSC` beneath the logo.
