### ISSUE TITLE
`with` and `without` link is invalid and broken in README.md

### ISSUE THREAD

**Issue by bishal7679** [cncf/landscape#2655]
1. `with` and `without` link is invalid and broken in README.md

![Screenshot (185)](https://user-images.githubusercontent.com/70086051/178225551-c0c87d28-37e9-4b46-a75f-e42919322860.png)

![Screenshot (184)](https://user-images.githubusercontent.com/70086051/178224255-2ec049d0-2f79-4d69-a758-506c96f33376.png)

2. The file path  src/components/MainContent2.js looks not so readable

![Screenshot (186)](https://user-images.githubusercontent.com/70086051/178224900-c96be69e-1a73-4412-b4d6-b180adf9f87b.png)

It would be better if 

![Screenshot (183)](https://user-images.githubusercontent.com/70086051/178225208-90fb6be9-0e2d-4ee6-ae25-328491f78256.png)

**Comment by bishal7679** [comment]
@caniszczyk Can I work on this issue??

**Comment by caniszczyk** [comment]
sure but keep @AndreyKozlov1984 in the loop

**Comment by bishal7679** [comment]
@caniszczyk you mean I will ping @AndreyKozlov1984 for the next time?

**Comment by abhijeetgauravm** [comment]
I would like to work on this issue!

**Comment by tegioz** [comment]
Hi!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io) and this issue probably no longer applies.

Please feel free to reopen if needed 🙂
