### ISSUE TITLE
the landscape appears not updated

### ISSUE THREAD

**Issue by donaldliu** [cncf/landscape#2687]
Some members have updates their entries on Crunchbase but the landscape appears not able to reflect the changes.

Taken a look at https://github.com/cncf/landscape:
===
processed_landscape.yml
Automated update by CNCF-bot
6 days ago
===

This file was updated 6 days ago (was automatically updated daily before) … wondering if it is the reason.

**Comment by caniszczyk** [comment]
@AndreyKozlov1984 can you investigate?

**Comment by donaldliu** [comment]
a friendly ping.

**Comment by AndreyKozlov1984** [comment]
Checking why automatic update failed.

**Comment by AndreyKozlov1984** [comment]
`FATAL: no headquarter addresses for infracost at https://www.crunchbase.com/organization/infracost`

 Someone needs to update the crunchbase entry 
@taylorwaggoner  or @caniszczyk  can you do it ?

**Comment by taylorwaggoner** [comment]
@AndreyKozlov1984 I added a HQ to their Crunchbase, thanks

**Comment by AndreyKozlov1984** [comment]
I am checking if this helps, so far that looks like the only blocking issue

**Comment by donaldliu** [comment]
Thx.
