### ISSUE TITLE
Confusing information of Tetragon in cncf.io/projects

### ISSUE THREAD

**Issue by kevin-wangzefeng** [cncf/landscape#2694]
It appears that Tetragon listed in cncf.io/projects as an incubating project[1] and with description "Tetragon was accepted to CNCF on October 13, 2021 and is at the Incubating project maturity level."[2]

Tetragon was launched in May, 2022[3], as a subproject[4] of Cilium and didn't go through CNCF project donation/accpetance process.

AFAIK, subprojects don't listed in the cncf.io/projects list. Am I missing anything?

Ref: 
[1] https://www.cncf.io/projects/#incubating
[2] https://www.cncf.io/projects/tetragon/
[3] https://isovalent.com/blog/post/2022-05-16-tetragon/
[4] https://github.com/cilium/tetragon

**Comment by tegioz** [comment]
Hi @kevin-wangzefeng 👋 

This was done in #2734 for landscape v1.

In landscape v2, subprojects are not displayed when filtering by CNCF projects either. When displaying the details of a subproject, we show the parent project though.

<img width="1680" alt="subproject" src="https://github.com/cncf/landscape/assets/1213902/3fe779bb-0e15-4347-b746-fa65f9aa4566">
