### ISSUE TITLE
Category for Encryption/Secrets Management

### ISSUE THREAD

**Issue by JJediny** [cncf/landscape#27]
A key need *(pun intended)* of managing everything-as-code is injecting variables at runtime, these tools don't seem to be accounted within the landscape?
https://www.vaultproject.io/
https://square.github.io/keywhiz/
https://www.gnupg.org/

etc...
ansible/chef vault
https://aws.amazon.com/kms/
https://keybase.io

**Comment by moderation** [comment]
https://lyft.github.io/confidant/

**Comment by shawnpreissner** [comment]
Hi @JJediny, leaving this open as we're considering it for a future release

**Comment by shawnpreissner** [comment]
Thanks @JJediny, closing as this new category update was included in the most recent version https://github.com/cncf/landscape#current-version
