### ISSUE TITLE
Allow for duplicate entries, or at least duplicate repo_names

### ISSUE THREAD

**Issue by cartermp** [cncf/landscape#2707]
(filing issue here since there's no clear path to take in a PR)

OpenTelemetry is currently classified as tracing. However, as a project it spans three signal types so far (tracing, metrics, and logs --> which is tracing, monitoring, and logging in the landscape, respectively) with more in the pipeline.

However, there's no good way to represent that a project spans categories so far. The idea I had was to just duplicate OpenTelemetry in each relevant subcategory, but the build doesn't allow duplicate names or repository names. I _could_ work around that by just pointing at some other opentelemetry repos, but I'd rather open an issue here to see if there's a preferred way to handle this before I go and do something kinda hacky.

**Comment by tegioz** [comment]
Hi @cartermp 👋 

Monitoring, logging and tracing subcategories [have been recently merged into a new one named observability](https://github.com/cncf/landscape/pull/3789), which includes OpenTelemetry. I saw [you agreed with the change](https://github.com/cncf/landscape/pull/3789#issuecomment-1984548491) as well 😉

Will close this issue for now, please feel free to reopen if needed.
