### ISSUE TITLE
Shrink SVGs

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#271]
From filterable-landscape created by [dankohn](https://github.com/dankohn) : cncf/filterable-landscape#334  

Shrink SVGs that are bigger than 100 kB. Recall that the Zookeeper logo is available as PSD: https://svn.apache.org/repos/asf/zookeeper/logo/

```sh
$ ls -lS cached_logos/
total 17112
-rw-r--r--@ 1 dan  staff   662K Feb 27 09:08 apache-zookeeper.svg
-rw-r--r--@ 1 dan  staff   368K Feb 27 09:08 clay.svg
-rw-r--r--@ 1 dan  staff   240K Feb 27 09:08 sheepdog.svg
-rw-r--r--@ 1 dan  staff   194K Feb 27 09:08 infrakit.svg
-rw-r--r--@ 1 dan  staff   139K Feb 27 09:08 snap-route.svg
```

**Comment by dankohn** [comment]
Please autotrace this Clay logo: https://github.com/clay-run/clay-cli

For Snaproute, if autotracing doesn't work well, you can add some padding on the top and bottom to give this the minimum 360ox height: https://microsoftventures.com/wp-content/uploads/2017/02/snaproute-1.png

**Comment by alexkontsevoy** [comment]
@dankohn this duplicates #396

**Comment by dankohn** [comment]
Closing as duplicate of #396
