### ISSUE TITLE
Open PRs with projects to set license info in a standard way

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#272]
From filterable-landscape created by [dankohn](https://github.com/dankohn) : cncf/filterable-landscape#314  

https://landscape.cncf.io/grouping=no&license=unknown-license

Create or edit LICENSE file.

**Comment by eirinikos** [comment]
I'm putting together a detailed summary of where this issue currently stands.

In short...
- 35 projects currently remain in ["unknown license" view](https://landscape.cncf.io/license=unknown-license)

Of these 35 projects...
- 2 projects were placed on hold
- 12 projects were left as-is*
- 11 projects have open PRs/bugs/issues
- 10 projects have not been touched **

* they are multi-licensed, or they bear licenses that aren’t recognized by Licensee
** they have been researched or discussed, but they don’t have any open PRs/bugs/issues

**Comment by dankohn** [comment]
I also want the list of how many you did change, and to what.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by eirinikos** [comment]
Got it. Here's the full [Google doc](https://docs.google.com/document/d/16Xu6TBgXRc3t3ERCTW_V3RF3JeD-xGTbkV6hD3kpzZg/edit?usp=sharing).

An updated count...

- 36 projects currently remain in "unknown license" view

Of these 36 projects...

- 1 project was added on 6/12/18
- 2 projects were placed on hold
- 11 projects have open PRs/bugs/issues
- 14 projects were left as-is*
- 8 projects have not been started**

\* they are multi-licensed, or they bear licenses that aren’t recognized by Licensee
** they have been researched or discussed, but they don’t have any open PRs/bugs/issues
