### ISSUE TITLE
Link broken in Cloud Native Landscape README.md

### ISSUE THREAD

**Issue by ADITYADAS1999** [cncf/landscape#2732]
Link broken in Cloud Native Landscape README.md, Non-Updated Items section

https://landscape.cncf.io/category=provisioning,runtime,orchestration-management,app-definition-and-development,paa-s-container-service,serverless&format=card-mode&grouping=no&license=open-source&sort=latest-commit

https://landscape.cncf.io/category=provisioning,runtime,orchestration-management,app-definition-and-development,paa-s-container-service,serverless,observability-and-analysis&format=card-mode&grouping=no&license=not-open-source&sort=latest-tweet

![0021](https://user-images.githubusercontent.com/58718316/188696361-9b914d6a-02fe-4690-918a-cddfd1ed8c88.PNG)

![054126](https://user-images.githubusercontent.com/58718316/188696413-28de6d22-409e-4a7e-b08e-70d68f99a809.PNG)

**Comment by SUGARXUST** [comment]
Hey @ADITYADAS1999 I looked into it can you please confirm if this is what you were looking for? I'll make a PR henceforth.

https://landscape.cncf.io/card-mode?category=provisioning,runtime,orchestration-management,app-definition-and-development,paa-s-container-service,serverless,observability-and-analysis,runtime,installable-platform&license=open-source&grouping=no&sort=latest-commit

https://landscape.cncf.io/card-mode?category=provisioning,runtime,orchestration-management,app-definition-and-development,paa-s-container-service,serverless,observability-and-analysis&license=not-open-source&grouping=no&sort=latest-tweet

**Comment by ADITYADAS1999** [comment]
Butter be discuss the issue on slack or group before make a PR

**Comment by SUGARXUST** [comment]
Can you share the link for the slack group?
