### ISSUE TITLE
Subprojects need an indicator in the landscape

### ISSUE THREAD

**Issue by amye** [cncf/landscape#2734]
See #2694, there's probably lots more out here.

We need a `project: subproject` and likely `project parent: project` indicator because right now, several subprojects of projects are getting added to the project pages. 
We need a way to filter these out and make it less confusing for everyone.

**Comment by amye** [comment]
Tagging @AndreyKozlov1984 to look into, I know this is a problem we're going to continue to have 😂

**Comment by AndreyKozlov1984** [comment]
Can you provide a bit more details with examples and screenshots so I can get this done ?

**Comment by amye** [comment]
> Can you provide a bit more details with examples and screenshots so I can get this done ?

I mean, #2694 as referenced describes the problem. 
Projects are adding 'incubating' to their listing, even though they're sandbox projects.

**Comment by cjyabraham** [comment]
Any updates on this one @AndreyKozlov1984 ?

**Comment by AndreyKozlov1984** [comment]
I don't think this task is completely clear to me, which cards are rendered improperly ?

**Comment by cjyabraham** [comment]
There are certain projects that are listed on landscape that are actually _subprojects_ of another project. Subprojects need to be specified as such in landscape.yml.

Sounds like @amye suggests having the value `project: subproject` for a subproject and a separate attribute of `project parent: parent project name`. Does that make sense?

Once subprojects are labeled this way then I will be able to skip importing them into the CNCF site.

@amye should these subprojects be omitted from [this listing](https://landscape.cncf.io/card-mode)?

**Comment by AndreyKozlov1984** [comment]
Ok, I need to check how subprojects are implemented, we already have `extra` attributes where we can specify this property
@amye and @cjyabraham can we use `extra` attributes here, like `extra: { parent: 'Kubernetes' }` to show that we have a parent?

**Comment by cjyabraham** [comment]
Seems fine from my POV but I don't really know what the pros/cons are with having it in the `extra` attribute.

**Comment by amye** [comment]
It is definitely an 'extra' because it's so rare!

**Comment by AndreyKozlov1984** [comment]
so you can use `parent_project: Kubernetes` inside the `extra` and this will be displayed for the selected item automatically, and if you want to fetch api data - you'll be able to skip all items which have `extra: { parent_project: ... }` field

**Comment by AndreyKozlov1984** [comment]
Give me an example project which is in fact a subproject of a different project, I'll make this change and you, @cjyabraham will be able to get this data via API

**Comment by cjyabraham** [comment]
Hubble is a subproject of Cilium

**Comment by AndreyKozlov1984** [comment]
@cjyabraham , I added the change. If you try to get api data you'll see parent_project in the `extra` field and then you can skip this project

https://landscape.cncf.io/?selected=hubble
https://github.com/cncf/landscape/blob/master/landscape.yml#L6340

**Comment by cjyabraham** [comment]
Ok, sounds fine. So what about the `project: incubating` line? That info is kind of redundant because I assume the parent project would set the maturity level. Is that right @amye? In which case, should we not have that line at all?

**Comment by amye** [comment]
Correct, that line should not be included.

**Comment by cjyabraham** [comment]
Ok, finally, @amye do you have a list of all projects which are in fact subprojects and their respective parent projects? I can update the landscape.yml to correct all their entries now...

**Comment by amye** [comment]
I'll go through and update based on the logos that shouldn't be included, we use the landscape as the source of truth

**Comment by amye** [comment]
https://github.com/cncf/landscape/pull/2751 resolves

**Comment by cjyabraham** [comment]
Ok. How about Hubble? Isn't that a subproject too? And are there any more?

**Comment by AndreyKozlov1984** [comment]
Is anything required from me here ?

**Comment by cjyabraham** [comment]
No it was a question for @amye

**Comment by amye** [comment]
Hubble is a subproject, missed that one

**Comment by cjyabraham** [comment]
Ok, I've taken care of those then. This issue is now done. Thanks for your help.
