### ISSUE TITLE
Sort last commit by human date

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#274]
Changing this request:

For both last commit and last release, please label all items from the last 7 days as `this week` and sort alphabetically, bucket all items from the previous 7 days as `last week` and sort alphabetically, continuing for `last month`, `2 months ago`.

**Comment by ZeusTheTrueGod** [comment]
Please clarify a bit, we already sort by name when primary sort returns same results fro two items.

**Comment by dankohn** [comment]
Looks at the bottom of: https://landscape.cncf.io/grouping=no&license=open-source&sort=latest-commit

All of the items with last commit `yesterday` should be sorted alphabetically, plus all the items with last commit `2 days ago`, `3 days ago`, etc. Earlier than a week, it's fine to just sort by time. But for recent items, I'm looking for some special logic for the comparison.

**Comment by ZeusTheTrueGod** [comment]
And as I guess everything older than 2 months ago can have same dates as before

**Comment by dankohn** [comment]
I'd prefer to do one for bucket for each month (3 months ago..., 11 months
ago) and then you could just sort by date.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com
