### ISSUE TITLE
Cannot easily search sandbox projects with browsers built-in page search

### ISSUE THREAD

**Issue by reegnz** [cncf/landscape#2808]
As discovered in [#924](https://github.com/cncf/toc/issues/924) one cannot easily search for projects by name on the CNCF website.

One should be able to search for Sandbox, Incubated or Graduated projects easily on the page by Ctrl+F. I find that this makes navigating the page a little bit complicated.

I created an issue because I cannot simply edit landscape.yaml to fix this one.

**Comment by tegioz** [comment]
Hi!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io) and this issue should be resolved.

Please feel free to reopen if needed 🙂
