### ISSUE TITLE
CNCF Landscape Guide page is not responsive properly

### ISSUE THREAD

**Issue by hs-07** [cncf/landscape#2811]
I would to like work over the improvement over the UI design of CNCF landscape [Guide page](https://landscape.cncf.io/guide), as its orientation in mobile view is not proper.
Here is the example screenshot below to ellaborate my issue.
![image](https://user-images.githubusercontent.com/87127387/194758704-18bcc3da-3d9f-442a-a669-4a167a1235c0.png)
I request to assign the issue to me 
Thank You 

https://github.com/cncf/landscape/issues/2811#tasklist-block-85cf4f33-aa7b-4ec1-b2ab-7bc3a1d42a44

**Comment by caniszczyk** [comment]
sure go for it!

**Comment by psancheti110** [comment]
Hi @hs-07, 
Are you still working on this issue?

if not, I would like to take this on.

**Comment by hs-07** [comment]
@psancheti110 
Yes I am working over it.

**Comment by hs-07** [comment]
@psancheti110 
By the way, do you know about Docker, kubernetes and Golang?

**Comment by hs-07** [comment]
@caniszczyk 
sir i am facing problem in running the project locally
Can you please help me?

**Comment by hs-07** [comment]
@caniszczyk 
sir while i am running the application on microsoft azure server, in the terminal it is showing following statements:
![8b159811-2fb3-4203-912d-622874bc81a6](https://user-images.githubusercontent.com/87127387/203474046-01ac83fb-2a43-49c3-b4c4-174378017ed0.jpg)

But when i am opening my localhost , the website isnt running there.

Can you please help me with the same?

**Comment by mohit1607** [comment]
Hi hs-07 I would like to assist you in this task and also Can you familirize me with this project. I am new to open source contribution.

**Comment by tegioz** [comment]
Hi!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io) and this issue should be resolved.

Please feel free to reopen if needed 🙂
