### ISSUE TITLE
Flip animation to modal popup

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#282]
From filterable-landscape created by [dankohn](https://github.com/dankohn) : cncf/filterable-landscape#13  

Add a 3-D horizontal flip animation when clicking a card, such as:

http://xue2han.github.io/react-dynamic-modal/
https://www.npmjs.com/package/react-dynamic-modal

**Comment by dankohn** [comment]
@alexkontsevoy in addition to making it work on close, could you please also try to have the card grow and flip from it's current location, as with: https://stackoverflow.com/a/35499596/1935918

**Comment by ZeusTheTrueGod** [comment]
I'll add 2 new states today : 'opening' and 'closing' so a css has a chance to properly display everything

**Comment by ZeusTheTrueGod** [comment]
To make it grow and flip, we 'll have to make some calculations

**Comment by ZeusTheTrueGod** [comment]
Now animation, although a different one, is supported from a framework, and that is good.
I want to try to also add a slide animation when a persons chooses a next or a previous item via click on left / right arrows

**Comment by dankohn** [comment]
I appreciate the hardwork here, but don't like the flip after all.

**Comment by dankohn** [comment]
You can close and delete branch.
