### ISSUE TITLE
Flip cards on mouseover

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#285]
From filterable-landscape created by [dankohn](https://github.com/dankohn) : cncf/filterable-landscape#34  

On mouseover, the cards should flip while staying in place like on https://dribbble.com/. This should show the description and one or two other fields.

**Comment by alexkontsevoy** [comment]
@dankohn the cards are flipping, I've made the description to appear on the back side:

![image](https://user-images.githubusercontent.com/4476098/39407731-93f073cc-4bec-11e8-98f4-ccd8531bed56.png)

Please say, what other fields do you want to see there

**Comment by dankohn** [comment]
Thanks, but I've decided I'd rather not include this functionality after all.
