### ISSUE TITLE
Add Google Cloud Storage to Cloud Native Storage

### ISSUE THREAD

**Issue by craigbox** [cncf/landscape#29]
In case you also want to add the Google Cloud Storage logo to the "Cloud Native Storage" section, it can be found [here](https://upload.wikimedia.org/wikipedia/en/2/2e/Google_Cloud_Storage_logo.png).

**Comment by craigbox** [comment]
Friendly ping.

**Comment by craigbox** [comment]
We'd love it you would use the three-colour GCP logo hexagon:
https://cloud.githubusercontent.com/assets/132510/20099933/dbfcd502-a5b2-11e6-990c-98f851af9868.png

**Comment by dankohn** [comment]
+1

**Comment by shawnpreissner** [comment]
Hi @craigbox please find in 0.9.4 under Infrastructure https://github.com/cncf/landscape/blob/master/landscape/CloudNativeLandscape_v0.9.4.jpg

**Comment by craigbox** [comment]
Hi Shawn,

This issue was to have Google Cloud Storage listed in "Storage" under Runtime, and as such still needs attention.
