### ISSUE TITLE
Istio Logo not rendering properly

### ISSUE THREAD

**Issue by therealmitchconnors** [cncf/landscape#2901]
#2805 merged the Istio Logo, and the svg renders blue on github, but black on the landscape.

**Comment by therealmitchconnors** [comment]
cc: @AndreyKozlov1984

**Comment by tegioz** [comment]
Hi!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io) and this issue should be resolved.

Please feel free to reopen if needed 🙂
