### ISSUE TITLE
Add more styling in this website

### ISSUE THREAD

**Issue by withgaurav** [cncf/landscape#2947]
![image](https://user-images.githubusercontent.com/76643106/210061170-d18d61ad-2f6e-4d93-96e9-f2afbb47b8fd.png)

[Landscape]( https://landscape.cncf.io/) view of this website can be seen more beautiful . Thankyou I'll wait for your response

**Comment by tegioz** [comment]
Hi!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io) and this issue probably no longer applies.

Please feel free to reopen if needed 🙂
