### ISSUE TITLE
Allow projects to set LinkedIn page

### ISSUE THREAD

**Issue by deepthi** [cncf/landscape#2952]
`landscape.yml` does not allow you to specify a LinkedIn page for a project.
We have a LinkedIn community for Vitess at https://www.linkedin.com/groups/12261364/. It will be nice to provide a link to this in the Landscape instead of linking to CNCF.

**Comment by chandankumar1307** [comment]
I would love to work on this issue if it's not been already assigned to anyone else

**Comment by caniszczyk** [comment]
@tegioz I assume this is possible with landscape v2?

**Comment by tegioz** [comment]
Not yet, but it's on the list (we got it from this issue actually 😉). We'll take care of it soon.

**Comment by tegioz** [comment]
This is now available in landscape v2. You can override the LinkedIn url obtained from Crunchbase (when available) by setting it in the item's extra field:

```yaml
extra:
  linkedin_url: https://www.linkedin.com/...
```
