### ISSUE TITLE
Trivy-operator project do not appear as open source project 

### ISSUE THREAD

**Issue by chen-keinan** [cncf/landscape#2971]
I have added Trivy-operator project under Security & Compliance.

The Trivy-operator project is an open source project however it do not appear as one on landscape.

Pls advice on what is missing

**Comment by craigbox** [comment]
Surely an operator for a project should just be listed as the project itself?

**Comment by chen-keinan** [comment]
> Surely an operator for a project should just be listed as the project itself?

note sure I fully understand , we have two projects `starboard` and `trivy-operator` both are `open source` and listed in the same way , however `starboard` is shown as open source where `trivy-operator` isn't. 
could you please advice what is missing ?

**Comment by tegioz** [comment]
Hi!

We've recently migrated the [CNCF landscape to v2](https://landscape.cncf.io) and this issue should be resolved.

Please feel free to reopen if needed 🙂
