### ISSUE TITLE
Project summary page doesn't scroll properly

### ISSUE THREAD

**Issue by craigbox** [cncf/landscape#2975]
There's a scrollbar at the bottom of https://landscape.cncf.io/summary

<img width="1243" alt="Screenshot 2023-01-12 at 12 13 08 PM" src="https://user-images.githubusercontent.com/132510/211938214-7cc0d6cf-6257-497f-96dd-41ff8dac1c1f.png">

But it doesn't actually scroll anything, no!  Instead you have to scroll vertically to the end, and then use _a different_ scroll bar.

<img width="1243" alt="Screenshot 2023-01-12 at 12 13 37 PM" src="https://user-images.githubusercontent.com/132510/211938220-1c79ad41-74ba-4997-8b56-e5cc66e838fc.png">

**Comment by Faizan711** [comment]
is anyone working on this issue, if not i would like to be assigned for it and fix it.

**Comment by AndreyKozlov1984** [comment]
I did the summary page, about to fix this. I am really curious what is wrong there

**Comment by jai-bhardwaj** [comment]
I think this issue is solved now.

**Comment by tegioz** [comment]
Hi!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io) and this issue probably no longer applies.

Please feel free to reopen if needed 🙂
