### ISSUE TITLE
Add lightbend reactive platform frameworks (Play/Akka/Lagom) and scala language

### ISSUE THREAD

**Issue by kikiya** [cncf/landscape#30]
Add Play, Akka, Lagom to frameworks and Scala language. 

Logos for reference on lightbend.com

**Comment by shawnpreissner** [comment]
Added Lightbend to languages & frameworks

**Comment by shawnpreissner** [comment]
Hi @kikiya please find in 0.9.4 https://github.com/cncf/landscape/blob/master/landscape/CloudNativeLandscape_v0.9.4.jpg

**Comment by dankohn** [comment]
Sorry, we removed all the programming languages and frameworks from the newest version, whether they are open source or proprietary.
