### ISSUE TITLE
Add GitHub contributors and releases

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#302]
Please have the GitHub fetcher pull the current number of contributors and the date of the last release. 

The contributor number we want is 1,605 for Kubernetes.
<img width="1023" alt="screen shot 2018-03-04 at 8 11 44 pm" src="https://user-images.githubusercontent.com/3083270/36953387-4d0531f8-1fe8-11e8-8a48-3bdb639ad256.png">

However, it doesn't seem easily available from the API. This [trick](https://stackoverflow.com/a/44347632/1935918) is giving me the wrong answer. https://api.github.com/repos/kubernetes/kubernetes/contributors?per_page=1 shows 391.

So, scraping the GitHub HTML page may be easier.

The releases date (which should say 4 days ago) should be a link to https://github.com/kubernetes/kubernetes/releases

If there's no data just don't show.

The contributors number should be a link to https://github.com/kubernetes/kubernetes/graphs/contributors

Cc @caniszczyk

**Comment by ZeusTheTrueGod** [comment]
I guess this should go after the last commit date, am I correct ?

**Comment by dankohn** [comment]
Right above first commit is good.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com
