### ISSUE TITLE
Subprojects aren't listed as CNCF projects

### ISSUE THREAD

**Issue by xmulligan** [cncf/landscape#3058]
Some CNCF projects are listed as [sub-projects](https://github.com/cncf/landscape/commit/07f2db22fb44def3abf84d27e7c41fc9b5fc311b). They show up [under CNCF as an organization](https://landscape.cncf.io/card-mode?organization=cloud-native-computing-foundation-cncf), but they [don't show up as CNCF projects](https://landscape.cncf.io/card-mode?project=hosted). It would be helpful if they are listed under both views because some people think the project is no longer a part of the CNCF then.

**Comment by xmulligan** [comment]
we've had this come up a few times so it would be great if there could be a way to fix this 🙏 

<img width="311" alt="Screenshot 2023-09-13 at 18 26 52" src="https://github.com/cncf/landscape/assets/29048870/e33a70c1-df1f-4e32-84dc-0f40767421e4">

**Comment by tegioz** [comment]
Hi @xmulligan 👋

For landscape v1, this behavior was changed in #2734 as a response to #2694. Displaying subprojects as projects was kind of confusing, as detailed in those issues.

In landscape v2, subprojects aren't listed when filtering by CNCF projects either, same as in v1. However, when opening the details of a subproject we highlight the parent project and, if it belongs to the CNCF, we show that as well.

<br/>
<img width="1680" alt="subproject" src="https://github.com/cncf/landscape/assets/1213902/3ef7fb15-cba9-48f7-9381-31cc8f12fb42">
<br/><br/>

Hope this helps making everything a bit clearer 🙂

Will close this one for now, please feel free to reopen if needed.

**Comment by xmulligan** [comment]
Ok, thanks
