### ISSUE TITLE
Can NOT add new entry in database section of landscape

### ISSUE THREAD

**Issue by Nelson-He** [cncf/landscape#3072]
Hi all
  I just think maybe the action of deploy/netlify run into problems, cause when I add new entry in database subcategories, the check will always fail, and the log show Fatal error info as belows
```
9:38:37 AM: FATAL: Empty twitter for RStudio (supporter): https://twitter.com/rstudio
9:38:37 AM: FATAL: No cached entry, and Privado (member) has issues with twitter: https://twitter.com/ai_privado, Request failed with status code 404
9:38:37 AM: FATAL: No cached entry, and ACKSTORM (member) has issues with twitter: https://twitter.com/ackstormsl, Request failed with status code 404
9:38:37 AM: FATAL: No cached entry, and Weaviate has issues with twitter: https://twitter.com/weaviate-io, Request failed with status code 404
9:38:37 AM: FATAL: Empty twitter for Tarantool: https://twitter.com/mailru
9:38:37 AM: ERROR: Using cached entry, because CloudHealth Technologies has issues with twitter: https://twitter.com/cloudhealthtech, Request failed with status code 401
```
I can not see where the problem is, can anyone helps?
By the way, my PR link is: https://github.com/cncf/landscape/pull/3071

**Comment by caniszczyk** [comment]
hey @AndreyKozlov1984 can you take a look at this? seems like a simple fix of bad twitter info?

**Comment by Nelson-He** [comment]
> hey @AndreyKozlov1984 can you take a look at this? seems like a simple fix of bad twitter info?

Hi, Thanks for your quick reply, sincerely.
 @AndreyKozlov1984 , I just run the ./server.js successfully on my laptop with my commit and without anything else changed, and I can see my add-on in the generated landscape.
```
% ./server.js
Development server running at http://127.0.0.1:8001/
Starting a new build...
2023-03-02T02:48:31.176Z build result: success
```
Hope this info will help you find the problem location.

**Comment by AndreyKozlov1984** [comment]
The real issue is here!

`FATAL ERROR: layout issues.`

Yes, you can run locally, and if you open the page, you can see that some items are (almost) out of bounds after adding one new item. I'll make a new PR

**Comment by markphelps** [comment]
👋🏻 I am also having what seems to be the same problem in #3076 . Is there something I can do to fix the layout issue?

**Comment by AndreyKozlov1984** [comment]
I am experimenting with an automatic layout autoresize.

**Comment by tegioz** [comment]
Hi!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io) and this issue probably no longer applies.

Please feel free to reopen if needed 🙂
