### ISSUE TITLE
Serverless and memebers on https://landscape.cncf.io/images/landscape.pdf points to localhost

### ISSUE THREAD

**Issue by scorcism** [cncf/landscape#3081]
Hello there,
I was goint through the pdfs
and I found that, when we hover or try to click on the `serverless` and `members` card on the right sidebar inside https://landscape.cncf.io/images/landscape.pdf it points to **localhost:4000**
The cards: https://imgur.com/O8Xw1JE.png

**Comment by tegioz** [comment]
Hi!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io) and this issue probably no longer applies.

Please feel free to reopen if needed 🙂
