### ISSUE TITLE
1. Quick off Heuristic Analysis 

### ISSUE THREAD

**Issue by andreuxxxx** [cncf/landscape#3083]
We'll review the current CNCF Landscape Interface to detect areas of opportunity. This will serve as a "warm up" and to get deeply familiar with the current state of the interface. 

TASKS

- [x] Hilda @Hilzygift will run through the Landscape and will use her expertise to propose what kind of heuristic analysis we'll run
- [x] Andrea & Hilda will meet on Friday to discuss, chose the more appropriate Heuristic methodology so next week we can setup tasks and dates to execute the analysis

**Comment by Hilzygift** [comment]
Hi Andrea,
Here's what I could come up with
https://miro.com/welcomeonboard/bzFGc2QzVUVuQnBHaDdUTXdyNU42bzZlZ3VPWnRjeWY2OFpqT0taOGtIQUY0ZXhCYWdVajVvTlRZb3MzOHdMRnwzMDc0NDU3MzU3MzMxNjczNzIzfDI=?share_link_id=456841996832

I will keep updating the board with more information

**Comment by nate-double-u** [comment]
closing as done, thanks @Hilzygift!
