### ISSUE TITLE
Add Lightbend Reactive Platform Production Suite to Platforms

### ISSUE THREAD

**Issue by kikiya** [cncf/landscape#31]
Lightbend production suite is a platform that enables service orchestration, monitoring, logging, tracing, service discovery, service management and enhanced resilience on distributed cloud based applications. 

Please add Lightbend logo to:
- Scheduling & Orchestration
- Service Discovery
- Service Management
- Monitoring
- Logging
- Tracing
 
Reactive Platform Production Suite details here -http://www.lightbend.com/platform/production

Lightbend Logo here - http://d3gnpvjw8j16uq.cloudfront.net/assets/images/svg/logo/09a7a2d971d039288221b17d1ef8ffb3-lightbend-color-reverse.svg

**Comment by shawnpreissner** [comment]
Thanks, added to Languages & Frameworks...limiting each to one category

**Comment by shawnpreissner** [comment]
Hi @kikiya please find in 0.9.4 under Languages & Frameworks https://github.com/cncf/landscape/blob/master/landscape/CloudNativeLandscape_v0.9.4.jpg

**Comment by kikiya** [comment]
Thanks @shawnpreissner !
