### ISSUE TITLE
Issue with firstcommitLink rendering 

### ISSUE THREAD

**Issue by hrittikhere** [cncf/landscape#3104]
When clicked on First Commit there happens to be a `"` at end of the link breaking the links

![image](https://user-images.githubusercontent.com/67012359/227853405-85cffb3e-7f6c-40e9-b901-b0af1e186f4e.png)

**Comment by adwait-godbole** [comment]
hey @hrittikhere, this issue seems to be in the https://github.com/cncf/landscapeapp repository. I have found it and fixed it. 
You can check out my PR there. Here's the link to my PR:- https://github.com/cncf/landscapeapp/pull/875

**Comment by tegioz** [comment]
Hi!

We've migrated the [CNCF landscape to v2](https://landscape.cncf.io) and this issue probably no longer applies.

Please feel free to reopen if needed 🙂
