### ISSUE TITLE
 When downloading the CSV file of CNCF Landscape, it is giving a file with a .css extension instead of a CSV.

### ISSUE THREAD

**Issue by akhilsahuji** [cncf/landscape#3126]
Steps to Reproduce:

- Go to the CNCF Landscape website (https://landscape.cncf.io/).
- Click on the "Download CSV" button located at the top right corner of the page.
- Select the location to save the file and click on "Save".
- Check the downloaded file's extension.

Expected Result:
- The downloaded file should have a .csv extension.
![image](https://user-images.githubusercontent.com/46328560/230442097-1217e56a-95a3-4199-93aa-8b957223d7fc.png)

Actual Result:
- The downloaded file has a .css extension instead of a .csv extension.
![Screenshot 2023-04-06 215816](https://user-images.githubusercontent.com/46328560/230442431-2cd22a0a-c86c-404d-a49c-dd751693cc5f.png)

Impact:
This issue prevents users from being able to download the CSV file of CNCF Landscape correctly. As a result, users may not be able to access the data they need for their projects, research, or analysis.

Possible Causes:
There may be an issue with the website's code that is causing the file extension to be incorrect when downloaded.

Proposed Solution:
To fix this issue, the website's code needs to be reviewed and modified so that the CSV file downloads correctly with the .csv extension. 
I think I should check the code related to the download functionality and ensure that the file is saved with the correct extension. But I am not able to find the source code in the master branch I searched for previous issues related to CSV but the file path `src/components/ExportExcel.js` is not in the master branch. Can Someone point out where should look?

Workaround:
As a temporary workaround, users can try manually changing the downloaded file's extension from .css to .csv. However, this workaround is not ideal as it may cause compatibility issues with some software that expects files to have the correct extension.

Priority:
This issue should be assigned a high priority as it impacts the usability and functionality of the CNCF Landscape website.

**Comment by caniszczyk** [comment]
weird for me I get a .csv :)

**Comment by caniszczyk** [comment]
[interactive-landscape (test).csv](https://github.com/cncf/landscape/files/11173420/interactive-landscape.test.csv)

**Comment by akhilsahuji** [comment]
![image](https://user-images.githubusercontent.com/46328560/230490750-a40322c8-b013-435b-9741-1d943dfe7ff4.png)
- Yes you are right other browsers are giving CSV files but Firefox is only giving me CSS files I think something is wrong either with Firefox or with the website.
- It's possible that the website sent the wrong file type to Firefox, or that Firefox interpreted the file type incorrectly?

**Comment by akhilsahuji** [comment]
it's really weird I tried to download it on my mobile phone on Chrome and Brave it gave me 
`interactive-landscape.csv.css` and on mobile Firefox it gives `interactive-landscape.csv` just opposite of desktop.

**Comment by jmhbnz** [comment]
Confirming I can re-create this issue with Firefox desktop, where clicking download csv results in `interactive-landscape.css`.

If I use Chromium desktop I get the correct `interactive-landscape.csv`.

The issue is also open here https://github.com/cncf/landscapeapp/issues/866

I've raised the pull request to fix: https://github.com/cncf/landscapeapp/pull/876

**Comment by tegioz** [comment]
Hi!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io) and this issue should be resolved.

Please feel free to reopen if needed 🙂
