### ISSUE TITLE
Jaeger is not showing in the Tracing category in Summary

### ISSUE THREAD

**Issue by yurishkuro** [cncf/landscape#3127]
https://landscape.cncf.io/summary

Jaeger shows under Observability/All, but not under Observability/Tracing

**Comment by mastersans** [comment]
Can i work on the issue.

**Comment by tegioz** [comment]
Hi!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io) and this issue probably no longer applies.

Please feel free to reopen if needed 🙂
