### ISSUE TITLE
Add Twitter card metadata

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#314]
https://moz.com/blog/meta-data-templates-123

One option: https://www.npmjs.com/package/meta-cards

Please test by making a tweet of the preview server.

**Comment by dankohn** [comment]
Note that I'm only interested in the Twitter card data. But please modify the values returned to match the card that's currently selected. So, tweeting https://landscape.cncf.io/grouping=landscape&selected=kube-virt would include the logo for Kube Virt instead of the Landscape logo.

**Comment by ZeusTheTrueGod** [comment]
I'm not completely sure what is this.

**Comment by dankohn** [comment]
Create a Twitter account and separately post to Twitter the URLs https://github.com/cncf/landscape and https://cncf.io.

You'll see that Twitter creates a card showing an image and the link. We want the same to happen from the interactive landscape.

**Comment by ZeusTheTrueGod** [comment]
cncf.io is set up with this data:
```

<meta property="og:locale" content="en_US" />
--
  | <meta property="og:type" content="website" />
  | <meta property="og:title" content="Home Page - Cloud Native Computing Foundation" />
  | <meta property="og:url" content="https://www.cncf.io/" />
  | <meta property="og:site_name" content="Cloud Native Computing Foundation" />
  | <meta property="fb:admins" content="alex.contini.94" />
  | <meta property="og:image" content="https://www.cncf.io/wp-content/uploads/2017/12/icon_cncf_twitter.png" />
  | <meta property="og:image:secure_url" content="https://www.cncf.io/wp-content/uploads/2017/12/icon_cncf_twitter.png" />
  | <meta name="twitter:card" content="summary" />
  | <meta name="twitter:title" content="Home Page - Cloud Native Computing Foundation" />
  | <meta name="twitter:site" content="@CloudNativeFdn" />
  | <meta name="twitter:image" content="https://www.cncf.io/wp-content/uploads/2017/12/icon_cncf_twitter.png" />
  | <meta name="twitter:creator" content="@CloudNativeFdn" />


```

**Comment by ZeusTheTrueGod** [comment]
Can we just reuse that content? I can change  a url.

**Comment by dankohn** [comment]
Mainly, but some of the information needs to be changed. For example, logo should be: https://raw.githubusercontent.com/cncf/artwork/master/other/cncf-landscape/icon/color/cncf-landscape-icon-color.png

But we probably want to serve the image from landscape.cncf.io.

Title and site_name should be "CNCF Cloud Native Interactive Landscape"

**Comment by dankohn** [comment]
This doesn't look resolved yet. Test at https://cards-dev.twitter.com/validator

**Comment by dankohn** [comment]
Twitter caching picked up the card but the title was wrong: https://twitter.com/tombee74/status/971979128546054144
