### ISSUE TITLE
Fix the link for "Edit this page" button

### ISSUE THREAD

**Issue by Mohith234** [cncf/landscape#3198]
### **ISSUE**

- On the [guide page](https://landscape.cncf.io/guide), "Edit this page" option redirects to a broken link

### **FIXING THE ISSUE**
- Change the URL redirecting to https://github.com/cncf/landscape/edit/master/guide.md

### **SCREENSHOT** 

![image](https://github.com/cncf/landscape/assets/88539464/4e0c82d5-95b7-4e3b-b4ff-4ac56eacfc5f)

**Comment by nakul1710** [comment]
It look like a easy issue for new comer. Can you assign me this to me?

**Comment by sripor62** [comment]
Hello, I am interested in fixing the issue.Can you assign me .

**Comment by SagarRawat24** [comment]
@Mohith234 can u tell where is Html file or folder i can't find it to solve the issue i am a begginer can you assign to me i would love to contribute.

**Comment by sharmatanikesh** [comment]
@Mohith234  Can you please assign this issue to me?

**Comment by Bhanuteja01** [comment]
/assign me this 
i can fix this

**Comment by aryasoni98** [comment]
I would like to work on it

**Comment by sahil-R** [comment]
Is this fixed @Mohith234 ??

**Comment by tegioz** [comment]
Hi!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io) and this issue probably no longer applies.

Please feel free to reopen if needed 🙂
