### ISSUE TITLE
Fetch last tweet date

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#321]
Please add a tweet scraper to fetch the date of the last tweet. Display the date as with our other dates (e.g., yesterday, last week) and make it a link to the tweet.

Add a sort option to sort by last tweet. The idea is to find moribund companies.

**Comment by ZeusTheTrueGod** [comment]
Looks like I can use a simple html request and then look for `data-time-ms` attribute to fetch dates of tweets on a front page. I'll take the maximum date and will use it.
Also I'll add the `twitter` section for the `processed_landscape.yml`

**Comment by ZeusTheTrueGod** [comment]
Also I will use a same rule for fetching the twitter data as I do for fetching basic github stats, i.e. it should not be run by default, only from a packet bot

**Comment by dankohn** [comment]
RIght, medium level.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by ZeusTheTrueGod** [comment]
@dankohn what should I do when a wrong twitter account is specified ? I.e. the one which returns 404
Right now I just add an error message,
`No cached entry, and Honeybadger has issues with twitter: https://twitter.com/joneybadgerapp, 404`

**Comment by dankohn** [comment]
Fatal error makes sense so we can fix it when it’s first set up. 

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation  https://www.cncf.io
+1-415-233-1000  https://www.dankohn.com

**Comment by ZeusTheTrueGod** [comment]
Also it can be a twitter with no entries, show it be treated as an error? Because I doubt you need such products

**Comment by ZeusTheTrueGod** [comment]
I.e. an empty twitter account

**Comment by dankohn** [comment]
Let's treat an empty account as a fatal error as well. It doesn't make sense for us to include those.
