### ISSUE TITLE
CNCF Landscape: UX UI improvement I / Research Plan Documentation

### ISSUE THREAD

**Issue by Hilzygift** [cncf/landscape#3215]

**Comment by nate-double-u** [comment]
This looks to be completed (in the project board).

@Hilzygift & @andreuxxxx, could we provide a link to this plan and close this issue if it's complete?

**Comment by Hilzygift** [comment]
**Research Plan** @andreuxxxx 

**Background** 

The CNCF Landscape is a comprehensive map of cloud-native technology projects that are part of the CNCF ecosystem. The Landscape is a useful tool for developers, architects, and business leaders to discover and learn about the cloud-native technologies available.
We aim to provide a user-friendly experience and optimize the current user experience and user interface Landscape for all those who interact with the Landscape, and we understand that this requires a thorough examination of the interface's usability.

Link to full research plan: [Link](https://docs.google.com/document/d/1zDLTyg5nCoxFPOQsSBWmAe6VBBMsrcy9flc1OVKgiIE/edit?usp=sharing)
