### ISSUE TITLE
Improper placement of Bar graph when not in full screen mode

### ISSUE THREAD

**Issue by parmishh** [cncf/landscape#3244]
The Bar graphs are not placed properly. It can be reproduced if you exit full screen or increase the zoom of web browser.

![511eebc9-b8ab-417b-99bd-973a9fc142ff](https://github.com/cncf/landscape/assets/91942072/31e311a5-0cfd-46a7-bab1-fd902d4a50b9)

**Comment by tehami02** [comment]
Do you how can we edit changes in this landscape page??...I mean I didn't found any html file or any such file that runs as this website.

**Comment by parmishh** [comment]
@tehami02 lets wait for a maintainer to comment on this

**Comment by tegioz** [comment]
Hi!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io) and this issue probably no longer applies.

Please feel free to reopen if needed 🙂
