### ISSUE TITLE
Create report for the work done in UX /UI mentorship round 1

### ISSUE THREAD

**Issue by andreuxxxx** [cncf/landscape#3256]
Please review all te work executed by @Hilzygift so we can take over and decide on next steps.

```[tasklist]
### Tasks
- [ ] Review video recordings and findings
```

**Comment by avantikajain289** [comment]
@Hilzygift Could you please add the link to your presentation and documentation here. Would be great to access all the amazing work you have done!

**Comment by avantikajain289** [comment]
@andreuxxxx please take a look at this short review of the CNCF (Term 1) Landscape Redesign Initiative.

Here is a link to my notion file:
https://rust-flavor-4ed.notion.site/Review-Term-1-of-the-CNCF-Landscape-Redesign-Initiative-3cabf5f63d894bbf8f6d3c9c7562240a?pvs=4

**Comment by tegioz** [comment]
Thanks @andreuxxxx!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io), so I'll close this one for now.

Please feel free to reopen if needed 🙂
