### ISSUE TITLE
Create simple acces to ALL video recordings

### ISSUE THREAD

**Issue by andreuxxxx** [cncf/landscape#3257]
We must have an easy access form the board to ALL video recordings. Add links to recording to this card

@Hilzygift

**Comment by nate-double-u** [comment]
I'm happy to have links to the private google drive here, but we need to be careful that we are protecting folks privacy even in the links. First names in the path should be fine, but if the file name/path has someone's full name we may want to make a change before linking here.

**Comment by tegioz** [comment]
Thanks @andreuxxxx!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io), so I'll close this one for now.

Please feel free to reopen if needed 🙂
