### ISSUE TITLE
Figma team file for consolidated UX research and UI design

### ISSUE THREAD

**Issue by avantikajain289** [cncf/landscape#3273]
We require a Figma file that can be used for UX research (figjam) and UI design purposes. This file will be accessed by mentors, stakeholders, mentees, and other contributors (eventually) with varying levels of access (view or edit).

Does the file require a CNCF email for access? If so, please add the information of the email/username and password.

@andreuxxxx @nate-double-u 

```[tasklist]
### Tasks
- [ ] Email associated with this project for figma
- [ ] Figma and figjam files for consolidated research and design
```

**Comment by nate-double-u** [comment]
Is there a cost associated with this? Does Figma have an open source program we could join?

**Comment by avantikajain289** [comment]
I will do some research regarding this and get back to you.

**Comment by avantikajain289** [comment]
Hi @nate-double-u and @andreuxxxx,

I found some resources for making an informed decision regarding our Figma files. We can get on an education plan or stick with the free plan that provides us with 3 Figma and Figjam files.

1. https://www.figma.com/education/
2. https://www.figma.com/pricing/#figma-for-design-prototyping
3. https://help.figma.com/hc/en-us/articles/360040328273-Figma-plans-and-features

**Comment by tegioz** [comment]
Thanks @avantikajain289!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io), so I'll close this one for now.

Please feel free to reopen if needed 🙂
