### ISSUE TITLE
Monthly Meeting Calendly Invite with Andrea and Nate

### ISSUE THREAD

**Issue by avantikajain289** [cncf/landscape#3274]
```[tasklist]
### Tasks
- [ ] Create a monthly recurring Calendly invite with Andrea and Nate for this time: 9 PM IST/ 11:30 AM EST/ 8:30 AM PST.
```
@andreuxxxx

**Comment by tegioz** [comment]
Thanks @avantikajain289!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io), so I'll close this one for now.

Please feel free to reopen if needed 🙂
