### ISSUE TITLE
Draft an email to invite stakeholders for a focus group meeting

### ISSUE THREAD

**Issue by avantikajain289** [cncf/landscape#3276]
Write a draft to invite stakeholders to join the landscape redesign process discussion for inputs, insights, vision etc.

@andreuxxxx

**Comment by avantikajain289** [comment]
Hi @andreuxxxx and @Hilzygift 

I'm attaching a notion file with a draft of an email we can share to stakeholders for a focus group: https://rust-flavor-4ed.notion.site/Stakeholder-Invitation-Email-b3b8e7678d194b8cbe6879afdff28b7d?pvs=4

Please let me know if you have any feedback and a specific calendar date for this meeting, I'm happy to make some edits and send it out to a list of stakeholders.

**Comment by tegioz** [comment]
Thanks @avantikajain289!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io), so I'll close this one for now.

Please feel free to reopen if needed 🙂
