### ISSUE TITLE
Create Proto Personas

### ISSUE THREAD

**Issue by avantikajain289** [cncf/landscape#3310]
Create two proto-personas to assist in the development and empathy stage of the design thinking process. The proto-persona should be based on assumptions about the target end-user and assist as a foundation to create persona's after the user interviews and affinity maps.

**Comment by avantikajain289** [comment]
The Figma link to the proto-persona's are provided below:
https://www.figma.com/file/JfEElCltA2vuyWmKfSQLm4/Proto-Personas?type=whiteboard&node-id=0%3A1&t=yF6ZWRHS89PKUFOh-1

**Comment by tegioz** [comment]
Thanks @avantikajain289!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io), so I'll close this one for now.

Please feel free to reopen if needed 🙂
