### ISSUE TITLE
App stops working after one hour

### ISSUE THREAD

**Issue by H4817** [cncf/landscape#3319]
![image](https://github.com/cncf/landscape/assets/14195832/a3614be6-8ce1-4e58-a202-91914cfe0bf8)

Steps to reproduce:
1. git clone https://github.com/cncf/landscape.git
2. cd landscape
3. make serve-docker
4. wait approximately one hour

**Comment by tegioz** [comment]
Hi!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io) and this issue probably no longer applies.

Please feel free to reopen if needed 🙂
