### ISSUE TITLE
Why are member/non-member projects separated out?

### ISSUE THREAD

**Issue by tgraf** [cncf/landscape#334]
What is the purpose of separating out projects driven by CNCF members?

**Comment by dankohn** [comment]
It provides a benefit for CNCF members to have their projects/products featured first. But if you don’t find it useful, please change grouping to no.

**Comment by tgraf** [comment]
How is this aligned with the charter?

> The foundation accepts all contributors based on the merit of their contributions, and the foundation’s technology must be available to all according to open source values.

> (c) Fair. The foundation will avoid undue influence, bad behavior or “pay-to-play” decision-making.

**Comment by dankohn** [comment]
We accept all contributions. We have tons of non-member projects/products listed.

The funding from our members is what enables us to build a tool like the interactive landscape. I don't see that as 'undue influence, bad behavior or “pay-to-play” decision-making.'

If it bothers you, I urge you to bookmark: https://landscape.cncf.io/grouping=no
