### ISSUE TITLE
Add Dynatrace to Observability & Analysis

### ISSUE THREAD

**Issue by metmajer** [cncf/landscape#34]
Hi, you may want to consider adding Dynatrace, a market leader in the application monitoring space to the Observability & Analysis board. You can find more information on us [here](https://www.dynatrace.com/).

**Comment by 1605200517** [comment]
Hi  @metmajer , your wish has been fulfilled here: 
https://github.com/1605200517/alm-devops-landscape 
:-)

**Comment by metmajer** [comment]
Thanks @1605200517! Looking forward to what v1.0 will look like 👍

**Comment by fraka79** [comment]
+1
Pls. find attached their current logo:
![dynatrace_logo_rgb_cph_2048x364px](https://cloud.githubusercontent.com/assets/26711197/24352749/18dd1090-12eb-11e7-97aa-aea2cfcad3a0.png)

**Comment by shawnpreissner** [comment]
Hi @metmajer please find in 0.9.4 https://github.com/cncf/landscape/blob/master/landscape/CloudNativeLandscape_v0.9.4.jpg

**Comment by metmajer** [comment]
Thanks @shawnpreissner, much appreciated!
