### ISSUE TITLE
Create a User Journey Map

### ISSUE THREAD

**Issue by avantikajain289** [cncf/landscape#3434]
Create a user journey map for better understanding of the situation, scenario persona's go through during their visit of the landscape.

**Comment by avantikajain289** [comment]
Figma link for the user journey map:
https://www.figma.com/file/iP9LxCPbDKXMtvjh1mODV3/User-Journey-Map?type=whiteboard&node-id=0%3A1&t=uP8QlD577lRTTWyL-1

**Comment by tegioz** [comment]
Thanks @avantikajain289!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io), so I'll close this one for now.

Please feel free to reopen if needed 🙂
