### ISSUE TITLE
Create a Value Proposition Canvas based on user interviews

### ISSUE THREAD

**Issue by avantikajain289** [cncf/landscape#3447]
Value Proposition Canvas [link](https://www.figma.com/file/0Y8SeT3c48YAFkORuVtTgo/Value-Proposition-Canvas?type=whiteboard&node-id=0%3A1&t=6KexQAwNQOKdVqKD-1)

**Comment by tegioz** [comment]
Thanks @avantikajain289!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io), so I'll close this one for now.

Please feel free to reopen if needed 🙂
