### ISSUE TITLE
Add DockerSlim to the Secure Images Category

### ISSUE THREAD

**Issue by q-cloudlock** [cncf/landscape#35]
DockerSlim is an open source container image optimization and security tool. It reduces the attack surface for container images and it also auto-generates seccomp and AppArmor security profiles.

https://github.com/docker-slim/docker-slim

Here's the project logo:  https://github.com/docker-slim/docker-slim/raw/master/assets/images/dslim/DockerSlimLogo1Big.png

Submitting a new issue now that there's an official high resolution logo.

**Comment by dankohn** [comment]
Closing due to trademark concerns.
