### ISSUE TITLE
Incubation data missing from .csv

### ISSUE THREAD

**Issue by amye** [cncf/landscape#3502]
When downloading all CNCF projects into a .csv file, the date for "incubating" is an empty column. 

This is probably because the column header is "Incubation" but the metadata tag is "incubating".

**Comment by aryasoni98** [comment]
I would like to work on it

**Comment by tegioz** [comment]
Hi!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io) and this issue should be resolved.

Please feel free to reopen if needed 🙂
