### ISSUE TITLE
Stakeholder Interview Transcript

### ISSUE THREAD

**Issue by avantikajain289** [cncf/landscape#3523]
Transcript written by Avantika Jain.

Figma file:
https://www.figma.com/file/YBjQhBCf60tix1ce6iYQoL/Stakeholder-Interview-Transcript%3A-Taylor-Dolezal?type=whiteboard&node-id=0%3A1&t=YtJjSKudol91zdbo-1

**Comment by tegioz** [comment]
Thanks @avantikajain289!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io), so I'll close this one for now.

Please feel free to reopen if needed 🙂
