### ISSUE TITLE
Stakeholder Interview Card Sorting

### ISSUE THREAD

**Issue by avantikajain289** [cncf/landscape#3524]
Card Sorting into categories before Affinity Mapping

Figma File:
https://www.figma.com/file/Zd9IZ7LmouR8S1wBa0Let6/Stakeholder-Interview-Card-Sorting%3A-Taylor-Dolezal?type=whiteboard&node-id=10%3A249&t=FlenECNH8MKqZwRU-1

**Comment by tegioz** [comment]
Thanks @avantikajain289!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io), so I'll close this one for now.

Please feel free to reopen if needed 🙂
