### ISSUE TITLE
Stakeholder Interview Affinity Mapping

### ISSUE THREAD

**Issue by avantikajain289** [cncf/landscape#3525]
Affinity Map to gather insights and reflections of the interview conducted with Taylor Dolezal, Head of Ecosystems, CNCF.

Figma File:
https://www.figma.com/file/0YQCf4Nhz8HWbHd8HdJ16t/Stakeholder-Interview-Affinity-Diagramming%3A-Taylor-Dolezal?type=whiteboard&node-id=0%3A1&t=1n1RcWn9kj3Th8I1-1

**Comment by tegioz** [comment]
Thanks @avantikajain289!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io), so I'll close this one for now.

Please feel free to reopen if needed 🙂
