### ISSUE TITLE
Persona's

### ISSUE THREAD

**Issue by avantikajain289** [cncf/landscape#3526]
Persona's created based on user interviews conducted in Term 1.

Figma file:

Persona [1](https://www.figma.com/file/AZHNC29hznw5oReYImBZ8g/Persona-person-1?type=whiteboard&node-id=0%3A1&t=OAM354FLAI91mYY2-1)

[Persona 2](https://www.figma.com/file/Ah1l3mtkERtMi12UnsVeDk/Personas-person-2?type=whiteboard&node-id=0%3A1&t=LKwivkYpHmltH2s1-1)

**Comment by tegioz** [comment]
Thanks @avantikajain289!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io), so I'll close this one for now.

Please feel free to reopen if needed 🙂
