### ISSUE TITLE
Stakeholder Email Survey

### ISSUE THREAD

**Issue by avantikajain289** [cncf/landscape#3527]
Taylor Dolezal email responses to CNCF landscape questions

[Google Doc file](https://docs.google.com/document/d/1xRSb4ClrLqUVR4n9cC29lCX7XG8h8W5QpEA2vNtsiNA/edit?usp=sharing)

**Comment by tegioz** [comment]
Thanks @avantikajain289!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io), so I'll close this one for now.

Please feel free to reopen if needed 🙂
