### ISSUE TITLE
Alignment is not proper in landscape guide

### ISSUE THREAD

**Issue by kumarankit999** [cncf/landscape#3562]
Alignment is not good in landscape guide documentation and have in right side. I can't see the proper alignment in mobile (android).

![Screenshot_20231016_141402.jpg](https://github.com/cncf/landscape/assets/111564362/b5c7ab1d-f1e3-4f5e-8680-dfcb9c1469f6)

**Comment by tegioz** [comment]
Hi!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io) and this issue probably no longer applies.

Please feel free to reopen if needed 🙂
