### ISSUE TITLE
Typo on csv export > csv exports leads to download interactive-landscape.css (instead of interactive-landscape.csv)

### ISSUE THREAD

**Issue by adriens** [cncf/landscape#3580]
### Typo on csv export

1. Click the **Download as CSV**
2. See that you downloaded `interactive-landscape.css` instead of `interactive-landscape.csv`

**Comment by rohan-kapse** [comment]
@adriens can i work on this if u may?

**Comment by adriens** [comment]
Hi @rohan-kapse , sure. I'll test to validate the fix :100:

**Comment by RupeshHacker** [comment]
@adriens 
![Screenshot (42)](https://github.com/cncf/landscape/assets/58428810/725c148b-f994-4c3e-a768-21bdd906f6b0)
its working good I haven't faced that issue

**Comment by adriens** [comment]
Currently, when I click on "Download as CSV" I get this:

`interactive-landscape(1).css`

![image](https://github.com/cncf/landscape/assets/5235127/8524cbe4-1a50-4d4b-8d4c-82e58c9a2339)

**Comment by RupeshHacker** [comment]
@adriens can you provide more screen shots from 1st step

**Comment by adriens** [comment]
Sure, I'm doing it :zap:

**Comment by adriens** [comment]
Here we go:


https://github.com/cncf/landscape/assets/5235127/361a4e7e-f186-460b-b3f2-93e03896b43d

**Comment by swinslow** [comment]
Same issue here. On Firefox for Mac, if I go to https://landscape.cncf.io/ and click "Download as CSV" on the left-hand side menu, the file that is downloaded has the name "interactive-landscape.css". This should presumably have a ".csv" extension instead of ".css".

**Comment by swinslow** [comment]
See also #3126 and https://github.com/cncf/landscapeapp/issues/866

**Comment by tegioz** [comment]
Hi!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io) and this issue should be resolved.

Please feel free to reopen if needed 🙂

**Comment by adriens** [comment]
Hi guys, I'm giving it a try rigt now and will let you know :zap:

**Comment by adriens** [comment]
They both are doing great : 

- :heavy_check_mark: `items.csv`
- :heavy_check_mark: `projects.csv`

:grey_question: Is there any static url that makes it possible to get csvs for example from `curl` :grey_question:

**Comment by tegioz** [comment]
Awesome 🙂

Yes, you can use:

- http://landscape.cncf.io/docs/items.csv
- http://landscape.cncf.io/docs/projects.csv

Please note that landscape2 is at an early stage of development and the content or location of those files could change 😇

**Comment by adriens** [comment]
Excellent :clap: 

I've just [tweeted about it](https://twitter.com/rastadidi/status/1748068794390684093) : 

![image](https://github.com/cncf/landscape/assets/5235127/96a963fd-0d1e-4346-a428-0f94931f1e92)
![image](https://github.com/cncf/landscape/assets/5235127/bb18f559-0fee-4e46-a392-4f6beb120189)
