### ISSUE TITLE
"Latest Release" and "Latest Commit" dates are not maintained

### ISSUE THREAD

**Issue by bluepuma77** [cncf/landscape#3599]
### Don't create an issue

What? The [page](https://landscape.cncf.io/guide#orchestration-management--service-proxy) has a link to "Report Issue" here. That does not make sense.

# Report issue

I quickly checked some proxies (Traefik, nginx, HAProxy) and all had "Latest Commit - 2 months ago" stated in the details box. 

This date is wrong, as is the "Latest Tweet - 7 months ago" date.

Traefik even has a "Latest Release - 4 months ago", which is just blatantly wrong.

Do you manually maintain those dates or is there a crawler program that is not working correctly anymore?

**Comment by tegioz** [comment]
Hi!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io) and this issue should be resolved.

Please feel free to reopen if needed 🙂
