### ISSUE TITLE
Adding Navops products to landscape

### ISSUE THREAD

**Issue by roblalonde** [cncf/landscape#36]
Please add the Navops product line to the Platforms sections per discussion with Dan Kohn.

http://navops.io

LOGOS ATTACHED:
![navops-logo](https://cloud.githubusercontent.com/assets/19596507/22656563/c14743e6-ec61-11e6-9325-8698b118642a.png)

**Comment by roblalonde** [comment]
updated per discussion.

**Comment by dankohn** [comment]
This should go in for 0.94.

**Comment by shawnpreissner** [comment]
Hi @roblalonde please find in 0.9.4 under Platforms https://github.com/cncf/landscape/blob/master/landscape/CloudNativeLandscape_v0.9.4.jpg

**Comment by roblalonde** [comment]
Thanks!!
