### ISSUE TITLE
use ghcr.io for this repo

### ISSUE THREAD

**Issue by cafkafk** [cncf/landscape#3626]
Since this project has a docker container, it would be valuable to distribute that container on the ghcr.io tied to this repo.

Here is an example from one of my projects https://github.com/cafkafk/rime/pkgs/container/rime.

This makes it a lot easier to use a project that includes a container.

**Comment by onlydole** [comment]
@castrojo - this might be a great use case for your GitHub Actions 😄

**Comment by castrojo** [comment]
Oooh! 

Hey @cafkafk if you want first dibs on this and want to adjust and PR your example then I'd be happy to review. Always happy to help someone get their first cncf contribution in!

Or if not I can put it on my list for next week! Thanks for filing this, we probably want/need this stuff in lots of places across the org.

**Comment by EyeCantCU** [comment]
Hi all,

I've drafted a PR for this here: https://github.com/cncf/landscape/pull/3634

It needs a key pair generated by cosign to successfully work

**Comment by castrojo** [comment]
I've generated a new cosign pair and PRed the new public key as #3636.    I've set the private key as SIGNING_KEY in the repo settings as expected. Just needs another set of eyes to double check, thanks ya'll!

**Comment by EyeCantCU** [comment]
Sounds great! I believe it needs to be SIGNING_SECRET and not SIGNING_KEY (apologies for not covering that)

**Comment by castrojo** [comment]
You're correct, I double checked and I got it right in the settings panel, but wrong in my comment. 😄 We should be good to go!

**Comment by tegioz** [comment]
Hi!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io) and this issue probably no longer applies. Landscape2 provides [a container image with the landscapes generator, in addition to some pre-built binaries for multiple platforms](https://github.com/cncf/landscape2#installation).

Please feel free to reopen if needed 🙂
