### ISSUE TITLE
Project card updates stopped 3 months ago

### ISSUE THREAD

**Issue by jonatan-ivanov** [cncf/landscape#3654]
Check project cards on https://landscape.cncf.io/. Lots of cards seems to be stale, e.g.:
```
Latest Commit 3 months ago
Latest Release 3 months ago
```
for projects that had commits/releases recently.

**Comment by krook** [comment]
@castrojo is this something you can take a look at?

**Comment by tegioz** [comment]
Hi!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io) and this issue should be resolved.

Please feel free to reopen if needed 🙂
