### ISSUE TITLE
Compress the therootcause.js

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#379]
https://developers.google.com/speed/pagespeed/insights/?utm_source=analytics&tab=desktop&url=http%3A%2F%2Flandscape.cncf.io%2F

<img width="701" alt="screen shot 2018-03-10 at 10 44 26 pm" src="https://user-images.githubusercontent.com/3083270/37249407-c5f4a0fa-24b4-11e8-9e3d-e83964b6d21f.png">

**Comment by ZeusTheTrueGod** [comment]
Done
