### ISSUE TITLE
Add Packet.net to the Infrastructure landscape layer

### ISSUE THREAD

**Issue by jacobsmith928** [cncf/landscape#38]
![packet_logo_rgb_black](https://cloud.githubusercontent.com/assets/7989673/21147371/c16d8cc8-c122-11e6-9503-ab3f599dad0c.png)
![packet_logo_rgb_blue](https://cloud.githubusercontent.com/assets/7989673/21147370/c1685fc8-c122-11e6-9b6d-64b7d0d2715a.png)
![packet_logo_rgb_darkteal](https://cloud.githubusercontent.com/assets/7989673/21147372/c180d8aa-c122-11e6-9b5a-9ba6798e57d0.png)
![packet_logo_rgb_pink](https://cloud.githubusercontent.com/assets/7989673/21147373/c18173be-c122-11e6-85ad-85a17d83dc8b.png)

**Comment by shawnpreissner** [comment]
Packet's now included under Infrastructure in v0.9.3
