### ISSUE TITLE
Tree shake unused lodash modules

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#380]
https://github.com/lodash/babel-plugin-lodash
https://github.com/lodash/lodash-webpack-plugin

More details: https://medium.com/@martin_hotell/tree-shake-lodash-with-webpack-jest-and-typescript-2734fa13b5cd

**Comment by ZeusTheTrueGod** [comment]
First we need to prove that it is a problem at this moment. Need to run a webpack analyzer first

**Comment by ZeusTheTrueGod** [comment]
Ok, so first attempt was to replace 'lodash' with 'lodash-es', but this did not help. Size is same, even 10kb more. Not sure how much unused lodash code is in the bundle

**Comment by ZeusTheTrueGod** [comment]
I can not get any advantages

**Comment by ZeusTheTrueGod** [comment]
Tried both lodash-es and babel plugin for a lodash.

**Comment by dankohn** [comment]
Please look at:

https://advancedweb.hu/2017/02/07/treeshaking/

Did you try both:

https://github.com/lodash/babel-plugin-lodash and
https://github.com/lodash/lodash-webpack-plugin

I didn't think you were using many lodash methods, so I'm surprised it can't shake the rest out.

**Comment by ZeusTheTrueGod** [comment]
May be it is already removed, but I'll check again

**Comment by ZeusTheTrueGod** [comment]
I had to try them both

**Comment by dankohn** [comment]
The difference should show up on the map.

**Comment by ZeusTheTrueGod** [comment]
689kb vs 760kb

**Comment by dankohn** [comment]
Can you post the maps before and after?

**Comment by ZeusTheTrueGod** [comment]
That would not be easy, html is not supported here

**Comment by ZeusTheTrueGod** [comment]
![image](https://user-images.githubusercontent.com/230982/37487540-dc424910-28a2-11e8-9e5b-06cfeaff3be4.png)

**Comment by ZeusTheTrueGod** [comment]
![image](https://user-images.githubusercontent.com/230982/37487718-7703a764-28a3-11e8-8e7a-e0b07ab92f94.png)

**Comment by ZeusTheTrueGod** [comment]
It was a pretty big lodash.js

**Comment by dankohn** [comment]
Please look at why material-ui isn't getting tree shaked: https://material-ui-next.com/guides/minimizing-bundle-size/

**Comment by dankohn** [comment]
Please re-add https://github.com/cncf/landscape/commit/f33a58f92cb64d3b382f8d0b52daeabcf6ec6c60
