### ISSUE TITLE
On-Prem | I think this doesn't exist anymore

### ISSUE THREAD

**Issue by SamuelMarks** [cncf/landscape#3814]
Clicking through all the interesting projects in your CNCF landscape and came across this one:

https://landscape.cncf.io/?item=app-definition-and-development--application-definition-image-build--on-prem

![image](https://github.com/cncf/landscape/assets/807580/5b72a089-aaea-4f3c-97ab-ba350ea4346e)

The website is all placeholder and I can't see a codebase. Their Twitter hasn't updated in 2 years also https://twitter.com/on_premises
https://on-premises.com

**Comment by caniszczyk** [comment]
fixed, thank you!
