### ISSUE TITLE
Googlebot can't access hundreds of images

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#387]
https://www.google.com/webmasters/tools/googlebot-fetch-details?hl=en&authuser=0&siteUrl=https://landscape.cncf.io/&path&timestamp=1520808081774

And yet some images are working because the preview looks good.

**Comment by dankohn** [comment]
I just confirmed that none of the images that are marked "Temporarily unreachable" are shown in the preview. So, I suspect it's timing out without being able to download the rest of the images.

Hopefully, adding them to the sitemap in #384 might fix the issue.

**Comment by ZeusTheTrueGod** [comment]
Actually what happens here - first a small set of items is loaded and completely displayed - about 20. Google properly renders it , after that a full list of items is loaded and, as I guess, google tried to draw those images too. And then a timeout occurs.

**Comment by dankohn** [comment]
So then, it's probably worth testing whether if we remove the preview.json, would Google succeed in fetching all the images? Or at least more of them?

Or does none of this matter because of sitemaps?

Let's do nothing for a few days until we confirm that our sitemaps are getting the pages into Googe's index. Then we can reconsider this.

**Comment by ZeusTheTrueGod** [comment]
Ok

**Comment by dankohn** [comment]
Duplicate of #677
