### ISSUE TITLE
Dynamically alter robots.txt on build

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#395]
Please set the robots.txt on master to:
```txt
User-agent: *
Disallow:

Sitemap: http://landscape.cncf.io/sitemap.xml
````

Set the robots.txt on non-master branches to:
```txt
User-agent: *
Disallow: /
```
This will stop Google from accidentally indexing any of our staging branches.

**Comment by ZeusTheTrueGod** [comment]
I don't understand what is a `/file.html` here , as well as how google can index our  staging branches.
Anyway, I'll add this feature.

**Comment by dankohn** [comment]
Sorry, I had a typo, hopefully the edited version above makes more sense.

**Comment by dankohn** [comment]
Without this, Google could find our staging servers via the links on GitHub. Now they can't.
