### ISSUE TITLE
Illustrator logo work

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#396]
I'm trying to get a vector image for Apache Zookeeper. Here's what it should look like: 
https://landscape.cncf.io/selected=apache-zookeeper

For source material, I have this 30 MB raster image:
https://svn.apache.org/repos/asf/zookeeper/logo/zookeeper.psd

Would you or someone in your org be able to trace that image and produce an AI file that could then be converted to an SVG. If you don't, or if it would take more than a couple hours, feel free to say no.

**Comment by alexkontsevoy** [comment]
@dankohn I can redraw the image to create SVG, it will take about an hour or so.

**Comment by dankohn** [comment]
Great!

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation  https://www.cncf.io
+1-415-233-1000  https://www.dankohn.com

**Comment by dankohn** [comment]
I'd also be interested in SVG versions of:
https://microsoftventures.com/wp-content/uploads/2017/02/snaproute-1.png

and

https://landscape.cncf.io/selected=snap
https://cdn-images-1.medium.com/max/1200/1*tLW51OFkeCFEakieBAqcBg.png

and

https://landscape.cncf.io/selected=clay
https://camo.githubusercontent.com/ff012baa43717b743cb673c6cb663a253a8e0de3/687474703a2f2f692e696d6775722e636f6d2f5a3076764c6b492e706e67

and

https://landscape.cncf.io/selected=sheepdog

and

https://landscape.cncf.io/selected=infrakit

**Comment by alexkontsevoy** [comment]
[zookeeper.zip](https://github.com/cncf/landscape/files/1826141/zookeeper.zip)

@dankohn  Archive contains 2 SVGs, with reflection:

![image](https://user-images.githubusercontent.com/4476098/37611882-c4c0499e-2bcd-11e8-94a7-6451abad1996.png)

and without:

![image](https://user-images.githubusercontent.com/4476098/37611892-ce4f167a-2bcd-11e8-8508-ea152a0179b5.png)

**Comment by dankohn** [comment]
Gorgeous. I need no reflection but add the name like:
https://landscape.cncf.io/selected=apache-zookeeper

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by alexkontsevoy** [comment]
@dankohn here it is:

[Uploading zookeeper.svg.zip…]()

**Comment by dankohn** [comment]
@alexkontsevoy That one looks great. Could you please do the 4 others.

**Comment by dankohn** [comment]
Not essential, but it would be nice if you could create a pull request to go along with the next 4. Note that after adjusting the logo entries in `landscape.yml` you run `yarn fetch` to update the dependent files.
