### ISSUE TITLE
Add Aqua Security to the Secure Images Category

### ISSUE THREAD

**Issue by jerbia** [cncf/landscape#40]
Aqua Security enables enterprises to secure their virtual container environments from development to production, accelerating container adoption and bridging the gap between DevOps and IT security.

Web site: https://www.aquasec.com
Logo: https://get.aquasec.com/aqua_logo_fullcolor.svg

**Comment by shawnpreissner** [comment]
Aqua Security now included under Secure Images in v0.9.3
