### ISSUE TITLE
Add card-only version for iframe embedding

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#400]
We want to be able to embed the landscape in an iframe. When `embed=yes` please don't display the header or the filter bar. Just show the cards and the footer.

Here's an example of an embed:

https://www.dankohn.com/test

**Comment by dankohn** [comment]
Intention is to replace the logos on https://www.cncf.io/certification/kcsp/. It would also be nice to turn off the internal links in the cards (on company, member, not open source). External links are still fine.

Also, please figure out the Javascript to use for embedding to have the height adjust automatically.
https://stackoverflow.com/questions/9162933/make-iframe-height-dynamic-based-on-content-inside-jquery-javascript

**Comment by dankohn** [comment]
Please also add a new footer in a large font saying "[View](https://landscape.cncf.io/grouping=landscape&landscape=special) the full interactive landscape." and have it open in a new tab.

**Comment by dankohn** [comment]
And please remove the card count line at the top in embed mode.

**Comment by dankohn** [comment]
Better iframe resizing solution: https://github.com/davidjbradshaw/iframe-resizer

**Comment by ZeusTheTrueGod** [comment]
It is not that simple. When I use that iframe-resizer, the popup works absolutely improperly.
I am going to publish the solution to the `/embed.html`
