### ISSUE TITLE
Atlantis logo

### ISSUE THREAD

**Issue by gecube** [cncf/landscape#4047]
There are no Atlantis logo despite it was added here:

https://github.com/cncf/landscape/pull/3941/files

![Image](https://github.com/user-attachments/assets/0a72f48b-2620-4d3a-897a-eae8b6bd86a8)
![Image](https://github.com/user-attachments/assets/49e30c9f-0f69-43f8-99ee-a84642e3c7f5)

**Comment by gecube** [comment]
Hi, @chenrui333 

Could you kindly elaborate on this issue? I see that only PNG image is available.

**Comment by thetwopct** [comment]
> There are no Atlantis logo despite it was added here:
> 
> https://github.com/cncf/landscape/pull/3941/files

No logo was included in the PR - the .yml update references "atlantis.svg" but that file was not included in the PR and is not in the hosted_logos directory.

I've [opened a PR](https://github.com/cncf/landscape/pull/4082) to get a basic logo added so the CNCF website doesn't look broken. You can update it once your final logo is ready. And of course, please submit the artwork to the CNCF Artwork repo https://github.com/cncf/artwork

**Comment by thetwopct** [comment]
The PR has been [approved](https://github.com/cncf/landscape/pull/4082) and waiting to be deployed. This issue can be closed (cc @castrojo)
