### ISSUE TITLE
Add hotkeys

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#406]
Typing `space` should open the first card shown. `r` should reset filters. `1` to `6` should trigger the 6 example filters.

**Comment by ZeusTheTrueGod** [comment]
And how will people guess that?
Also, is not space reserved for scrolling ?

**Comment by dankohn** [comment]
The cool thing would be to have `?` bring up a modal showing the shortcuts, as works with Gmail and Google Calendar. Of course, you're right about `space`; `return` would be a better choice. Interestingly, `esc` already works to dismiss the modal.
