### ISSUE TITLE
OpenStack projects forthcoming...

### ISSUE THREAD

**Issue by DFFlanders** [cncf/landscape#41]
We've been working on listing which OpenStack projects we should be placed in each box, for example (feedback welcome prior to submitting pull request):

Provisioning (infra automation) = Heat
Provisioning (secure image) = Nova / Glance
Runtime (cloud native storage) = Swift / Cinder
Container Runtime = Zun
Cloud Native Network = Neutron
Service Management = Shade

Coincidentally, we have new logos for each of these projects :)

**Comment by shawnpreissner** [comment]
Hi @DFFlanders we currently have OpenStack under Infrastructure. Would you prefer having separate projects on Velocity [()](https://github.com/cncf/velocity/pull/2) and the Landscape, or one collection of projects represented on each?

**Comment by shawnpreissner** [comment]
Hi @DFFlanders, closing as we've included OpenStack in the most recent version https://github.com/cncf/landscape#current-version
