### ISSUE TITLE
Moving between modals on mobile should bring you back to the top

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#413]
On a desktop, when moving between modals, you come back to the top.

On mobile, you don't, but should.

**Comment by ZeusTheTrueGod** [comment]
Are we talking about scrolling ?

**Comment by dankohn** [comment]
Yes, scrolling. Behavior is correct on desktop.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by ZeusTheTrueGod** [comment]
I still want to reproduce it. I scroll down, click on a random card, click right few times, then I close the modal. The scrolling position is still the same.

My intention was to scroll to the top when someone changes a filter.

**Comment by dankohn** [comment]
No, I'm saying scrolling with a modal. Open a modal, scroll down a little,
and click right. It should bring you back to the top of the next modal.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by ZeusTheTrueGod** [comment]
Thanks, now I understand what is the  problem
