### ISSUE TITLE
Add Librato to Monitoring

### ISSUE THREAD

**Issue by leecalcote** [cncf/landscape#43]
As a time series metrics monitoring solution, please add [Librato](https://www.librato.com) to the Monitoring section.

**Comment by dankohn** [comment]
+1

**Comment by shawnpreissner** [comment]
Added

**Comment by shawnpreissner** [comment]
Hi @leecalcote please find in 0.9.4 https://github.com/cncf/landscape/blob/master/landscape/CloudNativeLandscape_v0.9.4.jpg
