### ISSUE TITLE
Add native scrollbars to filter bar

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#433]
When the window is too short to show the whole filterbar, it now scrolls due to #402.

Please add native scrollbars to the filterbar, only when scrolling is enabled (because of a short window).

@alexkontsevoy says a React plugin is needed.

![image](https://user-images.githubusercontent.com/3083270/37606691-77b31f8e-2b6c-11e8-9f95-41b08ee812b5.png)

**Comment by alexkontsevoy** [comment]
@dankohn The default (as on image) scrollbars can be added without any plugin

**Comment by dankohn** [comment]
Yes. but only when window is short enough for it to be scrollable.
