### ISSUE TITLE
Update Azure logo?

### ISSUE THREAD

**Issue by johngossman** [cncf/landscape#47]
The Azure logo in the landscape document is from the bad-old-days when it was Windows Azure. Could we use this one instead
![azurelogo](https://cloud.githubusercontent.com/assets/6045039/21361726/1b488262-c69a-11e6-97da-2e825f3a2f38.png)

**Comment by dankohn** [comment]
Thanks, John. We'll fix in the next iteration, but the one you linked to isn't high resolution enough. Could you please provide a link, preferably to an SVG that includes the word "Azure".

**Comment by dankohn** [comment]
https://azure.microsoft.com/svghandler/dns/?width=600&height=315

**Comment by dankohn** [comment]
Please add.

**Comment by shawnpreissner** [comment]
Added in 0.94

**Comment by shawnpreissner** [comment]
Hi @johngossman please find in 0.9.4 https://github.com/cncf/landscape/blob/master/landscape/CloudNativeLandscape_v0.9.4.jpg
