### ISSUE TITLE
Adjust meaning of 2 months ago

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#472]
Please compare the last commit values from https://landscape.cncf.io/grouping=no&license=open-source&sort=latest-commit to what shows on GitHub. We often show 3 months ago when GitHub shows 2 months ago. Can you please adjust our logic to match their's.

**Comment by ZeusTheTrueGod** [comment]
I'm not able to reproduce that issue. I've checked those items which have 'latest commit' of 3 months ago, they look valid.

**Comment by dankohn** [comment]
For example, go to https://landscape.cncf.io/grouping=no&license=open-source&selected=my-sql&sort=latest-commit and it says last commit 4 months ago. Then click on the GitHub repo (and this is key) click on branches, and you'll see that it says 3 months ago. I'm seeing very consisten differences.

The simplest way to understand my request is that I'd like you to adjust our months ago logic to match that of: http://api.rubyonrails.org/classes/ActionView/Helpers/DateHelper.html#method-i-distance_of_time_in_words_to_now
