### ISSUE TITLE
Adjust breakpoints to allow 4 columns

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#481]
Look at https://landscape.cncf.io/embed.html while widening and narrowing the window. It jumps from 3 columns to 5. Also, after 5, the cards stay the same size and there is extra grey space on the right.

Instead, adjust breakpoints so that 4 columns are shown at the appropriate width, and that the width of cards widens to make use of any extra space.

Cc @ZeusTheTrueGod

**Comment by alexkontsevoy** [comment]
@dankohn the embedded version has no filters column, that's why the layout becomes different

@ZeusTheTrueGod I need some special class added to the body element for embedded version to write rules for it

**Comment by dankohn** [comment]
Sounds good, but you could go ahead and do the other part, which is to have the cards get wider to cover empty space like happens for 1 to 3 columns, but at higher column numbers as well.

**Comment by ZeusTheTrueGod** [comment]
Done, I've added the 'embed' class to the body in the embedded mode. I've pushed this directly to the master.

**Comment by ZeusTheTrueGod** [comment]
@alexkontsevoy
