### ISSUE TITLE
Logos need to shrink more on mobile portrait 

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#492]
They’re not shrinking enough:

https://www.cncf.io/certification/software-conformance/

![9af07db9-178c-4706-bfeb-7c16768610f8](https://user-images.githubusercontent.com/3083270/38195121-d0581e0e-3649-11e8-972a-30be1c71273c.png)

**Comment by alexkontsevoy** [comment]
@dankohn this one is resolved, you can check and close

**Comment by dankohn** [comment]
Sorry, my phone broke and I needed to get my new one to confirm this was resolved.
