### ISSUE TITLE
Autocrop SVGs

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#500]
Please autocrop SVGs. Since you're always displaying them with a border, I'm not sure that any transparent border is necessary.

Once working, please run on all cached SVGs.

Example that needs it: https://github.com/cncf/landscape/blob/master/hosted_logos/amazon-eks.svg

**Comment by dankohn** [comment]
Please leave a 1 pixel border around each logo so the logo is useful in other circumstances.

**Comment by dankohn** [comment]
Logos that aren't yet being autocropped:

https://500-andrey-crop-borders--landscape.netlify.com/selected=azure-functions
https://500-andrey-crop-borders--landscape.netlify.com/selected=azure-registry
https://500-andrey-crop-borders--landscape.netlify.com/selected=bosh
https://500-andrey-crop-borders--landscape.netlify.com/selected=concourse
https://500-andrey-crop-borders--landscape.netlify.com/selected=digital-ocean

These look distorted in the card view but not in the modal:
https://500-andrey-crop-borders--landscape.netlify.com/selected=cloudbees
https://500-andrey-crop-borders--landscape.netlify.com/selected=cloud-ops-kcsp
https://500-andrey-crop-borders--landscape.netlify.com/selected=codefresh
https://500-andrey-crop-borders--landscape.netlify.com/selected=container-pilot
https://500-andrey-crop-borders--landscape.netlify.com/selected=containership
https://500-andrey-crop-borders--landscape.netlify.com/selected=core-os-kcsp
https://500-andrey-crop-borders--landscape.netlify.com/selected=easy-stack-kubernetes-service-eks

I'll stop there.

**Comment by dankohn** [comment]
Great improvements. Some problems:

Every logo looks smaller in it's modal. Please change the modal to use the same 1 or 2 px transparent border like you see in the card view.

Corrupted:
https://500-andrey-crop-borders--landscape.netlify.com/grouping=no&selected=apprenda-kismatic-enterprise-toolkit-ket
https://500-andrey-crop-borders--landscape.netlify.com/logos/hadoop.svg

Squashed:
https://500-andrey-crop-borders--landscape.netlify.com/grouping=no&selected=pure-sec

Bottom is cut off:
https://500-andrey-crop-borders--landscape.netlify.com/grouping=no&selected=avi-networks

Left side cut off:
https://500-andrey-crop-borders--landscape.netlify.com/logos/container-solutions-kcsp.svg
https://500-andrey-crop-borders--landscape.netlify.com/grouping=no&selected=couchbase

Not cropped:
https://500-andrey-crop-borders--landscape.netlify.com/grouping=no&selected=buildkite
https://500-andrey-crop-borders--landscape.netlify.com/grouping=no&selected=claudis-js

Off center:
https://500-andrey-crop-borders--landscape.netlify.com/grouping=no&selected=my-sql

**Comment by dankohn** [comment]
Could you please move https://github.com/cncf/landscape/blob/500-andrey-crop-borders/tools/processSvg.js#L112 to the top and comment that `// 2% margin on each side of the image`.

Could you please write https://github.com/cncf/landscape/blob/500-andrey-crop-borders/tools/processSvg.js#L108 into a temp directory so it doesn't accidentally get copied. More descriptive names than `result.png` and `result2.png` would be nice as well.

In general, I don't fully get your algorithm and would love if you could add 5 or 6 comments showing where each of the major steps starts, and what it's going to be doing.

**Comment by ZeusTheTrueGod** [comment]
those result.png were used only for a debug purpose, so I could see an intermediate result during debugging

**Comment by ZeusTheTrueGod** [comment]
Overall, we draw an svg with a pretty big viewbox around it, render it to png, spot a proper region and than apply that region coordinates to the original coordinate of the svg, making a proper viewbox

**Comment by ZeusTheTrueGod** [comment]
I'll clean up a code and will add extra comments
