### ISSUE TITLE
Convert remaining PNGs to SVGs

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#503]
Please create SVGs for the following. If you have any questions about shape, go the company or product homepage and look for their logos. Or just ask. Thanks!

CloudOps: https://citrixready.citrix.com/content/dam/ready/partners/cl/cloudops-inc/CloudOps-RGB-Stacked%20(1).png

Cloudbees: https://blog.xebialabs.com/wp-content/uploads/2017/03/cloudbees-logo_4.png

Codefresh: Please convert https://codefresh.io/wp-content/uploads/2018/03/Codefresh-Registry.svg into Codefresh logo https://crunchbase-production-res.cloudinary.com/image/upload/v1470258929/hhinf38lttfyrjbz1h3t.jpg

Docker Compose: https://www.unixmen.com/wp-content/uploads/2017/06/docker-compose-logo.png

ContainerPilot: https://raw.githubusercontent.com/alexcontini/alexcontini.github.io/master/ContainerPilot-logo%20(1)-01.png

Containership: http://resumator.s3.amazonaws.com/customer_20150721151308_KZ8QDZPO4BOHCKCU/social_icons/20150825133703_containership_logo.png and see https://camo.githubusercontent.com/ae241fe4a1d04287cbb9ac274f2b1a5653aa9824/68747470733a2f2f63646e2e636f6e7461696e6572736869702e696f2f696d616765732f43535f5465616c477265795356472e737667

CoreOS: Stacked version of https://upload.wikimedia.org/wikipedia/commons/8/8c/CoreOS.svg that looks like https://s-media-cache-ak0.pinimg.com/originals/8d/4b/d4/8d4bd4b4011e8cd7c5c0b1478855f21d.jpg

Daocloud: https://opencollective-production.s3-us-west-1.amazonaws.com/6d959930-b283-11e7-aea9-770057e229d7.png

Docker Registry: https://blog.docker.com/media/2015/11/logo-title-final-registry-2.png

Easystack: https://easystack.cn/static/cn/images/easystack-logo.png

Gluster: Use https://community.redhat.com/images/software/gluster.svg?1478100396 to look like http://community.redhat.com/images/branding/logo-gluster.png

Hedvig: https://www.hedviginc.com/hs-fs/hub/448929/file-2664694225-png/Press_Kit/Hedvig-Logo/HedvigVerticalLockup-HighResPNG.png?t=1511209134101

IronDB: https://login.circonus.com/resources/docs/irondb/assets/irondb-logo-1777x761.png

Kong: Convert https://2tjosk2rxzc21medji3nfn1g-wpengine.netdna-ssl.com/wp-content/themes/konghq/assets/img/Kogo.svg to look like https://camo.githubusercontent.com/9f17544e4c068845f6bc81053b9eb9b640a63afe/68747470733a2f2f636c2e6c792f3033305631753032303930512f756e6e616d65642e706e67

Mesosphere: Convert https://www.nutanix.com/wp-content/uploads/2017/03/logo_mesosphere.svg to look like https://mesosphere.com/wp-content/uploads/2017/11/mesosphere-logo.png

Mirantis: https://www.mirantis.com/wp-content/uploads/2017/01/mirantis-logo-2color-rgb-transparent.png

Netsil: https://s3.amazonaws.com/docs.netsil.com/logos/Netsil_640x640-blue.jpg

Nuage Networks: Convert http://www.nuagenetworks.net/wp-content/themes/nuage/img/logo-side-black.svg to look like https://user-images.githubusercontent.com/6019102/29992977-e6e92a02-8f5d-11e7-855b-0bf748f13dd9.png

OpenAPI: Crop https://github.com/OAI/OpenAPI-Style-Guide/blob/master/graphics/vector/OpenAPI_Logo_Stacked_Pantone.svg

Portworx: https://portworx.com/wp-content/themes/portworx/images/portworx-logo.png

Puresec: https://cybersecurity-excellence-awards.com/wp-content/uploads/2018/01/210777.png that looks like https://landscape.cncf.io/logos/pure-sec.png

runV: https://user-images.githubusercontent.com/1701782/29455671-ab0078ca-8444-11e7-8a7c-f3b41fa1954d.png

scylla: https://www.mikelangelo-project.eu/wp-content/uploads/2015/03/LOGO2.png

server denisty: Make https://opzzz.sh/static/images/logos/server-density-black.svg look like https://www.gcppodcast.com//images/post/serverdensity.png

SmartOS: Make http://cuddletech.com/img/smartos-blue.png stacked like https://blog.newrelic.com/wp-content/uploads/smartos-stacked-blue-150x150.png

Zipkin: https://4.bp.blogspot.com/-DsmFcaeMi4U/T9DX_XLMrdI/AAAAAAAAABg/jKF_pXToIEo/s1600/zipkin.jpg

**Comment by dankohn** [comment]
Please also convert the Cloudify logo https://cloudify.co/wp-content/uploads/2017/04/cloudify-logo.svg to be stacked like https://amartus.com/wp-content/uploads/2017/10/Cloudify-Logo-Vertical.png

**Comment by alexkontsevoy** [comment]
@dankohn planned for today (Apr 6)

**Comment by dankohn** [comment]
Please create a new SVG of StackPointCloud: https://stackpoint.io/images/spc-logo-modern-left.c8908e33.png

**Comment by dankohn** [comment]
Please create a new SVG for Dashbird that looks like their logo on https://dashbird.io/pricing/ and uses SVG versions of https://dashbird.io/images/dashbird-logo.png and https://dashbird.io/images/dashbird-wordmark@2x.png

**Comment by dankohn** [comment]
Please convert ArangoDB https://landscape.cncf.io/logos/arango-db.svg to be stacked like https://secure.meetupstatic.com/photos/member/3/3/7/1/thumb_265153169.jpeg

**Comment by dankohn** [comment]
Great work.  Please rename daocluod.svg to daocloud.svg.

Please change the white to transparent on docker-registry.svg.

Bring back the grasshoper on gluster.svg.

Make the white inside the letters of portworx.svg to be transparent.

**Comment by alexkontsevoy** [comment]
@dankohn updated, please check

**Comment by coopr** [comment]
@dankohn sorry for my delay - do I still need to get this done for Kong?

**Comment by dankohn** [comment]
@coopr If you're happy with https://landscape.cncf.io/grouping=landscape&landscape=service-management&selected=kong there's nothing you need to do.

**Comment by coopr** [comment]
Perfect, I'm happy, thanks @dankohn
