### ISSUE TITLE
Please move HAProxy logo to "CNCF member products/projects" section

### ISSUE THREAD

**Issue by jonbrack** [cncf/landscape#517]
### Don't create an issue

If you see an error in the cards or missing ones, please don't create an issue here. Instead, edit landscape.yml (you can even do it via the GitHub web interface) and open a pull request. Then, review the preview staging server that's posted to your pull request and add a comment if your new or updated card looks correct and is ready to merge. Before going forward, please carefully review the sections of the Readme covering new entries, corrections, and logos: https://github.com/cncf/landscape/blob/master/README.md.

**Comment by dankohn** [comment]
Resolved just now with https://github.com/cncf/landscape/commit/00dedd8d77a6c160d7626ce8180cfe8aa418f39c

https://landscape.cncf.io/selected=ha-proxy

Welcome to CNCF. And thanks again to Willy for his help setting up an up-to-date mirror.
