### ISSUE TITLE
Add Weaveworks logo to Cloud Native Network

### ISSUE THREAD

**Issue by abuehrle** [cncf/landscape#52]
Weave Net repo is here: 

https://github.com/weaveworks/weave

![weaveworks_colour_logo_pos_rgb_300px](https://cloud.githubusercontent.com/assets/13420383/21364393/46e95876-c6b6-11e6-8531-44ef7f78a81d.png)

**Comment by dankohn** [comment]
+1

**Comment by shawnpreissner** [comment]
Hi @abuehrle please find in 0.9.4 https://github.com/cncf/landscape/blob/master/landscape/CloudNativeLandscape_v0.9.4.jpg
