### ISSUE TITLE
Can we print the landscape picture and share with others ?

### ISSUE THREAD

**Issue by tdy218** [cncf/landscape#526]
Like the title, can we print the landscape picture and share with others in our technology sharing conference for free without any changes ?

**Comment by dankohn** [comment]
Yes, please do so. The static landscape is distributed under the Creative Commons Attribution license, so you're welcome to distribute it as long as you leave the CNCF logo on it. 

https://github.com/cncf/landscape#license

We prefer printing it with the cloud native trail map on one side and the landscape on the other. Please be sure to use the PDF to get acceptable resolution for print.

https://github.com/cncf/landscape#formats

I would be curious to hear what event you'll be distributing it at.
