### ISSUE TITLE
Please try again on Romana

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#533]
https://github.com/cncf/landscape/blob/8cd876fd12a2e61ce00ff883f167cb9dfd02ffbc/hosted_logos/romana.svg is not up to your usual high level of work. The text looks fine but the windows look broken.

I know http://romana.io/images/Logo.250.png is low res but it's unfortunately all we have to work with.

**Comment by alexkontsevoy** [comment]
@dankohn ok, I'll try to recreate the logo today

**Comment by alexkontsevoy** [comment]
@dankohn updated the SVG version. Note that windows and other lines are still not straight, but this imperfectness is copied from original, I believe the logo was designed this way intentionally.
