### ISSUE TITLE
Create new "Application Segmentation" category under "Application Definition & Development"

### ISSUE THREAD

**Issue by aporeto-amir** [cncf/landscape#54]
Trireme (https://github.com/aporeto-inc/trireme - open source) in an application segmentation (security) library that currently works with Kubernetes.  Plugins for Mesos, Swarm, and other orchestration and management components soon.  

Trireme authenticates containers and authorizes access based on network policy without any centralized controller.  

Trireme requires its separate category because of its unique functionality.  Its logo can is at https://www.aporeto.com/wp-content/uploads/2016/10/trireme-logo-final-b.png

Thanks!

**Comment by shawnpreissner** [comment]
Hi @aporeto-amir we will add you to the next release. I understand how it can be viewed as a separate category, unfortunately, we'll have to include Trireme in a currently present one; is Application Definition best?

**Comment by aporeto-amir** [comment]
Hi, @shawnpreissner - thanks for the note.  May I suggest the following solution?

- Aporeto in "Cloud Native Network" and "Monitoring."
- Trireme in "Cloud Native Network."

This approach captures the natures of Aporeto and Trireme and provides better categorization.

**Comment by shawnpreissner** [comment]
Thanks for your input @aporeto-amir due to real estate challenges, we're limiting to one and will be able to include Trireme in Cloud Native Network. Please look for in the upcoming release.

**Comment by shawnpreissner** [comment]
Thanks @aporeto-amir, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
