### ISSUE TITLE
New badges design

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#548]
Could you please suggest improved styling for our badges. The colors we're using now are a little garish. There does seem to be an advantage to having different colors, but I'm open to other combinations or ideas.

<img width="320" alt="screen shot 2018-04-15 at 4 30 01 pm" src="https://user-images.githubusercontent.com/3083270/38783034-b6d480b8-40ca-11e8-87fc-dbb2703df207.png">

<img width="332" alt="screen shot 2018-04-15 at 4 30 27 pm" src="https://user-images.githubusercontent.com/3083270/38783035-bac8c490-40ca-11e8-870c-d96accdd6300.png">

**Comment by alexkontsevoy** [comment]
@dankohn I think we can make the badges more subtle, or even grayscale

![badges-03](https://user-images.githubusercontent.com/4476098/38864070-630fef0c-425b-11e8-8738-526cbbd9199e.png)

![badges-02](https://user-images.githubusercontent.com/4476098/38864071-63438362-425b-11e8-9ad5-6390c7239cda.png)

![badges-01](https://user-images.githubusercontent.com/4476098/38864073-636c063e-425b-11e8-9761-f2bc19181c52.png)

We can also go with text version:

![badges-04](https://user-images.githubusercontent.com/4476098/38864438-8e5aa7e6-425c-11e8-8f29-83ad472557cb.png)

**Comment by dankohn** [comment]
Thanks. I prefer different colors, but those pastels are too light. Could you please try some other combinations.

**Comment by dankohn** [comment]
Let's go with the first one here. Also, please make CNCF bold in CNCF
silver member. Thanks.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com
