### ISSUE TITLE
AppDynamics is in "monitoring" but does much more

### ISSUE THREAD

**Issue by jkowall** [cncf/landscape#55]
AppDynamics does tracing for every transaction with low overhead and no code changes, hence it's a tracing tool as well.

AppDynamics does log analytics the same as the other tools in logging.

**Comment by ichekrygin** [comment]
@jkowall just out of curiosity, what is AppD support story for containerized environments?

**Comment by dankohn** [comment]
We're generally limiting companies to one box.
