### ISSUE TITLE
OpenTracing is not a solution nor a standard 

### ISSUE THREAD

**Issue by jkowall** [cncf/landscape#57]
OpenTracing sounds great on paper, and it helps the developer of software to implement tracing. It doesn't help vendors implement standard tracing technologies on the backend. Each tracer needs different code, which defeats the purpose. Since OpenTracing cannot be used alone it doesn't make sense to include. Zipkin includes both the technology to collect and visualize along with the instrumentation technologies. Hence it makes sense to include.

**Comment by dankohn** [comment]
I don't believe your understanding of OpenTracing is up to date. I'd encourage you to read their documentation for framework developers: http://opentracing.io/documentation/pages/instrumentation/instrumenting-frameworks

More generally, it is rather unlikely that CNCF would leave a CNCF-hosted project off of the CNCF Cloud Native Landscape.

Cc @bensigelman

**Comment by bensigelman** [comment]
@jkowall thanks for bringing this up. Given our prior (1:1) chats, etc, I am assuming that you want/expect OpenTracing to be a toolkit for vendors creating black-box tracing systems, much like the AppD APM product. Of course that is simply not what OpenTracing is at the moment. This has always been out in the open, and in fact has been part of the OpenTracing docs for a while now:

http://opentracing.io/documentation/pages/instrumentation/common-use-cases#opentracing-priorities

And in this blog post I tried to lay out a clear description of the problem OpenTracing is trying to solve: https://medium.com/opentracing/towards-turnkey-distributed-tracing-5f4297d1736#.dyvj9uo46

To quote from the above:

> If distributed tracing is so valuable, why doesn’t everyone do it already?
>
> Because tracing instrumentation has been broken until now.
>
> ...
>
> And there’s the rub: It is not reasonable to ask all OSS services and all OSS packages and all application-specific code to use a single tracing vendor; yet, if they don’t share a mechanism for trace description and propagation, the causal chain is broken and the traces are truncated, often severely. **We _need_ a single, standard mechanism to describe the behavior of our systems.**

Regarding OpenTracing and CNCF, the alignment from a "mission" standpoint seems clear enough to me... from the [OpenTracing/CNCF proposal](https://github.com/cncf/toc/blob/master/proposals/opentracing.adoc):

> Regarding CNCF’s charter mission, OpenTracing is specifically concerned with making loosely-coupled [micro]services easier to manage. As such, it is strongly aligned with CNCF and its goal to “significantly increase the overall agility and maintainability of applications” by “[making] technology ubiquitous and easily available through reliable interfaces.” Indeed, OpenTracing and CNCF as a whole mutually benefit one another. (It should be noted that, as it is focused on standard instrumentation more than standard encoding formats, OpenTracing today is most relevant at the application layer; it has few specific opinions about — or strong dependencies on — the container layer or orchestration systems more generally, though service discovery and high-quality tracing are symbiotic.)

All of that said, I agree completely that OpenTracing doesn't "do" anything – its success as a project will be determined by the quality and quantity of integrations out in the wild. In my (candid) opinion, we are still in very early days... OpenTracing wasn't even a stable API until a few months ago and 95% of the important integration work is still ahead of us. But the project has good momentum from vendors and OSS projects alike and there is good reason to be optimistic about its ability to reduce integration effort for third-party OSS projects, monitoring vendors, and (microservice) application developers. Indeed we have already seen encouraging things from all three of those core constituencies.

Getting back to your particular concern about utility libs / etc for those building `Tracer` implementations: there are actually such things in several languages, though I guess you either didn't find them or didn't deem them useful. I am personally supportive of additional work in that area, though frankly there are already a bunch of vendors that were able to build OpenTracing support in a matter of a week or two of IC engineering effort, and there are a few other big-name vendors with (unannounced) plans to announce OpenTracing integrations in 2017... none of the above seemed concerned about the lack of utility libraries, so again it hasn't been a priority.

PS: As for Zipkin, I couldn't agree more about adding it to CNCF. You can see the Zipkin community debate the issue [here](https://github.com/openzipkin/openzipkin.github.io/issues/51#issuecomment-253290701) (and you can read my personal $0.02 on the subject [in this comment on that issue](https://github.com/openzipkin/openzipkin.github.io/issues/51#issuecomment-253290701)).
