### ISSUE TITLE
Age of MariaDB reported as 18 years old instead of 9 years

### ISSUE THREAD

**Issue by jhngrant** [cncf/landscape#573]
The Cloud Native Interactive Landscape website reports MariaDB as being 18 years old:

https://landscape.cncf.io/grouping=no&license=open-source&sort=first-commit

I guess this has been obtained from GitHub stats that indicates the first commit was Jul 30, 2000:

https://github.com/MariaDB/server/graphs/contributors

Other sources contradict this date. The MariaDB website states it was created in 2009:

https://mariadb.com/about-us

The initial release date on Wikipedia is 22 January 2009:

https://en.wikipedia.org/wiki/MariaDB

So, this means MariaDB is 9 years rather than 18 years old.

**Comment by dankohn** [comment]
MariaDB is a fork of MySQL, meaning that it includes all MySQL contributions up to the point of the fork. We calculate the date by looking at actual commits in the repo, and in fact link to the first one, which really was in 2000: https://github.com/MariaDB/server/commit/7eec25e393727b16bb916b50d82b0aa3084e065c

Thanks for the comment, though.
