### ISSUE TITLE
SVG of FoundationDB

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#576]
Please create an SVG of https://raw.githubusercontent.com/apple/foundationdb/master/documentation/FDB_logo.png

You can just zip and attach here.

**Comment by alexkontsevoy** [comment]
@dankohn attaching here:
[foundationdb.svg.zip](https://github.com/cncf/landscape/files/1932802/foundationdb.svg.zip)

**Comment by dankohn** [comment]
Closed with https://github.com/cncf/landscape/commit/cbc165d9594c2b2a0c1082537186b02debb8c6e4
