### ISSUE TITLE
Add StorageOS to Cloud Native Storage

### ISSUE THREAD

**Issue by croomes** [cncf/landscape#58]
Please add StorageOS to the "Cloud Native Storage" section.  StorageOS is a software-defined storage solution that provides persistent storage for containerized applications, on-premises or in the cloud.  [Logo here](http://storageos.com/wp-content/uploads/2016/06/storage-os-logo.png)

**Comment by croomes** [comment]
Adding SVG
[storageos.svg.zip](https://github.com/cncf/landscape/files/685462/storageos.svg.zip)

**Comment by lennypruss** [comment]
Added StorageOS to v0.9.3
