### ISSUE TITLE
Convert Logo to SVG

### ISSUE THREAD

**Issue by taylorwaggoner** [cncf/landscape#582]
Hi @alexkontsevoy - Please convert the attached logo to SVG.  Can you also please attach the zipped SVG to this issue when you're done?  Thank you!
[AgileStacks Logo Text 3.psd.zip](https://github.com/cncf/landscape/files/1932824/AgileStacks.Logo.Text.3.psd.zip)

**Comment by alexkontsevoy** [comment]
@taylorwaggoner attaching vector version (AI and SVG):

[agile stacks.zip](https://github.com/cncf/landscape/files/1933048/agile.stacks.zip)

**Comment by dankohn** [comment]
Looks great, thank you.
