### ISSUE TITLE
Match best practices on different url

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#591]
https://landscape.cncf.io/selected=git-lab

GitLab has a best practices badge but it's not showing because the badge is registered under a non-GitHub repo:
https://gitlab.com/gitlab-org/gitlab-ce
https://bestpractices.coreinfrastructure.org/en/projects/42

Please add support for a new key called `url_for_bestpractices` and if it exists, try it instead of `repo_url` to match against the best practices JSON.

**Comment by ZeusTheTrueGod** [comment]
Ok, I'll add this to the allowed keys
