### ISSUE TITLE
Habitat should cover multiple categories 

### ISSUE THREAD

**Issue by mfdii** [cncf/landscape#6]
Thank you for including Habitat (https://github.com/habitat-sh/habitat) in the landscape. Application Definition is probably the right area for Habitat's packaging technology. However, Habitat's supervisor capabilities used to run Habitat packages/containers also place it in the Service Management and Service Discovery.

Is it possible to have Habitat in these 3 categories:
- Application Definition
- Service Management
- Service Discovery

**Comment by dankohn** [comment]
I'm not arguing with what you're saying, but we've made the decision to put each project in only one box, even though that is inherently limiting for many projects.

Please let us know if you think it fits better in Platform, which is somewhat more of a catch all, or somewhere else.

Closing for now.
