### ISSUE TITLE
Add Spinnaker under CI/CD

### ISSUE THREAD

**Issue by skim1420** [cncf/landscape#61]
We are at spinnaker.io, and we are a continuous delivery platform developed in the open (github.com/spinnaker) through a partnership between Netflix, Google, Microsoft, Cloud Foundry, Veritas, Target, and many other contributors.

**Comment by skim1420** [comment]
![spinnaker-vert-lg](https://cloud.githubusercontent.com/assets/942631/21862646/1e074b1c-d808-11e6-9530-86e107f0ede7.png)

**Comment by lennypruss** [comment]
Added Spinnaker to v0.9.3.
