### ISSUE TITLE
Require unique names

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#618]
In the past, builds failed if the `name` wasn't unique. Please add an explicit check to have a fatal error if there are any duplicate `name`'s.

**Comment by ZeusTheTrueGod** [comment]
At this moment we allow same names if they are in different categories or subcategories.
Let me check if there are still any duplicates, and if there are no duplicates at this moment, lets prevent us from this issue in the future

**Comment by ZeusTheTrueGod** [comment]
I've just checked, there are no entries, so should we replace the check that name + subcategory is unique to just checking that name is unique, @dankohn ?

**Comment by dankohn** [comment]
Exactly.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by ZeusTheTrueGod** [comment]
Ok, if that decision is forever, we could stop using a special id instead of just a name

**Comment by dankohn** [comment]
I don't feel strongly either way.
