### ISSUE TITLE
Add fatal error for Twitter

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#626]
Please add a fatal error if the Twitter value includes a `?`. Lots of people include Twitter values like `https://twitter.com/HuaweiCloudCore?lang=en`. It should be `https://twitter.com/HuaweiCloudCore`.

**Comment by ZeusTheTrueGod** [comment]
Please check, values are equal.

**Comment by ZeusTheTrueGod** [comment]
Or point me what is the difference, it looks like what you want and what you see is same

**Comment by dankohn** [comment]
Fixed, sorry.

**Comment by dankohn** [comment]
Fixed for real, now.

**Comment by ZeusTheTrueGod** [comment]
I remember I know just drop that `?lang=en` part when I fetch it via twitter api. Should we close this ?

**Comment by dankohn** [comment]
No, I'd like to have a fatal error if you include a `?` in the Twitter value in landscape.yml. We display the Twitter handle and it looks broken when it shows as `@dankohn1?lang-en`.
