### ISSUE TITLE
Improve display in short embeds

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#636]
At the botton of https://www.cncf.io/certification/training/ the modal doesn't display clearly.

Please either make the modal scroll when the window is short or increase the minimum height of an embedded window.

**Comment by ZeusTheTrueGod** [comment]
The frame itself changes its width and height based on a browser width or height. I'll try to adapt the modal to the changing sizes

**Comment by dankohn** [comment]
The frame just needs a minimum height.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com
