### ISSUE TITLE
Add Rancher Cattle to Scheduling & Orchestration

### ISSUE THREAD

**Issue by ecliptik** [cncf/landscape#64]
Rancher has it's own default Scheduling and Orchestration framework called Cattle that is similar to Docker Compose, but is it's own entity.

https://github.com/rancher/cattle

**Comment by scottraney** [comment]
Thanks for the feedback and you comment is spot on.  We are dealing with limited real estate in this format so bucketed based on primary emphasis today.  In v1.0 (coming soon!) we will have a better way of capturing all the different frameworks/projects that come from a single companies.  Stay tuned.

**Comment by shawnpreissner** [comment]
+1 @scottraney, we'll keep Rancher in Platforms, closing request for the time being.
