### ISSUE TITLE
Add new category for Cloud Native OS

### ISSUE THREAD

**Issue by remonlam** [cncf/landscape#65]
Maybe we need to add a separate category for Cloud Native OS like CoreOS and Red Hat Atomic...

**Comment by rothgar** [comment]
I had asked about this at CloundNativeCon 2016. At the time they said they didn't want to prescribe something that low in the stack. They also didn't want to prescribe hardware or a cloud vendor to run on.

IMO that is the right decision, but I have no say in the matter.

**Comment by shawnpreissner** [comment]
Hi @remonlam this OS category has been added with 0.9.4 and more recent https://github.com/cncf/landscape/blob/master/landscape/CloudNativeLandscape_v0.9.5_cncf.jpg
