### ISSUE TITLE
CockroachDB

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#66]
@lennypruss 

Please replace the Cockroach Labs logo with this one for CockroachDB: https://raw.githubusercontent.com/cockroachdb/cockroach/master/docs/media/cockroach_db.png

**Comment by shawnpreissner** [comment]
Hi @dankohn, this is slated to be updated in the next release. Thanks.

**Comment by shawnpreissner** [comment]
Thanks @dankohn, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
