### ISSUE TITLE
Sort by latest tweet is failing

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#669]
https://landscape.cncf.io/grouping=no&sort=latest-tweet

Screen doesn't render, presumably because some expected value is null/.

**Comment by dankohn** [comment]
Can no longer recreate.

**Comment by ZeusTheTrueGod** [comment]
Not an issue anymore, I think. We fixed our way to fetch twitter. And we forbid an empty twitter field(i.e. null)
