### ISSUE TITLE
Graylog

### ISSUE THREAD

**Issue by zorel** [cncf/landscape#67]
Suggestion to add graylog in Logging
https://www.graylog.org/

**Comment by shawnpreissner** [comment]
Hi @zorel this is slated to be added in the next release. Thanks.

**Comment by raghu999** [comment]
+1 Hopefully Graylog is added

**Comment by shawnpreissner** [comment]
Thanks @zorel, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version

**Comment by raghu999** [comment]
@shawnpreissner why is graylog in logging greyed out its an opensource tool.
