### ISSUE TITLE
Submitted URL not selected as canonical

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#677]
Google is seeing 74 of our pages as "Submitted URL not selected as canonical" and not indexing them.

Figure out why and resolve.

https://search.google.com/search-console/index/drilldown?resource_id=https%3A%2F%2Flandscape.cncf.io%2F&item_key=CAESJWh0dHBzOi8vbGFuZHNjYXBlLmNuY2YuaW8vc2l0ZW1hcC54bWwYGSAC
https://webmasters.stackexchange.com/questions/112547/what-is-the-solution-for-submitted-url-not-selected-as-canonical-in-google-sea

<img width="948" alt="screen shot 2018-06-08 at 1 49 11 pm" src="https://user-images.githubusercontent.com/3083270/41172734-c5f4663a-6b22-11e8-814b-5b9e0089b91b.png">

**Comment by dankohn** [comment]
You determined via Fetch With Googlebot that the popup modal is not showing.

One short-term workaround would be to change the canonical URL for each card to include the organization and category. That way, it should be the only card showing, and should look different from every other entry. For example:

https://landscape.cncf.io/landscape=application-definition-image-build&organization=microsoft&selected=draft

**Comment by ZeusTheTrueGod** [comment]
So according to this, https://support.google.com/webmasters/answer/1061943?hl=en, we can detect googlebot via agent, and then provide a mobile view, which returns the proper result.
