### ISSUE TITLE
Recreate Netdata icon

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#679]
@alexcontini Could you please recreate a version of https://static.distribooted.com/logos/netdata.png. It is based on https://www.iconsdb.com/soylent-red-icons/seo-performance-icon.html (which unfortunately doesn't seem to have high-res versions) and the name added.

Cc https://github.com/firehol/netdata/issues/3801#issuecomment-396004881

**Comment by ktsaou** [comment]
Thank you!

**Comment by dankohn** [comment]
Done, thanks.
