### ISSUE TITLE
Remove mantl

### ISSUE THREAD

**Issue by zorel** [cncf/landscape#68]
Suggestion to remove Mantl, project is abandoned by Cisco, no community behind to take over.

**Comment by rothgar** [comment]
Is there official news of it being abandoned? I hadn't heard about them no longer maintaining the project.

**Comment by zorel** [comment]
Indeed, no official answer from Cisco, but https://github.com/mantl/mantl/issues/1842 
4 months old "answer in 2 weeks".

**Comment by dankohn** [comment]
OK to remove for now. We can add back if and when the project revives.

**Comment by thomasvincent** [comment]
The project is back.

**Comment by dankohn** [comment]
Thanks, we'll remove it for 0.95.

**Comment by thomasvincent** [comment]
Sorry if it was misunderstood. The project is active and building community again at https://www.github.com/mantl/

We are currently drawing the pull request queue and categorizing the issues. Ansible 2.x in the next week along with weave and HA.

**Comment by dankohn** [comment]
That's great to hear. Then, we'll add it back.

**Comment by shawnpreissner** [comment]
Thanks @thomasvincent, Mantl will be resurrected in the next version

**Comment by shawnpreissner** [comment]
Alive and well @thomasvincent, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
