### ISSUE TITLE
Check SVG cropping

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#686]
This SVG doesn't seem to have been cropped. Can you please check.

https://landscape.cncf.io/grouping=landscape&landscape=framework&selected=deep-framework

**Comment by ZeusTheTrueGod** [comment]
It goes bad because of 
![image](https://user-images.githubusercontent.com/230982/42128113-cfe65072-7cac-11e8-9602-790d65bcad16.png)
Both black and white background is used, thus an autocrop is confused.

**Comment by dankohn** [comment]
Sounds like the algorithm is fine. Can you please manually fix the SVG so that auto crop will work. 

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation  https://www.cncf.io
+1-415-233-1000  https://www.dankohn.com

**Comment by ZeusTheTrueGod** [comment]
Manual fix here does not look great to me, I think this is the best:
![image](https://user-images.githubusercontent.com/230982/42128594-c28eb5ee-7cb7-11e8-98d8-4936b962620f.png)
The picture is used only to detect the borders, nothing more

**Comment by dankohn** [comment]
Ok. 

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation  https://www.cncf.io
+1-415-233-1000  https://www.dankohn.com
