### ISSUE TITLE
Pure SVG On-Prem logo

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#698]
Cc @aw

You submitted a logo https://github.com/cncf/landscape/pull/631/files that is a PNG inside of an SVG. We require pure SVGs. Could you please attach a pure SVG or the AI file it's based on. You need to ZIP the file to upload it to this issue.

Thanks.

**Comment by aw** [comment]
OK I'm looking into it. Thanks for the heads-up.

**Comment by aw** [comment]
@dankohn I've attached a _pure_ SVG as requested, please let me know if it's correct. Thanks.
[on-prem.svg.zip](https://github.com/cncf/landscape/files/2110741/on-prem.svg.zip)

**Comment by dankohn** [comment]
You're set. Thank you!

https://landscape.cncf.io/selected=on-prem
