### ISSUE TITLE
Offer of assistance

### ISSUE THREAD

**Issue by LawrenceHecht** [cncf/landscape#7]
Hey, I don't want to quibble with how you chose what to include in the landscape. That said, please let me know if you want help vetting additions. I have a large data file of projects and companies that I am using to update my own directory.

In the meantime, I liked this criteria that the Linux Foundation included in its recent _Guide to the Open Cloud_:

Projects were selected for the list by The Linux Foundation’s cloud experts based on their
relevance, their relative maturity, and their relative visibility. More specifically, benchmarks for
consideration included:
• the project’s origins
• age of the project
• number of contributors
• number and frequency of commits
• diversity of contributions
• exposure
• demonstrated enterprise use
• expert opinions from IT practitioners

**Comment by dankohn** [comment]
Thanks, that's a good list. I'd be happy to get your suggestions.
