### ISSUE TITLE
Serverless

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#70]
I'd like to create a new box between Languages & Frameworks and Databases called Serverless that would include:

AWS Lambda: No good logo. Need to combine AWS and Lambda logos
Serverless: https://serverless.com/_/src/assets/images/serverless_logo.be2d3b90c0910b8d46efd441c96130ed.png
OpenWhisk: http://openwhisk.org/images/apache-openwhisk.svg
Fission: https://github.com/fission/fission

**Comment by moderation** [comment]
Other serverless offerings (not a complete list):
- [Azure Functions](https://azure.microsoft.com/en-us/services/functions/)
- [Google Cloud Functions](https://cloud.google.com/functions/)
- [Iron.io IronFunctions](http://open.iron.io/)
- [Webtask](https://webtask.io/)

**Comment by lennypruss** [comment]
A more appropriate place might be in platforms as a separate bucket (because they cut across multiple layers and abstract away that complexity).

**Comment by scottraney** [comment]
I think it could go either way.  Lamba is clearly a platform, while others like fission will be built on top of Kubernetes and provide some abstractions.

**Comment by craigbox** [comment]
Duplicate of #33.

**Comment by arun-gupta** [comment]
Was just thinking about this and would be great to see this added. How can I help?

**Comment by shawnpreissner** [comment]
This was achieved in the last version with the Event-based Compute category. Thank you all for your input!
