### ISSUE TITLE
missing in monitoring section

### ISSUE THREAD

**Issue by psdeblois** [cncf/landscape#72]
Dynatrace was built for Cloud Native monitoring. You should include them! https://www.dynatrace.com/platform/offerings/ruxit/

**Comment by fraka79** [comment]
+1
Pls. find attached their current logo:
![dynatrace_logo_rgb_cph_2048x364px](https://cloud.githubusercontent.com/assets/26711197/24352796/3919164c-12eb-11e7-8eca-77d94fe205ca.png)

**Comment by metmajer** [comment]
@shawnpreissner: resolved by https://github.com/cncf/landscape/issues/34.

**Comment by shawnpreissner** [comment]
Thanks @metmajer, @psdeblois and @fraka79 has been added in 0.9.4 and more recent
