### ISSUE TITLE
Division between infrastructure automation and host management

### ISSUE THREAD

**Issue by rothgar** [cncf/landscape#73]
Looking at the landscape the traditional config management tools are in their own box which I usually agree with. However they also can provision infrastructure the exact same way as Terraform/CloundFormation.

Just for example SaltStack has [Salt Cloud](https://docs.saltstack.com/en/latest/topics/cloud/) and Ansible has [ec2 module](http://docs.ansible.com/ansible/ec2_module.html)

It might be more beneficial just to join the two boxes as "Infrastructure Automation"

**Comment by shawnpreissner** [comment]
Hi @rothgar thanks for the great input and we'll consider merging in the future.

**Comment by shawnpreissner** [comment]
Thanks @rothgar, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
