### ISSUE TITLE
SVG version of ORY

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#735]
https://github.com/ory/oathkeeper/blob/master/docs/images/banner_oathkeeper.png

**Comment by alexkontsevoy** [comment]
@dankohn do we need the whole banner recreated, or just the Ory part? Can we use this:

![ory_07_-26-no-border](https://user-images.githubusercontent.com/4476098/43034258-1a290f54-8cfb-11e8-84ba-df33f486209a.png)

**Comment by dankohn** [comment]
Thanks, we went forward with: https://landscape.cncf.io/selected=ory-hydra
