### ISSUE TITLE
Provisioning section missing OS provisioning tools

### ISSUE THREAD

**Issue by rothgar** [cncf/landscape#74]
All of the tools describe in the provisioning section assume you already have an OS installed or available. None of them actually "provision" an operating system.

Tools such as

* [Foreman](https://www.theforeman.org/)
* [Collins](https://github.com/tumblr/collins)
* [Razor](https://docs.puppet.com/pe/latest/razor_intro.html)
* [MaaS](https://maas.io/)

Should probably be included in this section

**Comment by shawnpreissner** [comment]
Hi @rothgar, great suggestions...we're creating a Bare Metal section under Provisioning, which will include Foreman, MaaS, and a couple others! As you know, Razor is from Puppet -- which we've included right next-door, under Host Management / Tooling.

**Comment by shawnpreissner** [comment]
Thanks @rothgar, closing as this update was also included in the most recent version https://github.com/cncf/landscape#current-version
