### ISSUE TITLE
Outdated Google Cloud Platform logo (again!)

### ISSUE THREAD

**Issue by craigbox** [cncf/landscape#75]
This was fixed in #1 but has reverted.

Could you please fix this again? High-resolution asset [here](https://cloud.githubusercontent.com/assets/132510/20099933/dbfcd502-a5b2-11e6-990c-98f851af9868.png). Thank you!

**Comment by shawnpreissner** [comment]
Hi @craigbox please find in 0.9.4 under Infrastructure https://github.com/cncf/landscape/blob/master/landscape/CloudNativeLandscape_v0.9.4.jpg
