### ISSUE TITLE
Add Stackpoint.io to Platforms

### ISSUE THREAD

**Issue by arieljatib** [cncf/landscape#76]
We'd like to have [Stackpoint.io](https://stackpoint.io/#/) added to the infographic. 

Stackpoint.io is a web-based application for quickly deploying and managing Kubernetes clusters at all the leading cloud infrastructure providers - AWS, Azure, GKE, GCE, DigitalOcean. Additionally, users can choose to deploy a variety of applications, including cloud-native options like Prometheus and Linkerd. 

The company logo is attached. Let me know if there are any specific requirements around size or format. 

![spc-cncf-silver](https://cloud.githubusercontent.com/assets/1958997/22702849/13940656-ed30-11e6-8905-649374f75305.png)

![spc-cncf-silver 2x](https://cloud.githubusercontent.com/assets/1958997/22702848/139368b8-ed30-11e6-89a6-ee8555a365d8.png)

**Comment by dankohn** [comment]
Planning to add to platforms.

**Comment by baldwinSPC** [comment]
@dankohn ping

**Comment by dankohn** [comment]
Apologies, I thought we'd gotten you. 0.95 is coming very soon!

**Comment by shawnpreissner** [comment]
Thanks @baldwinSPC and @arieljatib, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
