### ISSUE TITLE
Prometheus is now a Graduated CNCF project

### ISSUE THREAD

**Issue by idvoretskyi** [cncf/landscape#770]
Since 2018-08-09, Prometheus is the Graduated CNCF project [1].

The Cloud Native Trail map and the static version of the Cloud Native landscape have to be updated respectfully.

1. https://www.cncf.io/announcement/2018/08/09/prometheus-graduates/
2. https://github.com/cncf/landscape/blob/master/README.md#trail-map
3. https://github.com/cncf/landscape#current-version

cc @dankohn @alexcontini

**Comment by dankohn** [comment]
It's already fixed in the interactive landscape and will be in the others when they're updated next.
