### ISSUE TITLE
Add Deveo to source code management

### ISSUE THREAD

**Issue by kontulai** [cncf/landscape#78]
[Deveo](https://deveo.com/) is a code hosting and collaboration platform. It differentiates from Github, Bitbucket and Gitlab by offering support also for Subversion (SVN) and Mercurial (HG) repositories. It acts from "all private" standpoint to be a solution for security considerate corporations who still wish to host code in the cloud.

Logo attached.

![deveo-logo-320x320](https://cloud.githubusercontent.com/assets/995598/22738381/ebddb5a4-ee0f-11e6-8bd7-b6c3953c4db7.png)

Would be nice to include it in the "Source code management" section, as it differentiates from the already existing tools.

**Comment by shawnpreissner** [comment]
Hi @kontulai thanks for the request. Unfortunately, at this time we are dealing with limited real estate and cannot fulfill this request for the Cloud Native landscape. Thanks again.

**Comment by kontulai** [comment]
Hi,

@shawnpreissner are you sure about the reasoning? In SCM column I see 3 icons and next to it there is registry services that has 5 icons.

**Comment by shawnpreissner** [comment]
@kontulai I was referring to macro real estate, there'll be some shifting where category frame sizes will be changing to help keep the entire landscape as readable as possible. Keep up the good work at Deveo and we'd be happy to re-evaluate in the future. Thanks.

**Comment by kontulai** [comment]
Thank you for your answer and good luck with the project!
