### ISSUE TITLE
Fetch default branch when grabbing repo info

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#786]
When a repo doesn't use master as it's default branch, we're having to manually specify the branch. However, we should instead fetch this info from the API. For example, https://api.github.com/repos/scality/metalk8s shows:
```json
"default_branch": "development/1.1",
```
Please automatically fetch the branch specified there. Also, please remove the branch info from all entries where it then wouldn't change the result.

**Comment by ZeusTheTrueGod** [comment]
The main reason for a branch was to handle those repos where `master` is not a default branch.
Now, with a github api, we can properly fetch a default branch, also this branch is used to count amount of contributors and first and last commits. I can guess that a repo may choose a default branch 'v1.0', then make main development in a master branch, without making any merges back into v1.0 or whatever, and this way we will accidentally think that there is no development at all

**Comment by dankohn** [comment]
It will be a shame to remove your clever binary search for first commit logic. 

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation  https://www.cncf.io
+1-415-233-1000  https://www.dankohn.com

**Comment by ZeusTheTrueGod** [comment]
First commit is not a problem, whatever branch you choose, it will be based on the original master in almost all the cases. Last commit may had a problem all that time: we look for the latest commit in a given branch, should not we look for the latest commit of a whole repo ?

**Comment by dankohn** [comment]
Some repos have hundreds of branches. But feel free to implement if you want. 

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation  https://www.cncf.io
+1-415-233-1000  https://www.dankohn.com
