### ISSUE TITLE
Formatting issues with landscape and filtering

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#794]
Formatting is broken when we filter items:
https://514-big-picture--landscape.netlify.com/cncf=hosted,graduated,incubating,sandbox&format=landscape

<img width="745" alt="screen shot 2018-09-07 at 3 42 21 pm" src="https://user-images.githubusercontent.com/3083270/45239898-e293e200-b2b4-11e8-96e0-78340db76f21.png">

**Comment by ZeusTheTrueGod** [comment]
@dankohn , done, please close if you can not reproduce it
