### ISSUE TITLE
Text below title

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#795]
Please change it to:

CNCF's Cloud Native Trail Map (png, pdf) provides a good introduction. The cloud native landscape (png, pdf) and serverless landscape (png, pdf) are dynamically generated below.

Except, if on mobile, change "below" to "when viewed from a larger device".

**Comment by dankohn** [comment]
Only "png" and "pdf" should be links.

**Comment by ZeusTheTrueGod** [comment]
@dankohn please check if it works properly.

**Comment by dankohn** [comment]
Fixed.
