### ISSUE TITLE
Convert fonts to outlines

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#797]
All of these SVGs have embedded fonts in them that cause them to display improperly if the fonts are not installed. Please re-export choosing "convert text to shapes" and ensure that the result looks the same but no longer contains font names when you open it as a text file. Note this decimal places issue: https://graphicdesign.stackexchange.com/a/91169

Please also writeup the exact steps here. The SVGs that need fixes are:

apache-openwhisk.svg
azurefunctions.svg
azureregistry.svg
codefresh-registry.svg
gardener.svg
google-cloudbuild.svg
jenkins.svg
kubicorn.svg
rexray.svg

**Comment by alexcontini** [comment]
@dankohn steps are:

1. Open file in Illustrator
2. Select all text
3. With text selected, go to Object > Expand in the top menu
4. Export file by going to File > Export > Export As in top menu
5. Select SVG from the format drop down and make sure that "Use Artboards" is checked
6. This will open a SVG options box, make sure to set Decimal to 5 (that is the highest possible) 7. Click Okay to export
