### ISSUE TITLE
Please add Nirmata

### ISSUE THREAD

**Issue by patelrit** [cncf/landscape#80]
About Nirmata:
Nirmata is a cloud based container and microservices management platform. Nirmata fully automates application management on any public or private cloud. Nirmata provides comprehensive policy-based automation for deploying, operating, and optimizing containerized applications across clouds, via easy-to-use, intuitive interfaces. Nirmata provides integrated tools for microservices, continuously monitors the application and infrastructure for changes, and auto-tunes the application based on defined policies.

Please add us to the 'Platform' sections.

**Website:** www.nirmata.com

Please let me know if you have specific size/resolution requirements for the logo (attached)

![nirmata-logo](https://cloud.githubusercontent.com/assets/3522560/22844464/4677a900-ef93-11e6-84ba-4f6537d3ff63.jpg)

**Comment by dankohn** [comment]
Adding to 1.0.

**Comment by shawnpreissner** [comment]
Hi @patelrit, included in 0.9.4 and more recent https://github.com/cncf/landscape/blob/master/landscape/CloudNativeLandscape_v0.9.5_cncf.jpg
