### ISSUE TITLE
Full screen mode

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#801]
Please add a full-screen icon just to the right of serverless. Clicking it should hide the title bar and nav bar. Here's the kind of icon to use: https://www.google.com/search?q=full+screen+icon&tbm=isch

You then need to add the inverse to restore.

**Comment by ZeusTheTrueGod** [comment]
we already have a `/serverless` and a `/landscape` urls used for rendering the png or pdf. Should we try to reuse it? Can you specify what exactly should be left in a fullscreen mode? Should we attempt to use a fullscreen mode from a browser?

**Comment by dankohn** [comment]
Just add a `mode=fullscreen` and don't render the navbar or header, similar to what you do with `embedded=yes`.
