### ISSUE TITLE
Please add Hyper.sh as a platform on the diagram

### ISSUE THREAD

**Issue by mrmrcoleman** [cncf/landscape#81]
Hyper.sh is a Docker hosting platform who are seeing huge growth: http://hyper.sh/

People have said very nice things about them in public places: http://thenewstack.io/hyper-docker-done-right-way/

Logo is here: https://www.hyper.sh/logo/logo_dark.svg

**Comment by caniszczyk** [comment]
@mrmrcoleman do you envision in this in the infrastructure or platform section?

**Comment by mrmrcoleman** [comment]
@caniszczyk This should be under platform please.

**Comment by caniszczyk** [comment]
+1 then

**Comment by mrmrcoleman** [comment]
@dankohn I disagree. Hyper.sh is a container platform. I'd be more than happy to create a separate PR for HyperContainer, the open-source container runtime that Hyper.sh uses?

**Comment by shawnpreissner** [comment]
@mrmrcoleman we discussed and will be adding Hyper to Platforms PaaS / Container Service in the upcoming release. Thanks

**Comment by shawnpreissner** [comment]
Thanks @mrmrcoleman, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
