### ISSUE TITLE
Add NETSIL to the Observability and Analytics section

### ISSUE THREAD

**Issue by smb06** [cncf/landscape#82]
NETSIL is the observability and analytics company for modern cloud applications. NETSIL’s Application Operations Center (AOC) helps SREs and DevOps improve the reliability and performance of API and microservices driven production applications. 

At the heart of the AOC is an auto-discovered service topology, which is rendered from live service interaction analysis. It allows practitioners to visualize their service dependencies and operational metrics and work collaboratively across teams. This enables effective application monitoring, incident response, capacity planning, and deploy management. 

To learn more about Netsil visit www.netsil.com. 

You may use the following logo for NETSIL: https://s3.amazonaws.com/docs.netsil.com/logos/Netsil_640x640-blue.jpg

**Comment by shawnpreissner** [comment]
Hi @smb06 NETSIL was added to Monitoring in the last release. Thanks.  https://github.com/cncf/landscape/blob/master/landscape/CloudNativeLandscape_v0.9.5_cncf.jpg
