### ISSUE TITLE
Aim to shorten build times on Netlify

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#825]
We're up from 2 minutes to 11 minutes. Also, please try to reduce duplicative log messages.

**Comment by dankohn** [comment]
It looks like you're running and tearing down the web server 4 times, one for each test. Can we keep it running between tests?

**Comment by ZeusTheTrueGod** [comment]
Yes, it is mostly related to rendering png/pdf images.

**Comment by dankohn** [comment]
Also, the final step of copying the repo seems to take a long time. You might look at whether #873 would help.

**Comment by ZeusTheTrueGod** [comment]
The real problem is that I keep the web server open for about 6 or 10 minutes, in order to run all the tests and generate the landscape images

**Comment by ZeusTheTrueGod** [comment]
I think that was done. I've checked, there is nothing that blocks us at this moment.
