### ISSUE TITLE
white line in CNCF projects at some zooms

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#832]
https://landscape.cncf.io/format=landscape&zoom=120

<img width="309" alt="screen shot 2018-09-14 at 9 54 55 pm" src="https://user-images.githubusercontent.com/3083270/45581283-092fbb00-b869-11e8-903c-9fe8d176a979.png">

**Comment by ZeusTheTrueGod** [comment]
That was fixed in other pull request
