### ISSUE TITLE
Enable landscape mode on mobile

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#834]
Please add back the card/landscape/serverless switcher to appear on mobile.

**Comment by ZeusTheTrueGod** [comment]
I plan to handle that issue, 
![image](https://user-images.githubusercontent.com/230982/45870252-21389a80-bd93-11e8-84ef-efc6d80b0598.png)
with reducing the font size a bit and displaying only '+' and '-' buttons afther the serverless

I'm trying to minimize the empty space at the top here, 
![image](https://user-images.githubusercontent.com/230982/45870414-812f4100-bd93-11e8-9345-9c228b6678c8.png)

May be we should put the switcher between 'Cloud native landscape' and 'Cloud native computing foundation'

**Comment by dankohn** [comment]
Sounds good, but it should work differently in portrait mode.
--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by ZeusTheTrueGod** [comment]
![image](https://user-images.githubusercontent.com/230982/45878614-69af8280-bdaa-11e8-97ee-ec30cdf643f9.png)
We can have "card", "landscape", "serverless", "-", "+" in one line for a portrait mode.

**Comment by dankohn** [comment]
Sounds good, thanks. 

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation  https://www.cncf.io
+1-415-233-1000  https://www.dankohn.com

**Comment by dankohn** [comment]
Making good headway. On portrait:

![img_1078](https://user-images.githubusercontent.com/3083270/45914257-50d9b800-be10-11e8-8f1f-2da70bdd8a8d.png)

Please remove some of the whitespace from the header and make the 100% the same font and size and in line with Serverless.

![img_1077](https://user-images.githubusercontent.com/3083270/45914262-5931f300-be10-11e8-86f8-0d986781095e.png)

In landscape perspective, could you please try killing the CNCF logo and moving the mode switch and the 100% to the top middle and top right so that much more space is available to see the landscape.

**Comment by ZeusTheTrueGod** [comment]
@dankohn , that was done. What do you think about sticking the Card Mode / Landscape / Serverless switch position? Right now it jumps when you go to the card mode or landscape/serverless mode. We could fix its position for a portrait mode, so first we have a row with logos, then a switch, and then everything else: a summary and a card mode content.

**Comment by ZeusTheTrueGod** [comment]
Actually, I updated the layout so the switcher does not change its position

**Comment by dankohn** [comment]
Almost done. Last issue is stickiness of subheaders when you scroll up and down. I could merge like this and you can fix later, if you prefer. 

![d68a8e0f-386a-41f9-b32d-f81698ab3327](https://user-images.githubusercontent.com/3083270/45929246-cfbc1700-bf1c-11e8-94ba-431b2ce30bfc.png)

**Comment by ZeusTheTrueGod** [comment]
Popup window was not working on simulator, thus please do not merge yet.
And could you clarify, is the problem with the offset or you want to keep certain elements during the scroll ?

**Comment by dankohn** [comment]
The latter. 

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation  https://www.cncf.io
+1-415-233-1000  https://www.dankohn.com

**Comment by ZeusTheTrueGod** [comment]
That was done,

![image](https://user-images.githubusercontent.com/230982/45930633-657e9300-bf6b-11e8-8802-4b4cc97be3d9.png)

**Comment by dankohn** [comment]
Scrolling now seems good. The last issue is that the modal is not displaying correctly in landscape orientation. It looks good in portrait.

![img_0020](https://user-images.githubusercontent.com/3083270/45932387-54248f00-bf49-11e8-9cbe-a4b9da0a68b4.png)
