### ISSUE TITLE
Add Quobyte to storage

### ISSUE THREAD

**Issue by sbuenker** [cncf/landscape#85]
Please add Quobyte to the storage section.

**Website**: [https://www.quobyte.com](https://www.quobyte.com)

Quobyte is a versatile software-defined storage system which runs all kinds of storage workloads and on most any mix of hardware (ranging from all-flash to archival disks). At base, it’s a parallel POSIX file system which also handles block and object storage.

It’s neatly integrated with all the infrastructure tech out there: there’s a Kubernetes [volume plugin](https://github.com/kubernetes/kubernetes/tree/master/examples/volumes/quobyte), OpenStack [storage drivers](https://wiki.openstack.org/wiki/Quobyte), a Mesosphere’s DC/OS [integration](https://github.com/quobyte/dcos-quobyte), and more. Monitoring and analytics are built in and can be accessed either via Quobyte’s webconsole or it can easiy be hooked up to [Prometheus](https://prometheus.io/). Oh, and there’s of course an API at the ready.

The company logo is attached. Please let me know if there are specific requirements in terms of size or format.

![quobyte_stacked_blue](https://cloud.githubusercontent.com/assets/3036965/23132067/ab7c04a8-f78c-11e6-8e2f-77b96b78a7c4.png)

**Comment by shawnpreissner** [comment]
Thanks and closing since Quobyte was included in the last release https://github.com/cncf/landscape/blob/master/landscape/CloudNativeLandscape_v0.9.5_cncf.jpg
