### ISSUE TITLE
Noassertion license is a bug

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#855]
This just got added: https://landscape.cncf.io/license=noassertion

https://github.com/cncf/landscape/commit/7bbc837a2fd3d315bbe7bd1d8ffbcc05b147429d

**Comment by ZeusTheTrueGod** [comment]
The problem is that github can not detect the license.
As far as I see from the repo, it has both Apache and MIT license in the root.
What should we do? Treat this as 'unknown' ?

**Comment by dankohn** [comment]
Unknown, which is what we've done in the past.
--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by ZeusTheTrueGod** [comment]
Just for your information, there are 30 elements without a known license, so the github gave them noassertion.

**Comment by dankohn** [comment]
But why are some unknown and some noassertion?
--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by ZeusTheTrueGod** [comment]
I think unknown could happen if there is no license file at all. noassertion was a case when github could not recognise the license from the content. Just a guess though
