### ISSUE TITLE
ContainerOps

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#86]
Huawei has a new CI project called ContainerOps that we'd like to include.

https://github.com/Huawei/containerops

![containerops-logo-small](https://cloud.githubusercontent.com/assets/3083270/23136350/5786a94c-f76a-11e6-85f0-280a0a965c14.png)
![containerops-logo-large](https://cloud.githubusercontent.com/assets/3083270/23136354/58ec8586-f76a-11e6-8a77-efe5220f0d39.png)

**Comment by shawnpreissner** [comment]
Thanks and closing as ContainerOps was included in the last release https://github.com/cncf/landscape/blob/master/landscape/CloudNativeLandscape_v0.9.5_cncf.jpg
