### ISSUE TITLE
Flickering scroll bar

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#861]
There's a new issue where when you hover over a triangle on an item in the navigation column, the scroll bar for the navigation column flickers on and off.

With scrollbar:
<img width="222" alt="screen shot 2018-09-28 at 8 11 29 pm" src="https://user-images.githubusercontent.com/3083270/46238545-ec13e580-c35a-11e8-9e38-04222b26d337.png">

Without:
<img width="228" alt="screen shot 2018-09-28 at 8 11 39 pm" src="https://user-images.githubusercontent.com/3083270/46238552-f7ffa780-c35a-11e8-9fd8-c9c0143ecaf4.png">

This only happens when full screen on my MacBook.

**Comment by ZeusTheTrueGod** [comment]
I'm not sure if I can reproduce this at all

**Comment by dankohn** [comment]
It's happened very reliably in the last month when I full-screen Chrome on my Macbook. If you play with different widths for 5 minutes you should see it.
