### ISSUE TITLE
Branch functionality seems to be broken

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#871]
I want to set https://landscape.cncf.io/grouping=no&selected=azure-stack-acs-engine&sort=latest-commit to use branch `azsmaster` but the last commit isn't changing. Could you please confirm that we can still override branch.

https://github.com/cncf/landscape/compare/dan-branch

**Comment by ZeusTheTrueGod** [comment]
I certainly removed this feature. Let me return it back, so you can override the branch.
