### ISSUE TITLE
Reduce the size of the repo

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#873]
Copy the repo to an archive repo. In this repo, filter out all old versions the landscape and serverless landscape and the trail map.

Create a new repo just to hold the trail map.

https://itextpdf.com/blog/how-completely-remove-file-git-repository

On build, copy the latest version of the trail map to `/dist` so that we serve the trail map from this app rather than GitHub (and get credit for doing so in Google Analytics).

**Comment by ZeusTheTrueGod** [comment]
@dankohn , here is a list of required actions
- close all pull requests, clean all branch
- remove all obsolete local branches
- remove `landscape`, `serverless`, `trail_map` folder and commit
- run `bfg --delete-folders 'landscape'`, `bfg --delete-folders 'serverless'`, `bfg --delete-folders 'trail_map'`
this removes these files from the history, also they should not present in the latest commit
- run `git reflog expire --expire=now --all && git gc --prune=now --aggressive` to get rid of obsolete local files
- finish with `git push origin HEAD --force`
I expect that eventually github will cleanup old files and the repo will be back to 37mb

**Comment by ZeusTheTrueGod** [comment]
Just forgot to mention, after that I need to update the code, I have a question, can we reference the new `cncf/landscape-trailmap` repo from the readme to show a trail map ?

**Comment by ZeusTheTrueGod** [comment]
Or do you want me to copy data to the dist folder and then server those files from the landscape.cncf.io for the readme ?

**Comment by dankohn** [comment]
Implemented.

Also note this useful command:
```sh
git rev-list --objects --all \
| git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' \
| sed -n 's/^blob //p' \
| sort --numeric-sort --key=2 \
| gcut -c 1-12,41- \
| gnumfmt --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest
```

**Comment by dankohn** [comment]
Note that the original, unaltered repo is archived at: https://github.com/cncf/landscape-archive
