### ISSUE TITLE
Gigaspaces Cloudify

### ISSUE THREAD

**Issue by dfilppi** [cncf/landscape#88]
Gigaspaces Cloudify (http://getcloudify.org) is a leading product in the orchestration and cloud native orchestration space.  Would it be possible to add it to the "orchestration and management/scheduling and orchestration" and "provisioning/infrastructure management"?

**Comment by shawnpreissner** [comment]
Hi @dfilppi thanks for the request, due to real estate challenges, we're limiting to 1 space and will include Cloudify in Provisioning/Infrastructure Automation in the upcoming release!

**Comment by dfilppi** [comment]
Thanks!

**Comment by shawnpreissner** [comment]
Thanks @dfilppi, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
