### ISSUE TITLE
More KCSP space

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#886]
Please move the KCSP box to the left on the landscape so there's room for 2 more columns of KCSPs.

**Comment by ZeusTheTrueGod** [comment]
Why is that open?  @dankohn

**Comment by dankohn** [comment]
Because when there is only one commit in a PR, GitHub uses the commit message instead of the PR title, so it misses the `closes`.

Closed via 57c31f6df89a6c3ced3eeb2dbdfe274a835bb5ac
