### ISSUE TITLE
Why is "Cloud-Native Storage" a sub-category of "Runtime"

### ISSUE THREAD

**Issue by f1erro** [cncf/landscape#89]
Why was cloud storage singled out as one of the subcategories of "Runtime?"  That seems a little arbitrary to me (in fact, you could have many services from each of AWS, GCP and Azure service listed under Runtime)

I think you should remove Cloud-Native Storage as a category for runtime, and re-name Runtime to Container Runtime.  That way it's a more fully explored category due to the limitation in scope.

Runtime should instead be named something like "Application Services" to include many services like S3, GCS, SQS, RDS, Spanner, etc.

**Comment by dankohn** [comment]
We appreciate the suggestion but storage, network and container runtimes are 3 of the biggest areas for innovation in the runtime space. By contrast, we would put SQS at a higher layer under Streaming, and RDS and Spanner under databases.

No taxonomy is perfect, but it's not a coincidence that CNCF has working groups for both storage and networking:
https://github.com/cncf/wg-storage
https://github.com/cncf/wg-networking

Anyway, thanks for the suggestions.
