### ISSUE TITLE
Re-brand for REX-Ray and EMC {code} in Cloud-Native Storage

### ISSUE THREAD

**Issue by kacole2** [cncf/landscape#90]
First off @dankohn, thanks for putting this together.

Our team has gone through some rebranding efforts and just wanted to make sure this makes its way into 1.0

`EMC {code}` is now `{code} by Dell EMC`. Our new logo .png logo can be vertical or horizontal. Horizontal is preferred.

In addition, REX-Ray has been upgraded to a new color logo.

![rex-ray_color_title_light](https://cloud.githubusercontent.com/assets/4482386/23806150/94629588-058e-11e7-87a5-e8b8caba3a83.png)
![dell emc logo vertical_web_rgb](https://cloud.githubusercontent.com/assets/4482386/23806162/9cdc03e8-058e-11e7-8f00-fe16c63a3a6d.png)
![dell emc logo_horizontal_web_rgb](https://cloud.githubusercontent.com/assets/4482386/23806163/9cdcd408-058e-11e7-921a-037401cae115.png)

**Comment by shawnpreissner** [comment]
Hi @kacole2, love the new REX-Ray look, and we'll get both updated in our upcoming release.

**Comment by dankohn** [comment]
REX-Ray logo is probably my favorite of all ~500.

**Comment by kacole2** [comment]
@shawnpreissner @dankohn oddly enough, we're going through another logo change. Once I have the new files I'll update this issue. Thanks for understanding.

**Comment by dankohn** [comment]
😢

--
Dan Kohn <mailto:dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation <https://cncf.io/>
tel:+1-415-233-1000

**Comment by shawnpreissner** [comment]
say it ain't so, @kacole2

**Comment by kacole2** [comment]
@shawnpreissner @dankohn not to REX. he's good. :) We're dropping the "by Dell EMC" and will be "Dell Technologies" or "Dell Tech".

**Comment by shawnpreissner** [comment]
Ok @kacole2, hopefully the timing works out as we're going to be releasing a new version in the coming weeks. Please keep us posted.

**Comment by shawnpreissner** [comment]
@kacole2 do you have a new logo? Please reply with today if at all possible.

**Comment by kacole2** [comment]
@shawnpreissner it's on my hit list today.

**Comment by dankohn** [comment]
@kacole2 We are planning to include REX-Ray and libstorage in the next version of the landscape, but not Code by Dell EMC, since the latter is not a specific project. We will also be including https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Dell_EMC_logo.svg/1024px-Dell_EMC_logo.svg.png as a non-open-source storage offering.

**Comment by kacole2** [comment]
@dankohn @shawnpreissner sorry for not getting back at you earlier. Graphics, ya know. :) At least these suggestions don't make me feel as bad not having a graphic yet.

That's fine to remove the {code} by Dell EMC since it's not project specific. Please keep REX-Ray and libStorage in there. And yes, please include the Dell EMC logo as a non-open-source storage offering.

**Comment by shawnpreissner** [comment]
Thanks, @kacole2 stay tuned for a release soon!

**Comment by shawnpreissner** [comment]
Thanks @kacole2, closing as these updates were included in the most recent version https://github.com/cncf/landscape#current-version
