### ISSUE TITLE
Application Definition and Build category has few odd items

### ISSUE THREAD

**Issue by errordeveloper** [cncf/landscape#905]
<img width="1954" alt="screenshot 2018-10-15 17 16 31" src="https://user-images.githubusercontent.com/251467/46963648-1b865a00-d09e-11e8-80da-e92f1cd7c7ab.png">

I see that Telepresence and KubeVirt are here, and I don't really understand why. Also minikube is an odd fit, and I'm not sure which way OpenAPI fits in as such, also Packer is not very Kubernetes-native.

If all the tools included are genuinely meant to define this category, there too many things missing, e.g. any traditional build systems (make, maven, and any others). However, considering that this is category is for tools that are dedicated to containers and are Kubernetes-native, I think this category needs a lot of work.

cc @garethr for comment

**Comment by dankohn** [comment]
In general, I'm very happy to hear suggestions on how to clearly split up categories. Note that we recently split `service management` into `remote procedure call`, `service proxy, `api gateway`, and `service mesh`, which I think is dramatically clearer.

I definitely think we can avoid traditional build systems by saying that this is focused on cloud native build systems. So, I'm all ears if you'd like to propose a split into separate `application definition` and `image build` categories, or other categories.

**Comment by dankohn** [comment]
Closing for now, but please reopen if you have ideas on how to segment this category.
