### ISSUE TITLE
Update OpenStack Logo

### ISSUE THREAD

**Issue by resker** [cncf/landscape#92]
OpenStack has a new logo, please update - thanks!

![openstack_logo_vertical](https://cloud.githubusercontent.com/assets/1372565/23922393/2d715d9c-08d0-11e7-92fd-8e45167fc62f.png)

**Comment by shawnpreissner** [comment]
Thanks @resker will refresh in upcoming version

**Comment by shawnpreissner** [comment]
Thanks @resker, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
