### ISSUE TITLE
Consider adding CI/CD security section

### ISSUE THREAD

**Issue by Ulua** [cncf/landscape#93]
Replace secure images area with "CI/CD security", or something similar:
Aqua
Twistlock
Neuvector
Evident.io
Hashicorp Vault
Credstash
Confidant

**Comment by shawnpreissner** [comment]
Hi @Ulua thanks for the request. We appreciate the suggestion and are renaming Secure Images -> CI/CD Security and including: Aqua, Twistlock, Neuvector, and Hashicorp Vault in addition to the incumbents. New version coming soon!

**Comment by shawnpreissner** [comment]
Thanks @Ulua, closing as these updates were included in the most recent version https://github.com/cncf/landscape#current-version
