### ISSUE TITLE
Include the Ubuntu suite of tools that support CNCF ecosystem technologies

### ISSUE THREAD

**Issue by dustinkirkland** [cncf/landscape#94]
Over the last few years, we have extended support of each of the following open source projects to support Cloud Native ecosystem at several different levels.  We are delighted to share and extend this vibrant ecosystem.

Please add the following logos to the ecosystem map sections:

INFRASTRUCTURE
- MAAS: Metal as a Service.  MAAS is an open source project (AGPL) implemented in Python that automates bare metal provisioning of any Linux OS and WIndows, through a command line interface, a web interface, and an REST API.  Complex workloads like Kubernetes are easily deployed to bare metal machines with MAAS.
- See: http://maas.io/
- Logo: https://insights.ubuntu.com/wp-content/uploads/950d/maas-logo-text.png

PROVISIONING --> Infrastructure Automation
- Juju: Service modeling.  Juju is an open source project (AGPL) implemented in Golang that provides a graphical and command line interface for modeling complex software deployments.  Charms of Kubernetes are part of the upstream Kubernetes source tree that enables deploying (day 1) and operating (day 2 - infinity) Kubernetes in a high availability configuration across any public cloud, private cloud, and bare metal.
- See: https://jujucharms.com/
- Logo: http://design.ubuntu.com/wp-content/uploads/6b77/juju_black-orange_hex.png

PROVISIONING --> Secure Images
- Snap: Snap are a universal packaging format enabling delivery of applications and their dependencies across any Linux distribution.  The infrastructure behind Snaps is open source (GPLv3) code implemented in Golang.  As of Kubernetes 1.6, all parts of the Kubernetes infrastructure are available as highly portable Snap Packages.
- See: https://snapcraft.io/ 
- Logo: http://people.canonical.com/~kirkland/snap.png

RUNTIME --> Container Runtime
- LXD: LXD is a container runtime that runs general purpose operating system, able to boot dozens of Linux OSes, and provides an extremely efficient replacement for virtual machines for Linux-on-Linux systems.  LXD includes open source (GPLv2) code entirely upstream in the Linux kernel, as well as an open source (Apache) userspace daemon implemented in Golang.  High Availability Kubernetes deployed on Ubuntu uses LXD for clustering, efficiency, and snapshot/rollback upgrades.
- See: http://linuxcontainers.org/
- Logo: http://people.canonical.com/~kirkland/lxd.png

PLATFORMS
- Ubuntu: Ubuntu is one of the world's most widely deployed operating systems, freely available, and widely used as the basis OS for cloud and container workloads, from Kubernetes to Cloud Foundry to OpenStack.
- See: http://www.ubuntu.com/
- Logo: http://people.canonical.com/~kirkland/ubuntu.png

OBSERVABILITY AND ANALYSIS --> Monitoring
- Landscape: The Landscape client/agent is an open source (GPLv3) tool implemented in Python that provides deep OS and application monitoring and systems management at tremendous scale.  Landscape is intimately aware of containers and cloud native infrastructure and manages the security updates and compliance.
- See: http://landscape.canonical.com/
- Logo: http://people.canonical.com/~kirkland/landscape.png

If you need any of these logos rotated or in a different orientation (e.g. linear versus stacked), just ask.

Thanks,
Dustin

**Comment by dustinkirkland** [comment]
Bump?

**Comment by shawnpreissner** [comment]
Hi @dustinkirkland , we'll be including below in the upcoming release. Thanks.
MAAS: Bare Metal (new branch of Infrastructure)
Juju : PROVISIONING --> Infrastructure Automation
Snap - agreed to not include
LXD : RUNTIME --> Container Runtime : updating existing LXD logo
Ubuntu : PLATFORMS
Landscape - agreed to not include

**Comment by shawnpreissner** [comment]
Thanks @dustinkirkland, closing as these updates were included in the most recent version https://github.com/cncf/landscape#current-version
