### ISSUE TITLE
Bitnami missing from 0.9.4 and later versions

### ISSUE THREAD

**Issue by watchnerd** [cncf/landscape#95]
Bitnami was included in the Application Definition category in the 0.9.3 version, but was removed from later versions.

Please add Bitnami back to the Application Definition category.

**Comment by shawnpreissner** [comment]
You are correct @watchnerd, sorry that is strange, and we will have Bitnami in the Application Definition category in the upcoming release. Thanks

**Comment by shawnpreissner** [comment]
Thanks @watchnerd, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
