### ISSUE TITLE
Datadog logo not rendered correctly in 0.9.4

### ISSUE THREAD

**Issue by brian-brazil** [cncf/landscape#97]
In 0.9.4 the text of the Datadog logo (in the top right, below Cloudwatch) seems to be missing a chunk and is thus unreadable.

**Comment by dankohn** [comment]
Thanks, Brian. We'll fix in the next update.

**Comment by shawnpreissner** [comment]
Hi @brian-brazil this was fixed in 0.9.5 https://github.com/cncf/landscape/blob/master/landscape/CloudNativeLandscape_v0.9.5_cncf.jpg 
Thanks
