### ISSUE TITLE
Adding Arquillian Cube as Kubernetes testing library

### ISSUE THREAD

**Issue by lordofthejars** [cncf/landscape#98]
Currently we have developed a library (Arquillian Cube) that can be used to test applications that are deployed in Docker (http://arquillian.org/arquillian-cube/#_basic_example) or test applications that are deployed in Kubernetes (and OpenShift) (http://arquillian.org/arquillian-cube/#_kubernetes)

This project is sponsored by Red Hat and home page is at http://arquillian.org/

**Comment by shawnpreissner** [comment]
Hi @lordofthejars thanks for the message, Arquillian looks cool. Unfortunately, due to real estate challenges, we don't see a great category fit at this time. Keep up the good work!
