### ISSUE TITLE
Wrong Helm logo in 'Infrastructure Automation'

### ISSUE THREAD

**Issue by lennypruss** [cncf/landscape#99]
Use this version:

https://datamountaineer.com/wp-content/uploads/2016/09/helm.png

**Comment by shawnpreissner** [comment]
Hi @lennypruss thanks and this will be corrected in the upcoming version

**Comment by shawnpreissner** [comment]
Thanks @lennypruss, closing as this update was included in the most recent version https://github.com/cncf/landscape#current-version
